<?php
return [
    'listen' => 'http://0.0.0.0:8788',
    'transport' => 'tcp',
    'context' => [],
    'name' => 'webman',
    'count' => cpu_count() * 2,
    'user' => '',
    'group' => '',
    'reusePort' => false,
    'event_loop' => '',
    'pid_file' => runtime_path() . '/webman.pid',
    'pidFile' => runtime_path() . '/webman.pid',
    'status_file' => runtime_path() . '/webman.status',
    'statusFile' => runtime_path() . '/webman.status',
    'stdout_file' => runtime_path() . '/logs/out.log',
    'log_file' => runtime_path() . '/logs/workerman.log',
    'logFile' => runtime_path() . '/logs/workerman.log',
    'max_package_size' => 10 * 1024 * 1024,
    'maxPackageSize' => 10 * 1024 * 1024,
    'stop_timeout' => 2,
];
