# -*- coding: utf-8 -*-
# 葡萄牙语翻译词典（versions + install-review）
TRANS = {
"docs/versions.md": {
"# 版本对比": "# Comparação de versões",
"| 版本 | 授权 | 获取方式 |": "| Versão | Licença | Como obter |",
"| **简化版 (Lite)** | 开源 (MIT) | GitHub 公开仓库 |": "| **Lite** | Open source (MIT) | Repositório público do GitHub |",
"| **标准版 (Standard)** | 商业授权 | 联系 erik@erik.xyz |": "| **Standard** | Licença comercial | Contate erik@erik.xyz |",
"| **完整版 (Full)** | 商业授权 | 联系 erik@erik.xyz |": "| **Full** | Licença comercial | Contate erik@erik.xyz |",
"## 功能对比": "## Comparação de funcionalidades",
"### 基础功能": "### Funcionalidades básicas",
"| 功能 | Lite | Standard | Full |": "| Funcionalidade | Lite | Standard | Full |",
"| 认证 (登录/Token刷新/当前用户) | ✅ | ✅ | ✅ |": "| Autenticação (login/refresh de Token/usuário atual) | ✅ | ✅ | ✅ |",
"| 平台管理 (29 平台列表 + OAuth) | ✅ | ✅ | ✅ |": "| Gerenciamento de plataformas (lista de 29 plataformas + OAuth) | ✅ | ✅ | ✅ |",
"| 账户管理 (CRUD + 同步) | ✅ | ✅ | ✅ |": "| Gerenciamento de contas (CRUD + sincronização) | ✅ | ✅ | ✅ |",
"| 广告计划 (CRUD + 启停 + 批量) | ✅ | ✅ | ✅ |": "| Planos de anúncios (CRUD + iniciar/pausar + em lote) | ✅ | ✅ | ✅ |",
"| 报表 (仪表盘 + 自定义 + 导出 CSV/Excel/PDF) | ✅ | ✅ | ✅ |": "| Relatórios (dashboard + personalizado + exportação CSV/Excel/PDF) | ✅ | ✅ | ✅ |",
"| 健康检查 + API 文档 + 验证码 | ✅ | ✅ | ✅ |": "| Verificação de saúde + documentação da API + captcha | ✅ | ✅ | ✅ |",
"| 数据同步 (Campaign + Report) | ✅ | ✅ | ✅ |": "| Sincronização de dados (Campaign + Report) | ✅ | ✅ | ✅ |",
"### 投放管理": "### Gerenciamento de veiculação",
"| 广告组 (CRUD + 启停) | — | ✅ | ✅ |": "| Grupos de anúncios (CRUD + iniciar/pausar) | — | ✅ | ✅ |",
"| 广告创意 (列表 + 详情) | — | ✅ | ✅ |": "| Criativos (lista + detalhes) | — | ✅ | ✅ |",
"| 广告组/创意数据同步 | — | ✅ | ✅ |": "| Sincronização de dados de grupos de anúncios/criativos | — | ✅ | ✅ |",
"### 监控与通知": "### Monitoramento e notificações",
"| 告警规则引擎 (7 指标/4 条件/3 范围) | — | ✅ | ✅ |": "| Engine de regras de alerta (7 métricas/4 condições/3 escopos) | — | ✅ | ✅ |",
"| 告警记录 + 确认 + 未读数 | — | ✅ | ✅ |": "| Registros de alertas + confirmação + não lidos | — | ✅ | ✅ |",
"| 通知中心 (列表/已读/全部已读) | — | ✅ | ✅ |": "| Central de notificações (lista/lidas/todas lidas) | — | ✅ | ✅ |",
"### 高级功能": "### Funcionalidades avançadas",
"| 自动出价规则引擎 (3 动作/冷却) | — | — | ✅ |": "| Engine de regras de lance automático (3 ações/resfriamento) | — | — | ✅ |",
"| 受众定向模板 (通用 JSON Schema) | — | — | ✅ |": "| Modelos de segmentação de público (JSON Schema genérico) | — | — | ✅ |",
"| 广告素材库 (上传/画廊/预览) | — | — | ✅ |": "| Biblioteca de materiais de anúncios (upload/galeria/prévia) | — | — | ✅ |",
"| 预算预警 (三段告警 50/80/100%) | — | — | ✅ |": "| Alerta de orçamento (alertas em três níveis 50/80/100%) | — | — | ✅ |",
"| 投放日历 (Gantt 可视化) | — | — | ✅ |": "| Calendário de veiculação (visualização Gantt) | — | — | ✅ |",
"| 跨平台归因 (5 模型/30 天回溯) | — | — | ✅ |": "| Atribuição entre plataformas (5 modelos/retrospectiva de 30 dias) | — | — | ✅ |",
"## 安全防护对比": "## Comparação de proteções de segurança",
"| 防护项 | Lite | Standard | Full |": "| Item de proteção | Lite | Standard | Full |",
"| CORS 白名单 | ✅ | ✅ | ✅ |": "| Lista de permissões CORS | ✅ | ✅ | ✅ |",
"| 安全响应头 (X-Frame/CSP/HSTS/nosniff) | ✅ | ✅ | ✅ |": "| Cabeçalhos de segurança (X-Frame/CSP/HSTS/nosniff) | ✅ | ✅ | ✅ |",
"| 版本路由 (X-API-Version) | ✅ | ✅ | ✅ |": "| Roteamento por versão (X-API-Version) | ✅ | ✅ | ✅ |",
"| 接口限流 (滑动窗口) | ✅ | ✅ | ✅ |": "| Rate limit de API (janela deslizante) | ✅ | ✅ | ✅ |",
"| SQL 注入检测 (模式匹配) | ✅ | ✅ | ✅ |": "| Detecção de injeção de SQL (correspondência de padrões) | ✅ | ✅ | ✅ |",
"| 输入过滤 (strip_tags + trim) | ✅ | ✅ | ✅ |": "| Filtragem de entrada (strip_tags + trim) | ✅ | ✅ | ✅ |",
"| 传输加解密 (X-Encrypted) | ✅ | ✅ | ✅ |": "| Criptografia de transporte (X-Encrypted) | ✅ | ✅ | ✅ |",
"| JWT Bearer 认证 | ✅ | ✅ | ✅ |": "| Autenticação JWT Bearer | ✅ | ✅ | ✅ |",
"| XSS 攻击检测 (11 模式) | — | ✅ | ✅ |": "| Detecção de ataques XSS (11 padrões) | — | ✅ | ✅ |",
"| 路径遍历检测 (7 模式) | — | ✅ | ✅ |": "| Detecção de path traversal (7 padrões) | — | ✅ | ✅ |",
"| Header 注入检测 | — | ✅ | ✅ |": "| Detecção de injeção de Header | — | ✅ | ✅ |",
"| Body 大小限制 (10 MiB) | — | ✅ | ✅ |": "| Limite de tamanho do body (10 MiB) | — | ✅ | ✅ |",
"| Content-Type 白名单 | — | ✅ | ✅ |": "| Lista de permissões Content-Type | — | ✅ | ✅ |",
"| 客户端来源识别 (8 端) | — | ✅ | ✅ |": "| Identificação da origem do cliente (8 plataformas) | — | ✅ | ✅ |",
"| 登录节流 (5次→15分钟) | — | ✅ | ✅ |": "| Throttle de login (5 falhas→15 minutos) | — | ✅ | ✅ |",
"| 响应时间监控 (X-Response-Time) | — | ✅ | ✅ |": "| Monitoramento do tempo de resposta (X-Response-Time) | — | ✅ | ✅ |",
"| Origin/Referer 校验 | — | — | ✅ |": "| Validação Origin/Referer | — | — | ✅ |",
"| 防重放攻击 (Nonce+Timestamp) | — | — | ✅ |": "| Anti-replay (Nonce+Timestamp) | — | — | ✅ |",
"| 并发会话限制 (最大3个) | — | — | ✅ |": "| Limite de sessões concorrentes (máximo de 3) | — | — | ✅ |",
"| CSRF Token (Admin端) | — | — | ✅ |": "| CSRF Token (lado Admin) | — | — | ✅ |",
"| SSRF 防护 (OAuth 白名单) | — | — | ✅ |": "| Proteção SSRF (lista de permissões OAuth) | — | — | ✅ |",
"| 日志数据脱敏 | — | — | ✅ |": "| Mascaramento de dados em logs | — | — | ✅ |",
"| JWT IP/UA 绑定 | — | — | ✅ |": "| Vínculo JWT IP/UA | — | — | ✅ |",
"## 中间件链对比": "## Comparação das cadeias de middleware",
"### Service 端": "### Lado Service",
"| Lite (7 层) | Standard (11 层) | Full (15 层) |": "| Lite (7 camadas) | Standard (11 camadas) | Full (15 camadas) |",
"### Admin 端": "### Lado Admin",
"| Lite (1 层) | Standard (4 层) | Full (5 层) |": "| Lite (1 camada) | Standard (4 camadas) | Full (5 camadas) |",
"## 定时任务对比": "## Comparação de tarefas agendadas",
"| 任务 | 频率 | Lite | Standard | Full |": "| Tarefa | Frequência | Lite | Standard | Full |",
"| DataSyncTask | 10min | ✅ (仅 Campaign+Report) | ✅ (+AdGroup+Creative) | ✅ (+AdGroup+Creative) |": "| DataSyncTask | 10min | ✅ (apenas Campaign+Report) | ✅ (+AdGroup+Creative) | ✅ (+AdGroup+Creative) |",
"## 数据库表对比": "## Comparação de tabelas do banco de dados",
"| 分类 | 表名 | Lite | Standard | Full |": "| Categoria | Nome da tabela | Lite | Standard | Full |",
"| 基础 | erik_tenants | ✅ | ✅ | ✅ |": "| Base | erik_tenants | ✅ | ✅ | ✅ |",
"| 账户 | erik_platform_accounts | ✅ | ✅ | ✅ |": "| Contas | erik_platform_accounts | ✅ | ✅ | ✅ |",
"| 投放 | erik_campaigns | ✅ | ✅ | ✅ |": "| Veiculação | erik_campaigns | ✅ | ✅ | ✅ |",
"| 告警 | erik_alert_rules | — | ✅ | ✅ |": "| Alertas | erik_alert_rules | — | ✅ | ✅ |",
"| 通知 | erik_notifications | — | ✅ | ✅ |": "| Notificações | erik_notifications | — | ✅ | ✅ |",
"| 出价 | erik_bid_rules | — | — | ✅ |": "| Lances | erik_bid_rules | — | — | ✅ |",
"| 定向 | erik_targeting_templates | — | — | ✅ |": "| Segmentação | erik_targeting_templates | — | — | ✅ |",
"| 素材 | erik_assets | — | — | ✅ |": "| Materiais | erik_assets | — | — | ✅ |",
"| 归因 | erik_conversions | — | — | ✅ |": "| Atribuição | erik_conversions | — | — | ✅ |",
"| 系统 | erik_sync_errors | ✅ | ✅ | ✅ |": "| Sistema | erik_sync_errors | ✅ | ✅ | ✅ |",
"| 管理 | admin_users/roles/audit_logs | ✅ | ✅ | ✅ |": "| Administração | admin_users/roles/audit_logs | ✅ | ✅ | ✅ |",
"| **合计** | | **8** | **13** | **18** |": "| **Total** | | **8** | **13** | **18** |",
"## 前端页面对比": "## Comparação de páginas do frontend",
"| 页面 | Lite | Standard | Full |": "| Página | Lite | Standard | Full |",
"| 登录 | ✅ | ✅ | ✅ |": "| Login | ✅ | ✅ | ✅ |",
"| 仪表盘 | ✅ | ✅ | ✅ |": "| Dashboard | ✅ | ✅ | ✅ |",
"| 账户列表 + 绑定 | ✅ | ✅ | ✅ |": "| Lista de contas + vínculo | ✅ | ✅ | ✅ |",
"| 广告计划 | ✅ | ✅ | ✅ |": "| Planos de anúncios | ✅ | ✅ | ✅ |",
"| 报表导出 | ✅ | ✅ | ✅ |": "| Exportação de relatórios | ✅ | ✅ | ✅ |",
"| 用户管理 | ✅ | ✅ | ✅ |": "| Gerenciamento de usuários | ✅ | ✅ | ✅ |",
"| 审计日志 | ✅ | ✅ | ✅ |": "| Logs de auditoria | ✅ | ✅ | ✅ |",
"| 广告组 | — | ✅ | ✅ |": "| Grupos de anúncios | — | ✅ | ✅ |",
"| 广告创意 | — | ✅ | ✅ |": "| Criativos | — | ✅ | ✅ |",
"| 报表分析 (ECharts) | — | ✅ | ✅ |": "| Análise de relatórios (ECharts) | — | ✅ | ✅ |",
"| 告警规则 | — | ✅ | ✅ |": "| Regras de alerta | — | ✅ | ✅ |",
"| 告警记录 | — | ✅ | ✅ |": "| Registros de alertas | — | ✅ | ✅ |",
"| 通知中心 | — | ✅ | ✅ |": "| Central de notificações | — | ✅ | ✅ |",
"| 自动出价 | — | — | ✅ |": "| Lance automático | — | — | ✅ |",
"| 素材库 | — | — | ✅ |": "| Biblioteca de materiais | — | — | ✅ |",
"| 投放日历 | — | — | ✅ |": "| Calendário de veiculação | — | — | ✅ |",
"| 归因分析 | — | — | ✅ |": "| Análise de atribuição | — | — | ✅ |",
"| **合计** | **7** | **13** | **17** |": "| **Total** | **7** | **13** | **17** |",
"| 广告计划 (列表+详情) | ✅ | ✅ | ✅ |": "| Planos de anúncios (lista+detalhes) | ✅ | ✅ | ✅ |",
"| 数据报表 | ✅ | ✅ | ✅ |": "| Relatórios de dados | ✅ | ✅ | ✅ |",
"| 平台账户 | ✅ | ✅ | ✅ |": "| Contas de plataforma | ✅ | ✅ | ✅ |",
"| 告警管理 | ✅ | ✅ | ✅ |": "| Gerenciamento de alertas | ✅ | ✅ | ✅ |",
"| 报表分析 | — | ✅ | ✅ |": "| Análise de relatórios | — | ✅ | ✅ |",
"| **合计** | **6** | **10** | **11** |": "| **Total** | **6** | **10** | **11** |",
"## API 端点对比": "## Comparação de endpoints da API",
"| 模块 | Lite | Standard | Full |": "| Módulo | Lite | Standard | Full |",
"| 系统 (health/ping/docs/captcha) | 6 | 6 | 6 |": "| Sistema (health/ping/docs/captcha) | 6 | 6 | 6 |",
"| 认证 (login/me/refresh) | 3 | 3 | 3 |": "| Autenticação (login/me/refresh) | 3 | 3 | 3 |",
"| 平台 (list/oauthUrl/callback) | 3 | 3 | 3 |": "| Plataformas (list/oauthUrl/callback) | 3 | 3 | 3 |",
"| 账户 (index/show/destroy/sync) | 4 | 4 | 4 |": "| Contas (index/show/destroy/sync) | 4 | 4 | 4 |",
"| 广告计划 (CRUD/toggle/batch) | 6 | 6 | 6 |": "| Planos de anúncios (CRUD/toggle/batch) | 6 | 6 | 6 |",
"| 广告组 (CRUD/toggle) | — | 5 | 5 |": "| Grupos de anúncios (CRUD/toggle) | — | 5 | 5 |",
"| 创意 (index/show) | — | 2 | 2 |": "| Criativos (index/show) | — | 2 | 2 |",
"| 报表 (summary/custom/export×2) | 4 | 4 | 4 |": "| Relatórios (summary/custom/export×2) | 4 | 4 | 4 |",
"| 报表 (calendar/budget/attribution/models) | — | — | 4 |": "| Relatórios (calendar/budget/attribution/models) | — | — | 4 |",
"| 告警 (rules CRUD + logs + acknowledge + unread) | — | 7 | 7 |": "| Alertas (CRUD de rules + logs + acknowledge + unread) | — | 7 | 7 |",
"| 通知 (index/unread/read/readAll) | — | 4 | 4 |": "| Notificações (index/unread/read/readAll) | — | 4 | 4 |",
"| 自动出价 (CRUD + logs) | — | — | 5 |": "| Lance automático (CRUD + logs) | — | — | 5 |",
"| 定向模板 (CRUD) | — | — | 5 |": "| Modelos de segmentação (CRUD) | — | — | 5 |",
"| 素材库 (index/upload/show/destroy) | — | — | 4 |": "| Biblioteca de materiais (index/upload/show/destroy) | — | — | 4 |",
"| **合计** | **26** | **44** | **62** |": "| **Total** | **26** | **44** | **62** |",
"## 技术栈": "## Stack de tecnologia",
"三层版本共享统一技术栈：": "As três versões compartilham uma stack de tecnologia unificada:",
"| 层 | 技术 |": "| Camada | Tecnologia |",
"| 后端框架 | webman v2, PHP 8.2+ |": "| Framework backend | webman v2, PHP 8.2+ |",
"| 数据库 | MySQL 8.0 (InnoDB, utf8mb4) |": "| Banco de dados | MySQL 8.0 (InnoDB, utf8mb4) |",
"| 缓存 | Redis 7 |": "| Cache | Redis 7 |",
"| 认证 | erikwang2013/jwt-webman |": "| Autenticação | erikwang2013/jwt-webman |",
"| ID 生成 | erikwang2013/snowflake-php |": "| Geração de ID | erikwang2013/snowflake-php |",
"| ID 编码 | erikwang2013/hashids |": "| Codificação de ID | erikwang2013/hashids |",
"| 前端 | Vue 3 + TypeScript + Element Plus + ECharts + Pinia |": "| Frontend | Vue 3 + TypeScript + Element Plus + ECharts + Pinia |",
"| 部署 | Docker + Nginx + Docker Compose |": "| Implantação | Docker + Nginx + Docker Compose |",
"## 升级路径": "## Caminho de upgrade",
},
"docs/install-review.md": {
"# Ads-PHP 安全审查与修复报告（第 3 轮）": "# Relatório de revisão e correção de segurança do Ads-PHP (3ª rodada)",
"**生成时间**: 2026-08-04  ": "**Gerado em**: 2026-08-04  ",
"**审查范围**: 全部安全中间件、认证流程、安装控制器、配置文件  ": "**Escopo da revisão**: todos os middlewares de segurança, fluxo de autenticação, controlador de instalação e arquivos de configuração  ",
"**PHP 版本**: 8.3.7 | **框架**: webman v2  ": "**Versão do PHP**: 8.3.7 | **Framework**: webman v2  ",
"## 一、修复概览": "## 1. Visão geral das correções",
"本轮针对第 2 轮安全审查发现的 6 个问题进行了全面修复。": "Esta rodada corrigiu completamente os 6 problemas encontrados na 2ª rodada de revisão de segurança.",
"| # | 问题 | 修复方式 | 状态 |": "| # | Problema | Forma de correção | Status |",
"| 1 | admin 端缺少 5 个安全中间件 | 新建 CorsMiddleware / SecurityHeadersMiddleware / RateLimitMiddleware / SqlGuardMiddleware / ValidationMiddleware | 已修复 |": "| 1 | Faltam 5 middlewares de segurança no admin | Criados CorsMiddleware / SecurityHeadersMiddleware / RateLimitMiddleware / SqlGuardMiddleware / ValidationMiddleware | Corrigido |",
"| 2 | admin AuthCheck 不做 IP/UA 绑定 | AuthController JWT payload 加入 `_ip` / `_ua`，AuthCheck 校验绑定 | 已修复 |": "| 2 | O AuthCheck do admin não faz vínculo de IP/UA | AuthController adiciona `_ip` / `_ua` ao payload do JWT, AuthCheck valida o vínculo | Corrigido |",
"| 3 | AttackGuardMiddleware ReDoS 风险 | 新增 `maxStrLen=8192` 预检查，超长字符串直接拒绝 | 已修复 |": "| 3 | Risco de ReDoS no AttackGuardMiddleware | Adicionada verificação prévia `maxStrLen=8192`; strings muito longas são rejeitadas diretamente | Corrigido |",
"| 4 | InstallController 密码特殊字符 | 新增 `envQuote()` 方法，自动引号包裹 + 转义 | 已修复 |": "| 4 | Caracteres especiais de senha no InstallController | Adicionado o método `envQuote()` que envolve com aspas e faz escape automaticamente | Corrigido |",
"| 5 | admin 中间件配置不完整 | 更新为 10 层全局中间件栈 | 已修复 |": "| 5 | Configuração de middleware do admin incompleta | Atualizada para uma pilha de 10 camadas de middleware global | Corrigido |",
"| 6 | README 中间件层数过时 | 中英文 README 同步更新 | 已修复 |": "| 6 | Número de camadas de middleware desatualizado no README | README em chinês e inglês atualizados em sincronia | Corrigido |",
"## 二、语法验证": "## 2. Validação de sintaxe",
"| 文件 | 行数 | 语法 |": "| Arquivo | Linhas | Sintaxe |",
"| `admin/app/middleware/CorsMiddleware.php` | 73 | 通过 |": "| `admin/app/middleware/CorsMiddleware.php` | 73 | Aprovado |",
"| `admin/app/middleware/SecurityHeadersMiddleware.php` | 41 | 通过 |": "| `admin/app/middleware/SecurityHeadersMiddleware.php` | 41 | Aprovado |",
"| `admin/app/middleware/RateLimitMiddleware.php` | 53 | 通过 |": "| `admin/app/middleware/RateLimitMiddleware.php` | 53 | Aprovado |",
"| `admin/app/middleware/SqlGuardMiddleware.php` | 40 | 通过 |": "| `admin/app/middleware/SqlGuardMiddleware.php` | 40 | Aprovado |",
"| `admin/app/middleware/ValidationMiddleware.php` | 39 | 通过 |": "| `admin/app/middleware/ValidationMiddleware.php` | 39 | Aprovado |",
"| `admin/app/middleware/AttackGuardMiddleware.php` | 99 | 通过 |": "| `admin/app/middleware/AttackGuardMiddleware.php` | 99 | Aprovado |",
"| `admin/app/middleware/AuthCheck.php` | 48 | 通过 |": "| `admin/app/middleware/AuthCheck.php` | 48 | Aprovado |",
"| `admin/app/controller/AuthController.php` | 194 | 通过 |": "| `admin/app/controller/AuthController.php` | 194 | Aprovado |",
"| `admin/app/controller/InstallController.php` | 298 | 通过 |": "| `admin/app/controller/InstallController.php` | 298 | Aprovado |",
"| `admin/config/middleware.php` | 43 | 通过 |": "| `admin/config/middleware.php` | 43 | Aprovado |",
"| `service/plugin/ads-api/middleware/AttackGuardMiddleware.php` | 99 | 通过 |": "| `service/plugin/ads-api/middleware/AttackGuardMiddleware.php` | 99 | Aprovado |",
"## 三、中间件栈（修复后）": "## 3. Pilha de middlewares (após correção)",
"### Service 端 (14 层全局 + AuthMiddleware)": "### Lado Service (14 camadas globais + AuthMiddleware)",
"### Admin 端 (10 层全局 + AuthCheck)": "### Lado Admin (10 camadas globais + AuthCheck)",
"### 路由矩阵（admin 端更新后）": "### Matriz de rotas (após atualização do lado admin)",
"| 路由 | CORS | SecHdr | Attack | Platform | Version | RateLimit | LoginThr | SQLGuard | Valid | CSRF | Auth |": "| Rota | CORS | SecHdr | Attack | Platform | Version | RateLimit | LoginThr | SQLGuard | Valid | CSRF | Auth |",
"| /api/admin/* (保护) | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | — | ✓ | ✓ | ✓ | ✓ |": "| /api/admin/* (protegido) | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | — | ✓ | ✓ | ✓ | ✓ |",
"## 四、安全改进详情": "## 4. Detalhes das melhorias de segurança",
"### 4.1 admin 新增中间件": "### 4.1 Novos middlewares no admin",
"| 中间件 | 文件 | 职责 |": "| Middleware | Arquivo | Responsabilidade |",
"| CorsMiddleware | `admin/app/middleware/CorsMiddleware.php` | CORS 预检 + 响应头，debug 模式放行所有，生产白名单 |": "| CorsMiddleware | `admin/app/middleware/CorsMiddleware.php` | Preflight CORS + cabeçalhos de resposta; no modo debug libera tudo, em produção usa lista de permissões |",
"| RateLimitMiddleware | `admin/app/middleware/RateLimitMiddleware.php` | Redis 滑动窗口限流 60req/60s |": "| RateLimitMiddleware | `admin/app/middleware/RateLimitMiddleware.php` | Rate limit com janela deslizante no Redis 60 req/60s |",
"| SqlGuardMiddleware | `admin/app/middleware/SqlGuardMiddleware.php` | SQL 注入模式检测（UNION/DROP/ALTER/注释符） |": "| SqlGuardMiddleware | `admin/app/middleware/SqlGuardMiddleware.php` | Detecção de padrões de injeção de SQL (UNION/DROP/ALTER/comentários) |",
"| ValidationMiddleware | `admin/app/middleware/ValidationMiddleware.php` | 输入 trim + strip_tags（排除 description/content/extra） |": "| ValidationMiddleware | `admin/app/middleware/ValidationMiddleware.php` | trim + strip_tags na entrada (exceto description/content/extra) |",
"### 4.2 JWT Token 绑定": "### 4.2 Vínculo do JWT Token",
"AuthController 登录时在 JWT payload 中加入 `_ip` 和 `_ua`：": "O AuthController adiciona `_ip` e `_ua` ao payload do JWT no login:",
"AuthCheck 中间件验证 token 时检查 IP 和 UA 一致性，不一致则拒绝访问。": "O middleware AuthCheck verifica a consistência de IP e UA ao validar o token; se não corresponderem, o acesso é negado.",
"### 4.3 ReDoS 防护": "### 4.3 Proteção contra ReDoS",
"AttackGuardMiddleware（admin + service）新增 `maxStrLen = 8192`：": "O AttackGuardMiddleware (admin + service) ganhou `maxStrLen = 8192`:",
"### 4.4 .env 密码转义": "### 4.4 Escape de senha no .env",
"InstallController 新增 `envQuote()` 方法，检测密码中的特殊字符（空格、`$`、`#`、引号、反斜杠），自动用双引号包裹并转义。": "O InstallController ganhou o método `envQuote()`, que detecta caracteres especiais na senha (espaço, `$`, `#`, aspas, barra invertida) e automaticamente envolve com aspas duplas e faz escape.",
"## 五、文件清单": "## 5. Lista de arquivos",
"### 新增（5 文件）": "### Novos (5 arquivos)",
"| 文件 | 行数 | 说明 |": "| Arquivo | Linhas | Descrição |",
"| `admin/app/middleware/CorsMiddleware.php` | 73 | CORS 中间件 |": "| `admin/app/middleware/CorsMiddleware.php` | 73 | Middleware CORS |",
"| `admin/app/middleware/SecurityHeadersMiddleware.php` | 41 | 安全响应头 |": "| `admin/app/middleware/SecurityHeadersMiddleware.php` | 41 | Cabeçalhos de segurança |",
"| `admin/app/middleware/RateLimitMiddleware.php` | 53 | 全局限流 |": "| `admin/app/middleware/RateLimitMiddleware.php` | 53 | Rate limit global |",
"| `admin/app/middleware/SqlGuardMiddleware.php` | 40 | SQL 注入检测 |": "| `admin/app/middleware/SqlGuardMiddleware.php` | 40 | Detecção de injeção de SQL |",
"| `admin/app/middleware/ValidationMiddleware.php` | 39 | 输入清洗 |": "| `admin/app/middleware/ValidationMiddleware.php` | 39 | Limpeza de entrada |",
"### 修改（6 文件）": "### Modificados (6 arquivos)",
"| 文件 | 变更 |": "| Arquivo | Alteração |",
"| `admin/config/middleware.php` | 全局中间件 5→10 层 |": "| `admin/config/middleware.php` | Middleware global de 5→10 camadas |",
"| `admin/app/middleware/AttackGuardMiddleware.php` | 新增 ReDoS 防护（maxStrLen） |": "| `admin/app/middleware/AttackGuardMiddleware.php` | Adicionada proteção contra ReDoS (maxStrLen) |",
"| `admin/app/middleware/AuthCheck.php` | 新增 JWT IP/UA 绑定校验 |": "| `admin/app/middleware/AuthCheck.php` | Adicionada validação de vínculo JWT IP/UA |",
"| `admin/app/controller/AuthController.php` | JWT payload 加入 _ip/_ua |": "| `admin/app/controller/AuthController.php` | _ip/_ua adicionados ao payload do JWT |",
"| `admin/app/controller/InstallController.php` | 新增 envQuote() 密码转义 |": "| `admin/app/controller/InstallController.php` | Adicionado escape de senha envQuote() |",
"| `service/plugin/ads-api/middleware/AttackGuardMiddleware.php` | 新增 ReDoS 防护（maxStrLen） |": "| `service/plugin/ads-api/middleware/AttackGuardMiddleware.php` | Adicionada proteção contra ReDoS (maxStrLen) |",
"## 六、结论": "## 6. Conclusão",
"全部 6 个安全问题已修复。admin 端防御从 5 层增加到 10 层全局中间件，补齐了安全响应头、限流、SQL 注入检测、输入清洗、CORS 5 个关键防护。JWT token 增加了 IP/UA 绑定验证。ReDoS 风险和 .env 密码特殊字符问题已消除。所有文件通过 PHP 语法检查。": "Todos os 6 problemas de segurança foram corrigidos. A defesa do admin passou de 5 para 10 camadas de middleware global, completando 5 proteções-chave: cabeçalhos de segurança, rate limit, detecção de injeção de SQL, limpeza de entrada e CORS. O JWT token ganhou validação de vínculo IP/UA. O risco de ReDoS e o problema de caracteres especiais de senha no .env foram eliminados. Todos os arquivos passaram na verificação de sintaxe do PHP.",
},
}
