# -*- coding: utf-8 -*-
# 葡萄牙语翻译词典（architecture + features）
TRANS = {
"docs/architecture.md": {
"# 架构设计文档": "# Documento de design de arquitetura",
"## 1. 系统概述": "## 1. Visão geral do sistema",
"多平台广告管理系统，对接 **29 个广告平台**，覆盖投放管理、跨平台报表、告警监控、自动出价、受众定向。支持 SaaS 多租户、代运营、自用三种模式。": "Sistema de gerenciamento de publicidade multiplataforma, integrando **29 plataformas de publicidade**, cobrindo gerenciamento de veiculação, relatórios entre plataformas, monitoramento de alertas, lances automáticos e segmentação de público. Suporta três modos: SaaS multitenant, operação terceirizada e uso próprio.",
"## 2. 部署架构": "## 2. Arquitetura de implantação",
"## 3. 请求处理管道": "## 3. Pipeline de processamento de requisições",
"### 3.1 Service 端 (15 层中间件)": "### 3.1 Lado Service (15 camadas de middleware)",
"### 3.2 Admin 端 (6 层中间件)": "### 3.2 Lado Admin (6 camadas de middleware)",
"## 4. 目录结构": "## 4. Estrutura de diretórios",
"## 5. 数据模型": "## 5. Modelo de dados",
"### 5.1 表分类": "### 5.1 Classificação das tabelas",
"| 分类 | 表名 | 主键 | 用途 |": "| Categoria | Nome da tabela | Chave primária | Finalidade |",
"| 基础 | `erik_tenants` | BIGINT Snowflake | 多租户 |": "| Base | `erik_tenants` | BIGINT Snowflake | Multitenant |",
"| 账户 | `erik_platform_accounts`, `erik_auth_tokens` | BIGINT Snowflake | OAuth 平台账户 |": "| Contas | `erik_platform_accounts`, `erik_auth_tokens` | BIGINT Snowflake | Contas de plataforma OAuth |",
"| 投放层级 | `erik_campaigns`, `erik_ad_groups`, `erik_creatives` | BIGINT Snowflake | 广告投放 |": "| Hierarquia de veiculação | `erik_campaigns`, `erik_ad_groups`, `erik_creatives` | BIGINT Snowflake | Veiculação de anúncios |",
"| 报表 | `erik_report_metrics`, `erik_report_extras` | BIGINT Snowflake | 统一指标 |": "| Relatórios | `erik_report_metrics`, `erik_report_extras` | BIGINT Snowflake | Métricas unificadas |",
"| 告警 | `erik_alert_rules`, `erik_alert_logs` | BIGINT Snowflake | 监控告警 |": "| Alertas | `erik_alert_rules`, `erik_alert_logs` | BIGINT Snowflake | Monitoramento de alertas |",
"| 出价 | `erik_bid_rules`, `erik_bid_logs` | BIGINT Snowflake | 自动出价 |": "| Lances | `erik_bid_rules`, `erik_bid_logs` | BIGINT Snowflake | Lance automático |",
"| 定向 | `erik_targeting_templates` | BIGINT Snowflake | 受众模板 |": "| Segmentação | `erik_targeting_templates` | BIGINT Snowflake | Modelos de público |",
"| 素材 | `erik_assets` | BIGINT Snowflake | 创意素材库 |": "| Materiais | `erik_assets` | BIGINT Snowflake | Biblioteca de materiais criativos |",
"| 通知 | `erik_notifications` | BIGINT Snowflake | 站内通知 |": "| Notificações | `erik_notifications` | BIGINT Snowflake | Notificações no sistema |",
"| 归因 | `erik_conversions`, `erik_attribution_results` | BIGINT Snowflake | 转化追踪 + 归因 |": "| Atribuição | `erik_conversions`, `erik_attribution_results` | BIGINT Snowflake | Rastreamento de conversões + atribuição |",
"| 系统 | `erik_sync_errors` | BIGINT Snowflake | 同步错误 |": "| Sistema | `erik_sync_errors` | BIGINT Snowflake | Erros de sincronização |",
"| 管理 | `admin_users`, `admin_roles`, `admin_audit_logs` | BIGINT Snowflake | RBAC + 审计 |": "| Administração | `admin_users`, `admin_roles`, `admin_audit_logs` | BIGINT Snowflake | RBAC + auditoria |",
"### 5.2 命名规范": "### 5.2 Convenção de nomenclatura",
"- 表前缀: `erik_`": "- Prefixo de tabela: `erik_`",
"- 主键: `BIGINT UNSIGNED PRIMARY KEY` (无自增, Snowflake ID)": "- Chave primária: `BIGINT UNSIGNED PRIMARY KEY` (sem autoincremento, Snowflake ID)",
"- 引擎: InnoDB, 字符集: utf8mb4": "- Engine: InnoDB, charset: utf8mb4",
"- 时间戳: `created_at`, `updated_at` (DATETIME)": "- Timestamps: `created_at`, `updated_at` (DATETIME)",
"## 6. 安全架构": "## 6. Arquitetura de segurança",
"### 6.1 防护层次": "### 6.1 Camadas de proteção",
"| 层 | 机制 | 覆盖范围 |": "| Camada | Mecanismo | Cobertura |",
"| 传输 | Nginx (SSL 终结) | 全量 |": "| Transporte | Nginx (terminação SSL) | Total |",
"| 网络 | CORS 白名单 + Origin 校验 + HSTS | Service |": "| Rede | Lista de permissões CORS + validação de Origin + HSTS | Service |",
"| 输入 | AttackGuard (XSS 11模式/路径遍历 7模式/Header注入) | Service + Admin |": "| Entrada | AttackGuard (XSS 11 padrões/path traversal 7 padrões/Injeção de Header) | Service + Admin |",
"| 注入 | SQLGuard (SQL 注入模式检测) | Service |": "| Injeção | SQLGuard (detecção de padrões de injeção de SQL) | Service |",
"| 清洗 | ValidationMiddleware (strip_tags) | Service |": "| Limpeza | ValidationMiddleware (strip_tags) | Service |",
"| 认证 | JWT Bearer + bcrypt + IP/UA 绑定 + refresh 轮换 | Service |": "| Autenticação | JWT Bearer + bcrypt + vínculo IP/UA + rotação de refresh | Service |",
"| 认证 | Session + JWT 双通道 + CSRF Token | Admin |": "| Autenticação | Sessão + JWT em dois canais + CSRF Token | Admin |",
"| 授权 | RBAC (角色 + 权限 JSON) | Admin |": "| Autorização | RBAC (papéis + JSON de permissões) | Admin |",
"| 节流 | RateLimit (滑动窗口) + LoginThrottle (5次→15分钟) | Service + Admin |": "| Throttle | RateLimit (janela deslizante) + LoginThrottle (5 falhas→15 minutos) | Service + Admin |",
"| 会话 | SessionLimit (最大3个活跃Token) + 黑名单 | Service |": "| Sessão | SessionLimit (máximo de 3 Tokens ativos) + lista negra | Service |",
"| 加密 | EncryptionMiddleware (传输) + Encryptable (存储) | Service |": "| Criptografia | EncryptionMiddleware (transporte) + Encryptable (armazenamento) | Service |",
"| 重放 | ReplayGuard (Nonce+Timestamp ±5min, 非浏览器端) | Service + 客户端 |": "| Replay | ReplayGuard (Nonce+Timestamp ±5min, fora do navegador) | Service + clientes |",
"| 审计 | 操作轨迹 (IP/UA/平台) | Admin |": "| Auditoria | Trilha de operações (IP/UA/plataforma) | Admin |",
"| 脱敏 | 日志敏感字段遮蔽 (password/token/secret → ***) | Service |": "| Mascaramento | Mascaramento de campos sensíveis nos logs (password/token/secret → ***) | Service |",
"### 6.2 客户端平台识别": "### 6.2 Identificação da plataforma do cliente",
"通过 `X-Client-Platform` header:": "Através do header `X-Client-Platform`:",
"| 值 | 来源 |": "| Valor | Origem |",
"## 7. API 版本路由机制": "## 7. Mecanismo de roteamento por versão da API",
"版本号不出现于 URL 路径。版本通过 `X-API-Version` header 传递，`VersionMiddleware` 读取并设置 `$request->apiVersion`。`versioned()` 辅助函数运行时将控制器类中的版本段替换为请求版本。": "O número da versão não aparece no caminho da URL. A versão é transmitida pelo header `X-API-Version`, e o `VersionMiddleware` a lê e define `$request->apiVersion`. A função auxiliar `versioned()` substitui em tempo de execução o segmento de versão na classe do controlador pela versão da requisição.",
"## 8. 定时任务调度": "## 8. Agendamento de tarefas",
"| 任务 | Cron | 功能 |": "| Tarefa | Cron | Função |",
"| TokenRefreshTask | `55 */1 * * *` | 刷新过期 OAuth Token |": "| TokenRefreshTask | `55 */1 * * *` | Atualiza Tokens OAuth expirados |",
"| DataSyncTask | `*/10 * * * *` | 同步 Campaigns→AdGroups→Creatives→Reports→清缓存 |": "| DataSyncTask | `*/10 * * * *` | Sincroniza Campaigns→AdGroups→Creatives→Reports→limpa cache |",
"| AlertCheckTask | `*/5 * * * *` | 评估告警规则，触发通知 |": "| AlertCheckTask | `*/5 * * * *` | Avalia regras de alerta e dispara notificações |",
"| BidCheckTask | `*/10 * * * *` | 评估出价规则，执行预算调整/启停 |": "| BidCheckTask | `*/10 * * * *` | Avalia regras de lance e executa ajustes de orçamento/início-pausa |",
"| RetrySyncTask | `*/3 * * * *` | 重试失败同步（最多 3 次，指数退避） |": "| RetrySyncTask | `*/3 * * * *` | Repete sincronizações com falha (máximo de 3 vezes, backoff exponencial) |",
"## 9. Erik Stack 包集成": "## 9. Integração dos pacotes Erik Stack",
"| 包 | 集成位置 | 用途 |": "| Pacote | Local de integração | Finalidade |",
"| `erikwang2013/snowflake-php` | 10 个 Model (SnowflakeTrait) + admin helpers.php | 主键生成 |": "| `erikwang2013/snowflake-php` | 10 Models (SnowflakeTrait) + admin helpers.php | Geração de chave primária |",
"| `erikwang2013/hashids` | ApiResponse + 2 个 Admin Controller | ID 编码 |": "| `erikwang2013/hashids` | ApiResponse + 2 Admin Controllers | Codificação de ID |",
"| `erikwang2013/jwt-webman` | JwtService (encode/decode/refresh) | 认证令牌 |": "| `erikwang2013/jwt-webman` | JwtService (encode/decode/refresh) | Token de autenticação |",
"| `erikwang2013/encryption` | EncryptionMiddleware | 传输加解密 |": "| `erikwang2013/encryption` | EncryptionMiddleware | Criptografia de transporte |",
"| `erikwang2013/encryptable` | PlatformAccount + AuthToken Model | DB 字段加密 |": "| `erikwang2013/encryptable` | Modelos PlatformAccount + AuthToken | Criptografia de campos do DB |",
"| `erikwang2013/webman-scout` | Campaign Model (Searchable trait) | ES 搜索 |": "| `erikwang2013/webman-scout` | Modelo Campaign (trait Searchable) | Busca ES |",
"| `erikwang2013/season` | PlatformController (getCountryFlagEmoji) | 国家旗帜 |": "| `erikwang2013/season` | PlatformController (getCountryFlagEmoji) | Bandeiras de países |",
"| `erikwang2013/poster-php` | AuthController (CaptchaService) | 滑块验证码 |": "| `erikwang2013/poster-php` | AuthController (CaptchaService) | Captcha deslizante |",
"| `hg/apidoc` | 注解 → 文档生成 (Web UI: :8788/apidoc) | API 文档 |": "| `hg/apidoc` | Anotações → geração de documentação (Web UI: :8788/apidoc) | Documentação da API |",
"## 10. 高并发架构": "## 10. Arquitetura de alta concorrência",
"### 10.1 数据库层": "### 10.1 Camada de banco de dados",
"| 优化 | 说明 |": "| Otimização | Descrição |",
"| 读写分离 | 主库 `shared`（写）+ 只读副本 `read_replica`（报表/分析查询） |": "| Separação leitura/escrita | Banco principal `shared` (escrita) + réplica somente leitura `read_replica` (consultas de relatórios/análises) |",
"| 持久连接 | `PDO::ATTR_PERSISTENT` + `mysqli max_persistent` 避免频繁 TCP 握手 |": "| Conexões persistentes | `PDO::ATTR_PERSISTENT` + `mysqli max_persistent` para evitar handshakes TCP frequentes |",
"| 连接预热 | worker 启动时执行 `SELECT 1`，连接池就绪后再接收请求 |": "| Pré-aquecimento de conexões | Executa `SELECT 1` na inicialização do worker; só recebe requisições após o pool de conexões estar pronto |",
"### 10.2 缓存层": "### 10.2 Camada de cache",
"### 10.3 消息队列": "### 10.3 Fila de mensagens",
"4 个通道: `sync` | `report` | `export` | `notification`": "4 canais: `sync` | `report` | `export` | `notification`",
"### 10.4 水平扩展": "### 10.4 Escala horizontal",
"- **keepalive**: 32 长连接复用": "- **keepalive**: reutilização de 32 conexões longas",
"- **failover**: `proxy_next_upstream` 自动故障转移，2 次重试": "- **failover**: `proxy_next_upstream` com failover automático, 2 tentativas",
"- **限流**: `limit_req_zone` 30r/s + burst 20 + `limit_conn` 20": "- **Rate limit**: `limit_req_zone` 30r/s + burst 20 + `limit_conn` 20",
"### 10.5 静态资源 CDN": "### 10.5 CDN de recursos estáticos",
"- `gzip_static on` — 预压缩 js/css 文件": "- `gzip_static on` — arquivos js/css pré-comprimidos",
"- 生产环境接入 CDN (CloudFront/Aliyun CDN)": "- Em produção, conecta-se a uma CDN (CloudFront/Aliyun CDN)",
"## 11. 部署与 CI/CD": "## 11. Implantação e CI/CD",
"### Docker 服务": "### Serviços Docker",
"| 服务 | 端口 | 镜像 |": "| Serviço | Porta | Imagem |",
},
"docs/features.md": {
"# 功能设计文档": "# Documento de design de funcionalidades",
"> 全部 API 接口定义（请求/响应/参数）见 [api.md](api.md)。": "> Todas as definições das interfaces de API (requisição/resposta/parâmetros) estão em [api.md](api.pt.md).",
"## 模块总览": "## Visão geral dos módulos",
"| # | 模块 | 控制器/服务 | API 路由数 | Vue 页面 |": "| # | Módulo | Controlador/Serviço | Rotas de API | Páginas Vue |",
"| 1 | 认证授权 | AuthController | 3 | LoginPage |": "| 1 | Autenticação e autorização | AuthController | 3 | LoginPage |",
"| 2 | 平台管理 | PlatformController | 3 | — |": "| 2 | Gerenciamento de plataformas | PlatformController | 3 | — |",
"| 3 | 账户管理 | AccountController | 5 | AccountList, AccountBind |": "| 3 | Gerenciamento de contas | AccountController | 5 | AccountList, AccountBind |",
"| 4 | 广告计划 | CampaignController | 6 | CampaignList |": "| 4 | Planos de anúncios | CampaignController | 6 | CampaignList |",
"| 5 | 广告组 | AdGroupController | 5 | AdGroupList |": "| 5 | Grupos de anúncios | AdGroupController | 5 | AdGroupList |",
"| 6 | 广告创意 | CreativeController | 2 | CreativeList |": "| 6 | Criativos | CreativeController | 2 | CreativeList |",
"| 7 | 数据报表 | DashboardController, ReportController, ExportController | 8 | DashboardPage, ReportView, ReportExport, CampaignCalendar, AttributionReport |": "| 7 | Relatórios de dados | DashboardController, ReportController, ExportController | 8 | DashboardPage, ReportView, ReportExport, CampaignCalendar, AttributionReport |",
"| 8 | 告警监控 | AlertController | 7 | AlertRuleList, AlertLogList |": "| 8 | Monitoramento de alertas | AlertController | 7 | AlertRuleList, AlertLogList |",
"| 9 | 通知中心 | NotificationController | 4 | NotificationList |": "| 9 | Central de notificações | NotificationController | 4 | NotificationList |",
"| 10 | 自动出价 | BidRuleController | 5 | BidRuleList |": "| 10 | Lance automático | BidRuleController | 5 | BidRuleList |",
"| 11 | 定向模板 | TargetingTemplateController | 5 | — |": "| 11 | Modelos de segmentação | TargetingTemplateController | 5 | — |",
"| 12 | 系统管理 | AdminUserController, AuditLogController | 5 | UserManage, AuditLog |": "| 12 | Administração do sistema | AdminUserController, AuditLogController | 5 | UserManage, AuditLog |",
"| 13 | 数据同步 | DataSyncTask, TokenRefreshTask, RetrySyncTask | — | — |": "| 13 | Sincronização de dados | DataSyncTask, TokenRefreshTask, RetrySyncTask | — | — |",
"| 14 | 素材库 | AssetController | 4 | AssetGallery |": "| 14 | Biblioteca de materiais | AssetController | 4 | AssetGallery |",
"| 15 | 预算预警 | BudgetAlertService + BudgetCheckTask | 1 | — |": "| 15 | Alerta de orçamento | BudgetAlertService + BudgetCheckTask | 1 | — |",
"| 16 | 投放日历 | CalendarService | 1 | CampaignCalendar |": "| 16 | Calendário de veiculação | CalendarService | 1 | CampaignCalendar |",
"| 17 | 跨平台归因 | AttributionEngine | 2 | AttributionReport |": "| 17 | Atribuição entre plataformas | AttributionEngine | 2 | AttributionReport |",
"| 18 | 健康检查 | HealthController | 2 | — |": "| 18 | Verificação de saúde | HealthController | 2 | — |",
"| 19 | 验证码 | CaptchaController | 2 | — |": "| 19 | Captcha | CaptchaController | 2 | — |",
"| 20 | API 文档 | DocController | 1 | — |": "| 20 | Documentação da API | DocController | 1 | — |",
"**合计**: 20 模块, 65+ 路由, 18 Vue 页面": "**Total**: 20 módulos, 65+ rotas, 18 páginas Vue",
"## 模块 1: 认证授权": "## Módulo 1: Autenticação e autorização",
"- 验证码检查（可选）": "- Verificação de captcha (opcional)",
"- 查询 `admin_users` 表": "- Consulta a tabela `admin_users`",
"- bcrypt `password_verify()` 验证": "- Verificação com bcrypt `password_verify()`",
"- JWT Token 生成 (24h TTL)": "- Geração de JWT Token (TTL de 24h)",
"- 旧 Token 自动加入黑名单": "- Token antigo é adicionado automaticamente à lista negra",
"- 从 Token 提取 `uid` 查询用户信息": "- Extrai `uid` do Token para consultar as informações do usuário",
"接口: 登录 / Token 刷新 / 当前用户 → [api.md 模块 2](api.md#模块-2-认证)": "Interfaces: login / refresh de Token / usuário atual → [módulo 2 do api.md](api.pt.md#模块-2-认证)",
"## 模块 2-3: 平台与账户管理": "## Módulos 2-3: Gerenciamento de plataformas e contas",
"- 平台列表缓存 1 小时 (Redis)，集成 Season 国旗 emoji": "- Lista de plataformas com cache de 1 hora (Redis), integração com emoji de bandeira do Season",
"- OAuth 流程: 生成随机 state → 构建授权 URL → 回调处理 → 存储 Token": "- Fluxo OAuth: gerar state aleatório → construir URL de autorização → processar callback → armazenar Token",
"- 账户列表/详情缓存 5 分钟": "- Lista/detalhes de contas com cache de 5 minutos",
"接口: 平台列表 / OAuth / 账户 CRUD + 同步 → [api.md 模块 3](api.md#模块-3-平台--账户)": "Interfaces: lista de plataformas / OAuth / CRUD de contas + sincronização → [módulo 3 do api.md](api.pt.md#模块-3-平台--账户)",
"## 模块 4-6: 广告投放层级": "## Módulos 4-6: Hierarquia de veiculação de anúncios",
"### 数据结构": "### Estrutura de dados",
"- 创建计划通过平台适配器 + 写入本地": "- Criação de planos via adaptador da plataforma + gravação local",
"- 支持按平台/状态/关键词筛选，列表含今日汇总": "- Suporta filtros por plataforma/status/palavra-chave, e a lista inclui o resumo de hoje",
"- 广告组创建支持 `targeting_template_id` 加载定向模板": "- A criação de grupos de anúncios suporta `targeting_template_id` para carregar modelos de segmentação",
"接口: 计划 / 广告组 / 创意 → [api.md 模块 4-6](api.md#模块-4-广告计划)": "Interfaces: planos / grupos de anúncios / criativos → [módulos 4-6 do api.md](api.pt.md#模块-4-广告计划)",
"## 模块 7: 数据报表": "## Módulo 7: Relatórios de dados",
"- 仪表盘汇总缓存 5 分钟: 8 个 KPI 指标卡片 + 日趋势折线图 + 平台柱状图": "- Resumo do dashboard com cache de 5 minutos: 8 cartões de indicadores KPI + gráfico de linhas de tendência diária + gráfico de barras por plataforma",
"- 自定义报表维度: date, platform, campaign": "- Dimensões de relatórios personalizados: date, platform, campaign",
"- 指标: cost, impressions, clicks, conversions, ctr, cvr, cpc, cpm, roi": "- Métricas: cost, impressions, clicks, conversions, ctr, cvr, cpc, cpm, roi",
"- 导出格式: CSV (UTF-8 BOM), Excel (HTML .xls), PDF (HTML 打印)": "- Formatos de exportação: CSV (UTF-8 BOM), Excel (HTML .xls), PDF (impressão HTML)",
"接口: 汇总 / 自定义 / 导出 → [api.md 模块 7](api.md#模块-7-报表)": "Interfaces: resumo / personalizado / exportação → [módulo 7 do api.md](api.pt.md#模块-7-报表)",
"## 模块 8: 告警监控": "## Módulo 8: Monitoramento de alertas",
"### AlertEngine 求值流程": "### Fluxo de avaliação do AlertEngine",
"### 通知渠道": "### Canais de notificação",
"| 渠道 | 状态 | 实现 |": "| Canal | Status | Implementação |",
"| web | ✅ | 写入 erik_notifications |": "| web | ✅ | Grava em erik_notifications |",
"| email | 占位 | echo 存根 |": "| email | Placeholder | Stub echo |",
"| sms | 占位 | echo 存根 |": "| sms | Placeholder | Stub echo |",
"| Redis pub/sub | ✅ | `alert:new` 频道 JSON 推送 |": "| Redis pub/sub | ✅ | Push JSON no canal `alert:new` |",
"接口: 规则 CRUD / 告警记录 / 确认 / 未读数 → [api.md 模块 8](api.md#模块-8-告警)": "Interfaces: CRUD de regras / registros de alertas / confirmação / não lidos → [módulo 8 do api.md](api.pt.md#模块-8-告警)",
"## 模块 9: 通知中心": "## Módulo 9: Central de notificações",
"- 前端 Pinia store 30s 轮询": "- Polling de 30s com Pinia store no frontend",
"- 侧边栏铃铛图标 + 未读数字徽标": "- Ícone de sino na barra lateral + badge com número de não lidos",
"接口: 列表 / 未读数 / 标记已读 / 全部已读 → [api.md 模块 9](api.md#模块-9-通知)": "Interfaces: lista / não lidos / marcar como lido / marcar todos como lidos → [módulo 9 do api.md](api.pt.md#模块-9-通知)",
"## 模块 10: 自动出价引擎": "## Módulo 10: Engine de lance automático",
"### BidEngine 求值流程": "### Fluxo de avaliação do BidEngine",
"### 规则字段": "### Campos da regra",
"| 字段 | 类型 | 说明 |": "| Campo | Tipo | Descrição |",
"| metric | cost/impressions/clicks/conversions/ctr/cvr/roi | 监控指标 |": "| metric | cost/impressions/clicks/conversions/ctr/cvr/roi | Métrica monitorada |",
"| condition | gt/gte/lt/lte | 触发条件 |": "| condition | gt/gte/lt/lte | Condição de disparo |",
"| threshold | DECIMAL(12,2) | 阈值 |": "| threshold | DECIMAL(12,2) | Limite |",
"| scope | tenant/platform/campaign | 作用范围 |": "| scope | tenant/platform/campaign | Escopo de aplicação |",
"| action_type | adjust_budget/toggle_pause/toggle_enable | 动作 |": "| action_type | adjust_budget/toggle_pause/toggle_enable | Ação |",
"| adjust_step | INT (分) | 预算调整步长 (正=加, 负=减) |": "| adjust_step | INT (centavos) | Passo do ajuste de orçamento (positivo=adicionar, negativo=reduzir) |",
"| budget_min, budget_max | BIGINT | 预算边界 |": "| budget_min, budget_max | BIGINT | Limites do orçamento |",
"| cooldown_minutes | INT | 冷却期 |": "| cooldown_minutes | INT | Período de resfriamento |",
"接口: 规则 CRUD / 出价历史 → [api.md 模块 10](api.md#模块-10-自动出价)": "Interfaces: CRUD de regras / histórico de lances → [módulo 10 do api.md](api.pt.md#模块-10-自动出价)",
"## 模块 11: 受众定向模板": "## Módulo 11: Modelos de segmentação de público",
"### 集成到广告组": "### Integração com grupos de anúncios",
"### 通用 JSON Schema": "### JSON Schema genérico",
"接口: 模板 CRUD → [api.md 模块 11](api.md#模块-11-定向模板)": "Interfaces: CRUD de modelos → [módulo 11 do api.md](api.pt.md#模块-11-定向模板)",
"## 模块 12: 系统管理 (Admin)": "## Módulo 12: Administração do sistema (Admin)",
"- 用户列表 ID hashids 编码": "- IDs da lista de usuários codificados com hashids",
"- 创建用户 bcrypt 哈希密码": "- Senhas de novos usuários com hash bcrypt",
"- 禁用用户为软禁用 (status=0)": "- Usuários desabilitados usam desabilitação suave (status=0)",
"审计日志字段: `{ user_id, username, action, resource, resource_id, detail, ip, user_agent, client_platform }`": "Campos do log de auditoria: `{ user_id, username, action, resource, resource_id, detail, ip, user_agent, client_platform }`",
"接口: 用户管理 / 审计日志 / 角色 → [api.md Admin 端点](api.md#admin-端点端口-8789)": "Interfaces: gerenciamento de usuários / logs de auditoria / papéis → [endpoints Admin do api.md](api.pt.md#admin-端点端口-8789)",
"## 模块 13: 数据同步": "## Módulo 13: Sincronização de dados",
"### DataSyncTask 流程 (每 10 分钟)": "### Fluxo do DataSyncTask (a cada 10 minutos)",
"## 响应格式": "## Formato de resposta",
"### 成功": "### Sucesso",
"### 分页": "### Paginação",
"### 错误": "### Erro",
"## 模块 14: 广告素材库": "## Módulo 14: Biblioteca de materiais de anúncios",
"- 支持类型: image/jpeg, image/png, image/gif, image/webp, video/mp4": "- Tipos suportados: image/jpeg, image/png, image/gif, image/webp, video/mp4",
"- 文件存储: `public/uploads/assets/`": "- Armazenamento de arquivos: `public/uploads/assets/`",
"- 前端: 网格画廊 + 拖拽上传 + 图片预览 + 视频播放 + 复制 URL": "- Frontend: galeria em grade + upload por arrastar e soltar + prévia de imagens + reprodução de vídeos + copiar URL",
"接口: 上传 / 列表 / 详情 / 删除 → [api.md 模块 12](api.md#模块-12-素材库)": "Interfaces: upload / lista / detalhes / exclusão → [módulo 12 do api.md](api.pt.md#模块-12-素材库)",
"## 模块 15: 预算预警": "## Módulo 15: Alerta de orçamento",
"- 三段告警: yellow (≥50%), orange (≥80%), red (≥100%)": "- Alertas em três níveis: yellow (≥50%), orange (≥80%), red (≥100%)",
"- BudgetCheckTask 每 15 分钟执行": "- BudgetCheckTask executa a cada 15 minutos",
"- 去重: 同一计划同一级别一天只通知一次": "- Deduplicação: o mesmo plano no mesmo nível é notificado apenas uma vez por dia",
"- 写入 `erik_notifications` 表": "- Grava na tabela `erik_notifications`",
"接口: 预算预警 → [api.md 模块 7](api.md#模块-7-报表)": "Interface: alerta de orçamento → [módulo 7 do api.md](api.pt.md#模块-7-报表)",
"## 模块 16: 投放日历": "## Módulo 16: Calendário de veiculação",
"- 按日期聚合 campaign 排期": "- Agrega os agendamentos de campaigns por data",
"- 前端 Gantt 图: x 轴日期, y 轴计划, 按平台颜色区分": "- Gráfico Gantt no frontend: eixo x datas, eixo y planos, cores distintas por plataforma",
"- 支持月/周视图切换": "- Suporta alternância entre visões mensal/semanal",
"接口: 投放日历 → [api.md 模块 7](api.md#模块-7-报表)": "Interface: calendário de veiculação → [módulo 7 do api.md](api.pt.md#模块-7-报表)",
"## 模块 17: 跨平台归因": "## Módulo 17: Atribuição entre plataformas",
"### 归因模型": "### Modelos de atribuição",
"| 模型 | 算法 |": "| Modelo | Algoritmo |",
"| first_touch | 首个触点 100% |": "| first_touch | Primeiro contato 100% |",
"| last_touch | 末个触点 100% |": "| last_touch | Último contato 100% |",
"| linear | 所有触点均分 (1/N) |": "| linear | Todos os contatos divididos igualmente (1/N) |",
"| time_decay | e^(-λ×Δt), 7天半衰期 |": "| time_decay | e^(-λ×Δt), meia-vida de 7 dias |",
"| position_based | 首40% + 末40% + 中间20% |": "| position_based | Primeiros 40% + últimos 40% + meio 20% |",
"- 回溯窗口: 30 天": "- Janela de retrospectiva: 30 dias",
"- 触点来源: `erik_report_metrics` (点击 > 0)": "- Origem dos contatos: `erik_report_metrics` (cliques > 0)",
"- 结果写入 `erik_attribution_results`": "- Resultados gravados em `erik_attribution_results`",
"- 前端: AttributionReport.vue 模型切换 + 统计卡片 + ECharts 柱状图 + 明细表格": "- Frontend: AttributionReport.vue com alternância de modelos + cartões de estatísticas + gráfico de barras ECharts + tabela de detalhes",
"### 数据表": "### Tabelas de dados",
"| 表 | 字段 |": "| Tabela | Campos |",
"接口: 归因分析 / 模型列表 → [api.md 模块 7](api.md#模块-7-报表)": "Interfaces: análise de atribuição / lista de modelos → [módulo 7 do api.md](api.pt.md#模块-7-报表)",
"### 健康检查": "### Verificação de saúde",
},
}
