# -*- coding: utf-8 -*-
# 葡萄牙语翻译词典（skills，中文源文件）
TRANS = {
"docs/skills/attribution-setup.md": {
"# 跨平台归因": "# Atribuição entre plataformas",
"设置和使用归因引擎分析转化来源。": "Como configurar e usar o mecanismo de atribuição para analisar a origem das conversões.",
"## 数据准备": "## Preparação de dados",
"1. 创建转化事件表：": "1. Criar a tabela de eventos de conversão:",
"2. 触点数据来自 `erik_report_metrics`（clicks > 0 的记录作为触点）。": "2. Os dados de pontos de contato vêm de `erik_report_metrics` (registros com clicks > 0 são considerados pontos de contato).",
"## 归因模型": "## Modelos de atribuição",
"| 模型 | 算法 | 适用场景 |": "| Modelo | Algoritmo | Cenário de uso |",
"| `first_touch` | 首次触点 100% | 品牌认知类 |": "| `first_touch` | Primeiro contato 100% | Reconhecimento de marca |",
"| `last_touch` | 末次触点 100% | 直接转化类 |": "| `last_touch` | Último contato 100% | Conversão direta |",
"| `linear` | 所有触点均分 | 持续投放类 |": "| `linear` | Todos os contatos igualmente divididos | Veiculação contínua |",
"| `time_decay` | e^(-λ×Δt), 7天半衰期 | 时效敏感类 |": "| `time_decay` | e^(-λ×Δt), meia-vida de 7 dias | Sensível ao tempo |",
"| `position_based` | 首40%+末40%+中间20% | 综合评估 |": "| `position_based` | Primeiros 40% + últimos 40% + meio 20% | Avaliação abrangente |",
"## API 调用": "## Chamadas de API",
"响应：": "Resposta:",
"## AttributionEngine 直接调用": "## Chamada direta do AttributionEngine",
"## 配置参数": "## Parâmetros de configuração",
"| 参数 | 默认值 | 说明 |": "| Parâmetro | Padrão | Descrição |",
"| `lookbackDays` | 30 | 回溯窗口 |": "| `lookbackDays` | 30 | Janela de retrospectiva |",
"| `halfLife` | 7.0 | 时间衰减半衰期（天） |": "| `halfLife` | 7.0 | Meia-vida do decaimento temporal (dias) |",
},
"docs/skills/cache-strategy.md": {
"# 缓存策略": "# Estratégia de cache",
"实现三级缓存（L1 内存 → L2 APCu → L3 Redis）。": "Implementar cache de três níveis (L1 memória → L2 APCu → L3 Redis).",
"## CacheService 使用": "## Uso do CacheService",
"## 三级缓存原理": "## Princípio do cache de três níveis",
"## 缓存 TTL 建议": "## Recomendações de TTL de cache",
"| 端点类型 | TTL | 理由 |": "| Tipo de endpoint | TTL | Motivo |",
"| 平台列表 | 3600s (1h) | 平台元数据极少变化 |": "| Lista de plataformas | 3600s (1h) | Os metadados das plataformas mudam muito raramente |",
"| 账户列表/详情 | 300s (5min) | 可能频繁同步 |": "| Lista/detalhes de contas | 300s (5min) | Podem ser sincronizadas com frequência |",
"| 仪表盘汇总 | 300s (5min) | 每日数据 |": "| Resumo do dashboard | 300s (5min) | Dados diários |",
"| 告警规则 | 120s (2min) | 允许一定延迟 |": "| Regras de alerta | 120s (2min) | Algum atraso é aceitável |",
"| 告警未读数 | 30s | 前端 30s 轮询 |": "| Alertas não lidos | 30s | Polling de 30s do frontend |",
"## Dashboard 缓存刷新": "## Atualização do cache do Dashboard",
"DataSyncTask 同步完成新数据后自动调用：": "O DataSyncTask chama automaticamente após sincronizar novos dados:",
"## 注意事项": "## Observações",
"1. 写操作后必须刷新相关缓存（如 destroy/sync 后 `CacheService::forget()`）": "1. Após operações de escrita, o cache relacionado deve ser atualizado (ex.: `CacheService::forget()` depois de destroy/sync)",
"2. APCu 需要安装扩展：`apt install php-apcu`": "2. O APCu requer a extensão: `apt install php-apcu`",
"3. 缓存 Key 命名规范：`cache:{domain}:{tenantId}:{params}`": "3. Convenção de nomes de chave de cache: `cache:{domain}:{tenantId}:{params}`",
},
"docs/skills/high-concurrency.md": {
"# 高并发优化": "# Otimização de alta concorrência",
"实施 8 项高并发优化策略。": "Implementar 8 estratégias de otimização de alta concorrência.",
"## 1. 数据库读写分离": "## 1. Separação de leitura/escrita do banco de dados",
"`service/config/database.php`：": "`service/config/database.php`:",
"环境变量：": "Variáveis de ambiente:",
"## 2. 持久连接": "## 2. Conexões persistentes",
"## 3. Redis 连接池": "## 3. Pool de conexões Redis",
"## 4. 三级缓存": "## 4. Cache de três níveis",
"参见 [缓存策略技能](cache-strategy.md)。": "Consulte a [habilidade de estratégia de cache](cache-strategy.pt.md).",
"## 5. 消息队列异步": "## 5. Fila de mensagens assíncrona",
"4 个通道: `sync`, `report`, `export`, `notification`": "4 canais: `sync`, `report`, `export`, `notification`",
"## 6. Nginx 多层限流": "## 6. Limitação de taxa em várias camadas no Nginx",
"## 7. 水平扩展": "## 7. Escala horizontal",
"## 8. CDN 静态资源": "## 8. Recursos estáticos em CDN",
},
"docs/skills/security-middleware.md": {
"# 安全中间件": "# Middlewares de segurança",
"向请求管道添加新的安全中间件。": "Adicionar novos middlewares de segurança ao pipeline de requisições.",
"## 中间件接口": "## Interface do middleware",
"## 注册": "## Registro",
"编辑 `service/config/middleware.php`，在 `global` 数组中按顺序添加类名：": "Editar `service/config/middleware.php` e adicionar o nome da classe em ordem no array `global`:",
"## 现有中间件链": "## Cadeia de middlewares existente",
"| 阶段 | 中间件 | 职责 |": "| Fase | Middleware | Responsabilidade |",
"| 边界 | CorsMiddleware | CORS 白名单 |": "| Limite | CorsMiddleware | Lista de permissões CORS |",
"| 边界 | SecurityHeadersMiddleware | X-Frame/CSP/HSTS |": "| Limite | SecurityHeadersMiddleware | X-Frame/CSP/HSTS |",
"| 检测 | AttackGuardMiddleware | XSS/路径遍历/Header注入 |": "| Detecção | AttackGuardMiddleware | XSS/Path traversal/Injeção de Header |",
"| 识别 | ClientPlatformMiddleware | 来源端识别 |": "| Identificação | ClientPlatformMiddleware | Identificação do cliente de origem |",
"| 路由 | VersionMiddleware | API 版本路由 |": "| Rota | VersionMiddleware | Roteamento por versão da API |",
"| 控制 | RateLimitMiddleware | 滑动窗口限流 |": "| Controle | RateLimitMiddleware | Limitação por janela deslizante |",
"| 控制 | LoginThrottleMiddleware | 登录节流 |": "| Controle | LoginThrottleMiddleware | Throttle de login |",
"| 检测 | SqlGuardMiddleware | SQL 注入检测 |": "| Detecção | SqlGuardMiddleware | Detecção de injeção de SQL |",
"| 清洗 | ValidationMiddleware | strip_tags + trim |": "| Limpeza | ValidationMiddleware | strip_tags + trim |",
"| 监控 | ResponseTimeMiddleware | X-Response-Time |": "| Monitoramento | ResponseTimeMiddleware | X-Response-Time |",
"| 加密 | EncryptionMiddleware | X-Encrypted 加解密 |": "| Criptografia | EncryptionMiddleware | Criptografia/descriptografia X-Encrypted |",
"## 添加 Admin 端中间件": "## Adicionar middlewares no Admin",
"Admin 中间件位于 `admin/app/middleware/`，注册在 `admin/config/middleware.php`。": "Os middlewares do Admin ficam em `admin/app/middleware/` e são registrados em `admin/config/middleware.php`.",
},
"docs/skills/version-split.md": {
"# 版本拆分": "# Divisão de versões",
"管理 Lite/Standard/Full 三版本功能差异。": "Gerenciar as diferenças de funcionalidades entre as três versões Lite/Standard/Full.",
"## 三层架构": "## Arquitetura de três camadas",
"## 拆分步骤": "## Etapas da divisão",
"### 1. 创建功能分支": "### 1. Criar o branch de funcionalidade",
"### 2. 删除非目标版本的功能": "### 2. Remover funcionalidades que não pertencem à versão alvo",
"**从 Full 拆分到 Standard（需要删除的）**：": "**Da Full para a Standard (o que remover):**",
"- 控制器: BidRuleController, TargetingTemplateController, AssetController": "- Controladores: BidRuleController, TargetingTemplateController, AssetController",
"- 服务: BidEngine, BudgetAlertService, AttributionEngine, CalendarService": "- Serviços: BidEngine, BudgetAlertService, AttributionEngine, CalendarService",
"- 模型: BidRule, BidLog, TargetingTemplate": "- Modelos: BidRule, BidLog, TargetingTemplate",
"- 中间件: ReplayGuard, SessionLimit, OriginGuard, CsrfMiddleware": "- Middlewares: ReplayGuard, SessionLimit, OriginGuard, CsrfMiddleware",
"- 任务: BidCheckTask, BudgetCheckTask": "- Tarefas: BidCheckTask, BudgetCheckTask",
"- 路由: bid-rules, targeting-templates, assets, attribution, calendar, budget-alerts": "- Rotas: bid-rules, targeting-templates, assets, attribution, calendar, budget-alerts",
"**从 Standard 拆分到 Lite（需要删除的）**：": "**Da Standard para a Lite (o que remover):**",
"- 控制器: AdGroupController, CreativeController, AlertController, NotificationController": "- Controladores: AdGroupController, CreativeController, AlertController, NotificationController",
"- 服务: AlertEngine, NotificationService": "- Serviços: AlertEngine, NotificationService",
"- 模型: AlertRule, AlertLog": "- Modelos: AlertRule, AlertLog",
"- 中间件: AttackGuard(×2), ClientPlatform(×2), LoginThrottle(×2), ResponseTime": "- Middlewares: AttackGuard(×2), ClientPlatform(×2), LoginThrottle(×2), ResponseTime",
"- 任务: AlertCheckTask": "- Tarefas: AlertCheckTask",
"- DataSyncTask 中移除 adgroup/creative 同步": "- Remover a sincronização de adgroup/creative do DataSyncTask",
"### 3. 更新配置文件": "### 3. Atualizar os arquivos de configuração",
"每次拆分后更新：": "Atualizar após cada divisão:",
"- `route.php`: 删除对应路由和 import": "- `route.php`: remover as rotas e imports correspondentes",
"- `middleware.php` (service+admin): 简化中间件链": "- `middleware.php` (service+admin): simplificar a cadeia de middlewares",
"- `cron.php`: 精简定时任务": "- `cron.php`: reduzir os jobs agendados",
"- `router/index.ts` + `SideNav.vue` (Vue): 移除页面路由和菜单": "- `router/index.ts` + `SideNav.vue` (Vue): remover rotas e menus de páginas",
"- `router.dart` + `menu_config.dart` (Flutter): 同步更新": "- `router.dart` + `menu_config.dart` (Flutter): atualizar de forma sincronizada",
"### 4. 验证": "### 4. Validação",
},
}
