# -*- coding: utf-8 -*-
# 葡萄牙语翻译词典（api.md）
TRANS = {
"docs/api.md": {
"# API 接口文档": "# Documentação da API",
"> **hg/apidoc 在线文档**: 启动服务后访问 `http://127.0.0.1:8788/apidoc`（Service + Admin 双应用切换）  ": "> **Documentação online hg/apidoc**: após iniciar o serviço, acesse `http://127.0.0.1:8788/apidoc` (alternância entre os dois aplicativos Service + Admin)  ",
"> 配置文件: `service/config/plugin/hg/apidoc/app.php`": "> Arquivo de configuração: `service/config/plugin/hg/apidoc/app.php`",
"## 通用规范": "## Especificações gerais",
"### 必需 Headers": "### Headers obrigatórios",
"| Header | 值 | 说明 |": "| Header | Valor | Descrição |",
"| `X-API-Version` | `v1` | API 版本号（必填，不出现于 URL 路径） |": "| `X-API-Version` | `v1` | Número da versão da API (obrigatório, não aparece no caminho da URL) |",
"| `X-Client-Platform` | `web` / `ios` / `android` / `macos` / `windows` / `linux` / `harmonyos` | 操作来源端（必填） |": "| `X-Client-Platform` | `web` / `ios` / `android` / `macos` / `windows` / `linux` / `harmonyos` | Plataforma de origem da operação (obrigatório) |",
"| `Authorization` | `Bearer <token>` | JWT 认证令牌（除登录/平台列表/健康检查外必填） |": "| `Authorization` | `Bearer <token>` | Token de autenticação JWT (obrigatório exceto login/lista de plataformas/verificação de saúde) |",
"### 防重放 Header（非浏览器端）": "### Headers anti-replay (fora do navegador)",
"| Header | 说明 |": "| Header | Descrição |",
"| `X-Nonce` | 随机字符串（每次请求唯一） |": "| `X-Nonce` | String aleatória (única por requisição) |",
"| `X-Timestamp` | Unix 秒级时间戳（±5 分钟窗口） |": "| `X-Timestamp` | Timestamp Unix em segundos (janela de ±5 minutos) |",
"### 可选 Headers": "### Headers opcionais",
"| `X-Tenant-Id` | 租户 ID（多租户模式） |": "| `X-Tenant-Id` | ID do tenant (modo multitenant) |",
"| `X-Encrypted` | `1` = 请求体需解密，响应体需加密 |": "| `X-Encrypted` | `1` = corpo da requisição precisa ser descriptografado e o da resposta criptografado |",
"| 值 | 说明 |": "| Valor | Descrição |",
"| `application/json` | JSON 请求体（推荐） |": "| `application/json` | Corpo de requisição JSON (recomendado) |",
"| `application/x-www-form-urlencoded` | 表单请求 |": "| `application/x-www-form-urlencoded` | Requisição de formulário |",
"| `multipart/form-data` | 文件上传 |": "| `multipart/form-data` | Upload de arquivos |",
"### 响应格式": "### Formato de resposta",
"**成功**:": "**Sucesso**:",
"**分页**:": "**Paginação**:",
"**错误**:": "**Erro**:",
"**健康检查**:": "**Verificação de saúde**:",
"### HTTP 状态码": "### Códigos de status HTTP",
"| 状态码 | 含义 |": "| Código | Significado |",
"| 200 | 成功 |": "| 200 | Sucesso |",
"| 204 | OPTIONS 预检成功 |": "| 204 | Preflight OPTIONS bem-sucedido |",
"| 400 | 请求参数错误、不支持的 API 版本 |": "| 400 | Parâmetros de requisição inválidos, versão de API não suportada |",
"| 401 | 未认证、Token 过期、Token IP/UA 不匹配 |": "| 401 | Não autenticado, Token expirado, IP/UA do Token não correspondente |",
"| 403 | 禁止访问（XSS/路径遍历/CSRF/SQL注入/Origin 不匹配） |": "| 403 | Acesso proibido (XSS/path traversal/CSRF/injeção de SQL/Origin não correspondente) |",
"| 404 | 资源不存在 |": "| 404 | Recurso não encontrado |",
"| 429 | 请求过多（限流/登录节流/并发会话限制） |": "| 429 | Muitas requisições (rate limit/throttle de login/limite de sessões concorrentes) |",
"| 500 | 服务器错误 |": "| 500 | Erro do servidor |",
"| 503 | 服务降级（DB 或 Redis 不可用） |": "| 503 | Serviço degradado (DB ou Redis indisponível) |",
"### 分页参数": "### Parâmetros de paginação",
"| 参数 | 默认值 | 最大值 | 说明 |": "| Parâmetro | Padrão | Máximo | Descrição |",
"| `page` | 1 | — | 页码 |": "| `page` | 1 | — | Número da página |",
"| `per_page` | 20 | 100 | 每页条数（超过自动截断） |": "| `per_page` | 20 | 100 | Itens por página (truncado automaticamente se exceder) |",
"| `sort` | `id` | — | 排序字段（需在白名单内） |": "| `sort` | `id` | — | Campo de ordenação (deve estar na lista de permissões) |",
"### 缓存策略": "### Estratégia de cache",
"| 端点 | TTL | 层 |": "| Endpoint | TTL | Camada |",
"| `/api/platforms` | 1 小时 | L1 内存 → L2 APCu → L3 Redis |": "| `/api/platforms` | 1 hora | L1 memória → L2 APCu → L3 Redis |",
"| `/api/accounts` + `/api/accounts/:id` | 5 分钟 | 同上 |": "| `/api/accounts` + `/api/accounts/:id` | 5 minutos | O mesmo acima |",
"| `/api/reports/summary` | 5 分钟 | 同上 |": "| `/api/reports/summary` | 5 minutos | O mesmo acima |",
"| `/api/alerts/rules` | 2 分钟 | 同上 |": "| `/api/alerts/rules` | 2 minutos | O mesmo acima |",
"| `/api/alerts/unread-count` | 30 秒 | 同上 |": "| `/api/alerts/unread-count` | 30 segundos | O mesmo acima |",
"## 模块 1: 系统": "## Módulo 1: Sistema",
"### GET /health — 健康检查": "### GET /health — verificação de saúde",
"**响应**:": "**Resposta**:",
"- `status`: `healthy` (200) 或 `degraded` (503)": "- `status`: `healthy` (200) ou `degraded` (503)",
"- 无认证要求，不走版本路由": "- Sem requisito de autenticação, não passa pelo roteamento de versão",
"### GET /ping — 探活": "### GET /ping — verificação de atividade",
"**响应**: `{ \"pong\": true }`": "**Resposta**: `{ \"pong\": true }`",
"### GET /docs — API 文档": "### GET /docs — documentação da API",
"返回 HTML 格式的 API 文档页面（免认证）。": "Retorna a página de documentação da API em HTML (sem autenticação).",
"### GET /api/captcha/generate — 生成验证码": "### GET /api/captcha/generate — gerar captcha",
"免认证。": "Sem autenticação.",
"- token 有效期 5 分钟": "- Token válido por 5 minutos",
"- 偏移容差 5px": "- Tolerância de deslocamento de 5px",
"### POST /api/captcha/verify — 验证验证码": "### POST /api/captcha/verify — verificar captcha",
"**请求**:": "**Requisição**:",
"**响应**: `{ \"code\": 0, \"message\": \"验证通过\" }`": "**Resposta**: `{ \"code\": 0, \"message\": \"Verificação aprovada\" }`",
"## 模块 2: 认证": "## Módulo 2: Autenticação",
"### POST /api/auth/login — 登录": "### POST /api/auth/login — login",
"- JWT Token 有效期 24 小时": "- JWT Token válido por 24 horas",
"- Token 内嵌 IP + User-Agent hash": "- Token incorpora hash de IP + User-Agent",
"- 5 次失败 → Redis 锁定 15 分钟": "- 5 falhas → bloqueio no Redis por 15 minutos",
"### GET /api/auth/me — 当前用户": "### GET /api/auth/me — usuário atual",
"**请求头**: `Authorization: Bearer <token>`": "**Cabeçalho da requisição**: `Authorization: Bearer <token>`",
"### POST /api/auth/refresh — 刷新 Token": "### POST /api/auth/refresh — atualizar Token",
"**请求头**: `Authorization: Bearer <old_token>`": "**Cabeçalho da requisição**: `Authorization: Bearer <old_token>`",
"- 旧 Token 自动加入黑名单": "- Token antigo é adicionado automaticamente à lista negra",
"- 每个用户最大 3 个活跃 Token": "- Máximo de 3 Tokens ativos por usuário",
"## 模块 3: 平台 & 账户": "## Módulo 3: Plataformas & contas",
"### GET /api/platforms — 平台列表": "### GET /api/platforms — lista de plataformas",
"免认证。缓存 1 小时。": "Sem autenticação. Cache de 1 hora.",
"### GET /api/platforms/:code/oauth-url — OAuth 授权 URL": "### GET /api/platforms/:code/oauth-url — URL de autorização OAuth",
"**参数**: `?redirect_uri=https://your-domain.com/callback`": "**Parâmetro**: `?redirect_uri=https://your-domain.com/callback`",
"**响应**: `{ \"code\": 0, \"data\": { \"auth_url\": \"https://...\", \"state\": \"random-state\" } }`": "**Resposta**: `{ \"code\": 0, \"data\": { \"auth_url\": \"https://...\", \"state\": \"random-state\" } }`",
"- `redirect_uri` 必须通过 SSRF 白名单校验（`OAUTH_ALLOWED_REDIRECTS` 环境变量）": "- `redirect_uri` deve passar pela validação da lista de permissões SSRF (variável de ambiente `OAUTH_ALLOWED_REDIRECTS`)",
"### POST /api/platforms/:code/callback — OAuth 回调": "### POST /api/platforms/:code/callback — callback OAuth",
"**请求**: `{ \"state\": \"...\", \"code\": \"...\" }`": "**Requisição**: `{ \"state\": \"...\", \"code\": \"...\" }`",
"**响应**: `{ \"code\": 0, \"data\": { \"account_id\": \"hashids-encoded\" } }`": "**Resposta**: `{ \"code\": 0, \"data\": { \"account_id\": \"hashids-encoded\" } }`",
"### GET /api/accounts — 账户列表": "### GET /api/accounts — lista de contas",
"缓存 5 分钟。": "Cache de 5 minutos.",
"**参数**:": "**Parâmetros**:",
"| 参数 | 说明 |": "| Parâmetro | Descrição |",
"| `platform` | 平台代码筛选 |": "| `platform` | Filtro por código de plataforma |",
"| `page` | 页码 |": "| `page` | Número da página |",
"| `per_page` | 每页条数 |": "| `per_page` | Itens por página |",
"**响应**: 分页格式，list 中每项包含 `id`(hashids), `platform`, `account_name`, `status`, `sync_enabled`, `last_sync_at`": "**Resposta**: formato paginado; cada item de `list` contém `id`(hashids), `platform`, `account_name`, `status`, `sync_enabled`, `last_sync_at`",
"### GET /api/accounts/:id — 账户详情": "### GET /api/accounts/:id — detalhes da conta",
"### DELETE /api/accounts/:id — 解绑账户": "### DELETE /api/accounts/:id — desvincular conta",
"### POST /api/accounts/:id/sync — 手动同步": "### POST /api/accounts/:id/sync — sincronização manual",
"## 模块 4: 广告计划": "## Módulo 4: Planos de anúncios",
"### GET /api/campaigns — 计划列表": "### GET /api/campaigns — lista de planos",
"| 参数 | 说明 | 可选值 |": "| Parâmetro | Descrição | Valores possíveis |",
"| `platform` | 平台筛选 | juliang, meta, google... |": "| `platform` | Filtro de plataforma | juliang, meta, google... |",
"| `status` | 状态筛选 | enabled, paused |": "| `status` | Filtro de status | enabled, paused |",
"| `keyword` | 名称搜索 | 任意文本 |": "| `keyword` | Busca por nome | Qualquer texto |",
"| `sort` | 排序字段 | id, name, platform, daily_budget, status, created_at |": "| `sort` | Campo de ordenação | id, name, platform, daily_budget, status, created_at |",
"| `page` | 页码 | — |": "| `page` | Número da página | — |",
"| `per_page` | 每页条数 | ≤100 |": "| `per_page` | Itens por página | ≤100 |",
"**响应**: 分页格式 + `summary: { total_cost, total_impressions, total_clicks, avg_ctr, avg_cvr }`": "**Resposta**: formato paginado + `summary: { total_cost, total_impressions, total_clicks, avg_ctr, avg_cvr }`",
"### POST /api/campaigns — 创建计划": "### POST /api/campaigns — criar plano",
"**响应**: `{ \"code\": 0, \"data\": { \"id\": \"hashids-encoded\", \"platform_campaign_id\": \"platform-side-id\" } }`": "**Resposta**: `{ \"code\": 0, \"data\": { \"id\": \"hashids-encoded\", \"platform_campaign_id\": \"platform-side-id\" } }`",
"- `daily_budget` 单位：分（20000 = ¥200.00）": "- Unidade de `daily_budget`: centavos (20000 = ¥200.00)",
"### GET /api/campaigns/:id — 计划详情": "### GET /api/campaigns/:id — detalhes do plano",
"**响应**: `{ \"code\": 0, \"data\": { \"campaign\": {...}, \"today\": { \"cost\":..., \"impressions\":... } } }`": "**Resposta**: `{ \"code\": 0, \"data\": { \"campaign\": {...}, \"today\": { \"cost\":..., \"impressions\":... } } }`",
"### PUT /api/campaigns/:id — 更新计划": "### PUT /api/campaigns/:id — atualizar plano",
"**请求**: `{ \"name\": \"新名称\", \"daily_budget\": 30000 }`": "**Requisição**: `{ \"name\": \"Novo nome\", \"daily_budget\": 30000 }`",
"### POST /api/campaigns/:id/toggle — 启停计划": "### POST /api/campaigns/:id/toggle — iniciar/pausar plano",
"**请求**: `{ \"enabled\": false }`": "**Requisição**: `{ \"enabled\": false }`",
"### POST /api/campaigns/batch/toggle — 批量启停": "### POST /api/campaigns/batch/toggle — iniciar/pausar em lote",
"**请求**: `{ \"ids\": [\"hash1\", \"hash2\", \"hash3\"], \"enabled\": false }`": "**Requisição**: `{ \"ids\": [\"hash1\", \"hash2\", \"hash3\"], \"enabled\": false }`",
"**响应**: `{ \"code\": 0, \"data\": { \"success\": 3, \"failed\": 0, \"total\": 3 } }`": "**Resposta**: `{ \"code\": 0, \"data\": { \"success\": 3, \"failed\": 0, \"total\": 3 } }`",
"## 模块 5: 广告组": "## Módulo 5: Grupos de anúncios",
"### GET /api/ad-groups — 广告组列表": "### GET /api/ad-groups — lista de grupos de anúncios",
"**参数**: `platform`, `campaign_id`, `status`, `sort`(id/name/status/bid_amount), `page`, `per_page`": "**Parâmetros**: `platform`, `campaign_id`, `status`, `sort`(id/name/status/bid_amount), `page`, `per_page`",
"### POST /api/ad-groups — 创建广告组": "### POST /api/ad-groups — criar grupo de anúncios",
"- `targeting_template_id`: 可选，从定向模板加载 targeting JSON 并合并": "- `targeting_template_id`: opcional, carrega o targeting JSON do modelo de segmentação e faz merge",
"### GET /api/ad-groups/:id — 广告组详情": "### GET /api/ad-groups/:id — detalhes do grupo de anúncios",
"### PUT /api/ad-groups/:id — 更新广告组": "### PUT /api/ad-groups/:id — atualizar grupo de anúncios",
"### POST /api/ad-groups/:id/toggle — 启停广告组": "### POST /api/ad-groups/:id/toggle — iniciar/pausar grupo de anúncios",
"## 模块 6: 创意": "## Módulo 6: Criativos",
"### GET /api/creatives — 创意列表": "### GET /api/creatives — lista de criativos",
"**参数**: `platform`, `ad_group_id`, `campaign_id`, `media_type`(image/video/text), `sort`, `page`, `per_page`": "**Parâmetros**: `platform`, `ad_group_id`, `campaign_id`, `media_type`(image/video/text), `sort`, `page`, `per_page`",
"### GET /api/creatives/:id — 创意详情": "### GET /api/creatives/:id — detalhes do criativo",
"## 模块 7: 报表": "## Módulo 7: Relatórios",
"### GET /api/reports/summary — 仪表盘汇总": "### GET /api/reports/summary — resumo do dashboard",
"**参数**: `date_start`, `date_end`": "**Parâmetros**: `date_start`, `date_end`",
"**参数**: `date_start`, `date_end`, `platform`": "**Parâmetros**: `date_start`, `date_end`, `platform`",
"### GET /api/reports/custom — 自定义报表": "### GET /api/reports/custom — relatório personalizado",
"| `dimensions[]` | 维度: date, platform, campaign |": "| `dimensions[]` | Dimensões: date, platform, campaign |",
"| `metrics[]` | 指标: cost, impressions, clicks, conversions, ctr, cvr, cpc, cpm, roi |": "| `metrics[]` | Métricas: cost, impressions, clicks, conversions, ctr, cvr, cpc, cpm, roi |",
"| `date_start` | 起始日期 |": "| `date_start` | Data inicial |",
"| `date_end` | 截止日期 |": "| `date_end` | Data final |",
"| `platform` | 平台筛选 |": "| `platform` | Filtro de plataforma |",
"### GET /api/reports/export — 导出报表": "### GET /api/reports/export — exportar relatório",
"**参数**: `format=csv`, `date_start`, `date_end`, `metrics[]`": "**Parâmetros**: `format=csv`, `date_start`, `date_end`, `metrics[]`",
"返回文件下载（CSV UTF-8 BOM 或 Excel .xls）。": "Retorna download de arquivo (CSV UTF-8 BOM ou Excel .xls).",
"### GET /api/reports/export-dashboard — 导出仪表盘 PDF": "### GET /api/reports/export-dashboard — exportar dashboard em PDF",
"### GET /api/reports/calendar — 投放日历": "### GET /api/reports/calendar — calendário de veiculação",
"**响应**: `[{ id, name, platform, status, start_date, end_date, budget }]`": "**Resposta**: `[{ id, name, platform, status, start_date, end_date, budget }]`",
"### GET /api/reports/budget-alerts — 预算预警": "### GET /api/reports/budget-alerts — alertas de orçamento",
"**响应**: `[{ campaign_id, campaign_name, platform, spent, budget, pct, level }]`": "**Resposta**: `[{ campaign_id, campaign_name, platform, spent, budget, pct, level }]`",
"### GET /api/reports/attribution — 归因分析": "### GET /api/reports/attribution — análise de atribuição",
"**参数**: `model`(first_touch/last_touch/linear/time_decay/position_based), `date_start`, `date_end`": "**Parâmetros**: `model`(first_touch/last_touch/linear/time_decay/position_based), `date_start`, `date_end`",
"### GET /api/reports/attribution/models — 归因模型列表": "### GET /api/reports/attribution/models — lista de modelos de atribuição",
"**响应**: `[{ code: \"last_touch\", name: \"末次触点\", description: \"...\" }]`": "**Resposta**: `[{ code: \"last_touch\", name: \"Último contato\", description: \"...\" }]`",
"共 5 种模型。": "Existem 5 modelos no total.",
"## 模块 8: 告警": "## Módulo 8: Alertas",
"### GET /api/alerts/rules — 告警规则列表": "### GET /api/alerts/rules — lista de regras de alerta",
"缓存 2 分钟。": "Cache de 2 minutos.",
"**参数**: `platform`, `enabled`(0/1), `metric`, `page`, `per_page`": "**Parâmetros**: `platform`, `enabled`(0/1), `metric`, `page`, `per_page`",
"### POST /api/alerts/rules — 创建告警规则": "### POST /api/alerts/rules — criar regra de alerta",
"### PUT /api/alerts/rules/:id — 更新告警规则": "### PUT /api/alerts/rules/:id — atualizar regra de alerta",
"### DELETE /api/alerts/rules/:id — 删除告警规则": "### DELETE /api/alerts/rules/:id — excluir regra de alerta",
"### GET /api/alerts/logs — 告警记录": "### GET /api/alerts/logs — registros de alertas",
"**参数**: `status`, `rule_id`, `metric`, `page`, `per_page`": "**Parâmetros**: `status`, `rule_id`, `metric`, `page`, `per_page`",
"### POST /api/alerts/logs/:id/acknowledge — 确认告警": "### POST /api/alerts/logs/:id/acknowledge — confirmar alerta",
"### GET /api/alerts/unread-count — 未读告警数": "### GET /api/alerts/unread-count — número de alertas não lidos",
"缓存 30 秒。前端 30s 轮询。": "Cache de 30 segundos. Polling de 30s no frontend.",
"## 模块 9: 通知": "## Módulo 9: Notificações",
"### GET /api/notifications — 通知列表": "### GET /api/notifications — lista de notificações",
"**参数**: `type`(alert/system), `is_read`(0/1), `page`, `per_page`": "**Parâmetros**: `type`(alert/system), `is_read`(0/1), `page`, `per_page`",
"### GET /api/notifications/unread-count — 未读通知数": "### GET /api/notifications/unread-count — número de notificações não lidas",
"### POST /api/notifications/:id/read — 标记已读": "### POST /api/notifications/:id/read — marcar como lida",
"### POST /api/notifications/read-all — 全部已读": "### POST /api/notifications/read-all — marcar todas como lidas",
"## 模块 10: 自动出价": "## Módulo 10: Lance automático",
"### GET /api/bid-rules — 规则列表": "### GET /api/bid-rules — lista de regras",
"### POST /api/bid-rules — 创建规则": "### POST /api/bid-rules — criar regra",
"**字段说明**:": "**Descrição dos campos**:",
"| 字段 | 类型 | 说明 |": "| Campo | Tipo | Descrição |",
"| metric | cost/impressions/clicks/conversions/ctr/cvr/roi | 监控指标 |": "| metric | cost/impressions/clicks/conversions/ctr/cvr/roi | Métrica monitorada |",
"| condition | gt/gte/lt/lte | 触发条件 |": "| condition | gt/gte/lt/lte | Condição de disparo |",
"| threshold | decimal | 阈值 |": "| threshold | decimal | Limite |",
"| action_type | adjust_budget/toggle_pause/toggle_enable | 动作类型 |": "| action_type | adjust_budget/toggle_pause/toggle_enable | Tipo de ação |",
"| adjust_step | int (分) | 预算调整步长（正=加, 负=减） |": "| adjust_step | int (centavos) | Passo do ajuste de orçamento (positivo=adicionar, negativo=reduzir) |",
"| budget_min | int | 预算下限（分） |": "| budget_min | int | Limite inferior do orçamento (centavos) |",
"| budget_max | int | 预算上限（分） |": "| budget_max | int | Limite superior do orçamento (centavos) |",
"| cooldown_minutes | int | 冷却时间（默认 60） |": "| cooldown_minutes | int | Tempo de resfriamento (padrão 60) |",
"### PUT /api/bid-rules/:id — 更新规则": "### PUT /api/bid-rules/:id — atualizar regra",
"### DELETE /api/bid-rules/:id — 删除规则": "### DELETE /api/bid-rules/:id — excluir regra",
"### GET /api/bid-rules/logs — 出价历史": "### GET /api/bid-rules/logs — histórico de lances",
"**参数**: `rule_id`, `campaign_id`": "**Parâmetros**: `rule_id`, `campaign_id`",
"## 模块 11: 定向模板": "## Módulo 11: Modelos de segmentação",
"### GET /api/targeting-templates — 模板列表": "### GET /api/targeting-templates — lista de modelos",
"**参数**: `platform`": "**Parâmetros**: `platform`",
"### GET /api/targeting-templates/:id — 模板详情": "### GET /api/targeting-templates/:id — detalhes do modelo",
"### POST /api/targeting-templates — 创建模板": "### POST /api/targeting-templates — criar modelo",
"### PUT /api/targeting-templates/:id — 更新模板": "### PUT /api/targeting-templates/:id — atualizar modelo",
"### DELETE /api/targeting-templates/:id — 删除模板": "### DELETE /api/targeting-templates/:id — excluir modelo",
"## 模块 12: 素材库": "## Módulo 12: Biblioteca de materiais",
"### GET /api/assets — 素材列表": "### GET /api/assets — lista de materiais",
"**参数**: `type`(image/video), `page`, `per_page`": "**Parâmetros**: `type`(image/video), `page`, `per_page`",
"### POST /api/assets/upload — 上传素材": "### POST /api/assets/upload — enviar material",
"**请求**: `multipart/form-data`, 字段 `file`": "**Requisição**: `multipart/form-data`, campo `file`",
"- 图片: 最大 5 MB (jpeg/png/gif/webp)": "- Imagens: máximo de 5 MB (jpeg/png/gif/webp)",
"- 视频: 最大 50 MB (mp4)": "- Vídeos: máximo de 50 MB (mp4)",
"**响应**: `{ \"code\": 0, \"data\": { \"id\": \"hashids\", \"url\": \"/uploads/assets/20260522/abc123.jpg\", \"type\": \"image\" } }`": "**Resposta**: `{ \"code\": 0, \"data\": { \"id\": \"hashids\", \"url\": \"/uploads/assets/20260522/abc123.jpg\", \"type\": \"image\" } }`",
"### GET /api/assets/:id — 素材详情": "### GET /api/assets/:id — detalhes do material",
"### DELETE /api/assets/:id — 删除素材": "### DELETE /api/assets/:id — excluir material",
"## Admin 端点（端口 8789）": "## Endpoints Admin (porta 8789)",
"### POST /api/admin/login — 管理员登录": "### POST /api/admin/login — login do administrador",
"**请求**: `{ \"username\": \"admin\", \"password\": \"...\" }`": "**Requisição**: `{ \"username\": \"admin\", \"password\": \"...\" }`",
"**响应**: `{ \"code\": 0, \"data\": { \"access_token\": \"...\", \"user\": {...}, \"csrf_token\": \"...\" } }`": "**Resposta**: `{ \"code\": 0, \"data\": { \"access_token\": \"...\", \"user\": {...}, \"csrf_token\": \"...\" } }`",
"- Token 存入 localStorage": "- Token armazenado em localStorage",
"- `csrf_token` 需在后续 POST/PUT/DELETE 请求的 `X-CSRF-Token` header 中携带": "- `csrf_token` deve ser enviado no header `X-CSRF-Token` das requisições POST/PUT/DELETE subsequentes",
"### GET /api/admin/me — 当前管理员": "### GET /api/admin/me — administrador atual",
"### POST /api/admin/logout — 退出": "### POST /api/admin/logout — sair",
"### GET /api/admin/users — 用户列表": "### GET /api/admin/users — lista de usuários",
"**参数**: `keyword`, `role_id`, `page`, `per_page`": "**Parâmetros**: `keyword`, `role_id`, `page`, `per_page`",
"响应中 `id` 和 `role_id` 使用 hashids 编码。": "Na resposta, `id` e `role_id` são codificados com hashids.",
"### POST /api/admin/users — 创建用户": "### POST /api/admin/users — criar usuário",
"### PUT /api/admin/users/:id — 更新用户": "### PUT /api/admin/users/:id — atualizar usuário",
"### DELETE /api/admin/users/:id — 禁用用户": "### DELETE /api/admin/users/:id — desabilitar usuário",
"### GET /api/admin/users/roles — 角色列表": "### GET /api/admin/users/roles — lista de papéis",
"### GET /api/admin/audit-logs — 审计日志": "### GET /api/admin/audit-logs — logs de auditoria",
"**参数**: `user_id`, `action`, `date_from`, `date_to`, `page`, `per_page`": "**Parâmetros**: `user_id`, `action`, `date_from`, `date_to`, `page`, `per_page`",
"## 错误码参考": "## Referência de códigos de erro",
"| code | HTTP | 说明 |": "| code | HTTP | Descrição |",
"| 0 | 200 | 成功 |": "| 0 | 200 | Sucesso |",
"| 1 | 200/400 | 通用业务错误 |": "| 1 | 200/400 | Erro geral de negócio |",
"| 401 | 401 | 未认证 / Token 过期 / IP/UA 不匹配 |": "| 401 | 401 | Não autenticado / Token expirado / IP/UA não correspondente |",
"| 403 | 403 | 禁止访问（安全拦截） |": "| 403 | 403 | Acesso proibido (interceptação de segurança) |",
"| 404 | 404 | 资源不存在 |": "| 404 | 404 | Recurso não encontrado |",
"| 422 | 422 | 参数校验失败 |": "| 422 | 422 | Falha na validação de parâmetros |",
"| 429 | 429 | 请求过多 / 登录节流 / 并发限制 |": "| 429 | 429 | Muitas requisições / throttle de login / limite de concorrência |",
"| 1001 | 200 | 认证失败（用户名或密码错误） |": "| 1001 | 200 | Falha de autenticação (usuário ou senha incorretos) |",
"## 安全拦截响应": "## Resposta de interceptação de segurança",
"当请求被安全中间件拦截时，返回 403：": "Quando uma requisição é interceptada por um middleware de segurança, retorna 403:",
"## 限流响应": "## Resposta de rate limit",
"`Retry-After` header 包含剩余等待秒数。": "O header `Retry-After` contém os segundos restantes de espera.",
},
}
