# -*- coding: utf-8 -*-
# 葡萄牙语翻译词典（plans 小文件）: {相对路径: {源行: 译文行}}
TRANS = {
"docs/superpowers/plans/2026-05-15-phase3-more-adapters.md": {
"# Phase 3: 扩展广告平台适配器 Implementation Plan": "# Phase 3: Expansão dos Adaptadores de Plataformas de Publicidade — Plano de Implementação",
"**Goal:** 新增腾讯广告、友盟、快手磁力引擎、小红书蒲公英四个平台的适配器。": "**Goal:** Adicionar adaptadores para quatro plataformas: Tencent Ads, Umeng, Kuaishou Magnet Engine e Xiaohongshu Dandelion.",
"**已有适配器（Phase 1+2）：** 巨量引擎、百度营销、淘宝/阿里妈妈": "**Adaptadores existentes (Fases 1+2):** Juliang (Ocean Engine), Baidu Marketing, Taobao/Alimama",
"**Architecture:** 每个适配器实现 `PlatformAdapter` 接口，注册到 `AdapterRegistry`，即可被 OAuth 授权流程、数据同步任务、前端管理后台统一调用。": "**Arquitetura:** Cada adaptador implementa a interface `PlatformAdapter` e é registrado no `AdapterRegistry`, podendo ser chamado de forma unificada pelo fluxo de autorização OAuth, pelas tarefas de sincronização de dados e pelo painel administrativo do frontend.",
"## Task 13: 创建腾讯广告适配器": "## Task 13: Criar o adaptador do Tencent Ads",
"**文件：**": "**Arquivos:**",
"### 适配器规格": "### Especificação do adaptador",
"腾讯广告（广点通）API：": "API do Tencent Ads (Guangdiantong):",
"- 广告计划: `campaigns/get` + `campaigns/add` + `campaigns/update`": "- Planos de publicidade: `campaigns/get` + `campaigns/add` + `campaigns/update`",
"- 报表: `daily_reports/get` (异步：创建任务→轮询→获取)": "- Relatórios: `daily_reports/get` (assíncrono: criar tarefa → consultar → obter)",
"- 金额单位：分（与统一模型一致，无需转换）": "- Unidade monetária: centavos (consistente com o modelo unificado, sem conversão)",
"- 状态映射：`AD_STATUS_NORMAL`→enabled, `AD_STATUS_SUSPEND`→paused, `AD_STATUS_DELETE`→deleted": "- Mapeamento de status: `AD_STATUS_NORMAL`→enabled, `AD_STATUS_SUSPEND`→paused, `AD_STATUS_DELETE`→deleted",
"- 认证方式: `access_token` URL参数 + `nonce`/`timestamp` 防重放": "- Autenticação: `access_token` como parâmetro de URL + `nonce`/`timestamp` contra replay",
"### 腾讯特有 API 签名": "### Assinatura específica da API do Tencent",
"腾讯使用 `access_token` 作为 URL 参数，不需要 MD5 签名，但需要 `nonce`（随机数）+ `timestamp` 防重放。": "O Tencent usa `access_token` como parâmetro de URL; não requer assinatura MD5, mas exige `nonce` (número aleatório) + `timestamp` para proteção contra replay.",
"**字段映射要点：**": "**Pontos-chave do mapeamento de campos:**",
"- `daily_budget` → `daily_budget`（单位已是分，无需转换）": "- `daily_budget` → `daily_budget` (unidade já em centavos, sem conversão)",
"- `configured_status` → `status`（AD_STATUS_NORMAL/SUSPEND/DELETE）": "- `configured_status` → `status` (AD_STATUS_NORMAL/SUSPEND/DELETE)",
"- 报表中 `cost`（分）/`view_count`→`impressions`/`valid_click_count`→`clicks`/`conversions_count`→`conversions`": "- No relatório: `cost` (centavos)/`view_count`→`impressions`/`valid_click_count`→`clicks`/`conversions_count`→`conversions`",
"## Task 14: 创建友盟适配器": "## Task 14: Criar o adaptador da Umeng",
"友盟（Umeng U-App + U-Ads）：": "Umeng (U-App + U-Ads):",
"- 认证方式: API Key + API Secret + MD5 签名": "- Autenticação: API Key + API Secret + assinatura MD5",
"- 友盟侧重**推广效果监测**，与广告投放平台不同——它不直接创建/管理广告计划，而是追踪各渠道推广数据": "- A Umeng foca em **monitoramento do efeito de promoção**, diferente das plataformas de veiculação de anúncios — ela não cria/gerencia planos de publicidade diretamente, mas rastreia os dados de promoção de cada canal",
"- capabilities: `['report', 'oauth']` （不支持 campaign/create/update/toggle）": "- capabilities: `['report', 'oauth']` (não suporta campaign/create/update/toggle)",
"- 报表接口：`/v1/ad_analytics/report` 返回按渠道/日期维度的推广数据": "- Endpoint de relatório: `/v1/ad_analytics/report` retorna os dados de promoção por canal/data",
"- fetchCampaigns 返回空（友盟不自建计划）": "- fetchCampaigns retorna vazio (a Umeng não cria planos próprios)",
"- fetchReports 拉取推广效果数据映射到统一报表模型": "- fetchReports busca os dados de efeito de promoção e os mapeia para o modelo de relatório unificado",
"### 友盟签名算法": "### Algoritmo de assinatura da Umeng",
"通过 HTTP Header 传认证信息：`X-Umeng-API-Key`、`X-Umeng-Sign`、`X-Umeng-Timestamp`。": "As informações de autenticação são enviadas via cabeçalhos HTTP: `X-Umeng-API-Key`, `X-Umeng-Sign`, `X-Umeng-Timestamp`.",
"- `channel` → `platform_campaign_id`（渠道标识映射到计划维度）": "- `channel` → `platform_campaign_id` (o identificador do canal é mapeado para a dimensão de plano)",
"- `pv` → `impressions`（展示）": "- `pv` → `impressions` (impressões)",
"- `click` → `clicks`（点击）": "- `click` → `clicks` (cliques)",
"- `activation` → `conversions`（激活/转化）": "- `activation` → `conversions` (ativações/conversões)",
"- `cost` 单位：元 → 分 (×100)": "- Unidade de `cost`: yuan → centavos (×100)",
"## Task 15: 创建快手磁力引擎适配器": "## Task 15: Criar o adaptador do Kuaishou Magnet Engine",
"快手磁力引擎（Kwai Ads）：": "Kuaishou Magnet Engine (Kwai Ads):",
"- 认证方式: `access_token` Header": "- Autenticação: cabeçalho `access_token`",
"- 广告计划: `/campaign/list` + `/campaign/create` + `/campaign/update`": "- Planos de publicidade: `/campaign/list` + `/campaign/create` + `/campaign/update`",
"- 报表: `/report/campaign/report` (同步返回)": "- Relatórios: `/report/campaign/report` (retorno síncrono)",
"- 金额单位：元 → 分 (×100)": "- Unidade monetária: yuan → centavos (×100)",
"- `day_budget` → `daily_budget`（元→分 ×100）": "- `day_budget` → `daily_budget` (yuan→centavos ×100)",
"- `put_status` → `status`（1→enabled, 2→paused, 3→deleted）": "- `put_status` → `status` (1→enabled, 2→paused, 3→deleted)",
"- 报表中 `charge`→`cost`（元→分）/`impression`→`impressions`/`click`→`clicks`/`action_count`→`conversions`": "- No relatório: `charge`→`cost` (yuan→centavos)/`impression`→`impressions`/`click`→`clicks`/`action_count`→`conversions`",
"## Task 16: 创建小红书蒲公英适配器": "## Task 16: Criar o adaptador do Xiaohongshu Dandelion",
"小红书蒲公英（小红书聚光平台）：": "Xiaohongshu Dandelion (plataforma Juguang do Xiaohongshu):",
"- 认证方式: `access_token` Header (`Authorization: Bearer xxx`)": "- Autenticação: cabeçalho `access_token` (`Authorization: Bearer xxx`)",
"- 广告计划: `/v1/campaign/list` + `/v1/campaign/create` + `/v1/campaign/update`": "- Planos de publicidade: `/v1/campaign/list` + `/v1/campaign/create` + `/v1/campaign/update`",
"- 报表: `/v1/report/campaign/report`": "- Relatórios: `/v1/report/campaign/report`",
"- 金额单位：分（小红书API返回分，无需转换）": "- Unidade monetária: centavos (a API do Xiaohongshu retorna centavos, sem conversão)",
"- capabilities: `['report', 'campaign', 'creative', 'oauth']`": "- capabilities: `['report', 'campaign', 'creative', 'oauth']`",
"- `day_budget` → `daily_budget`（单位：分）": "- `day_budget` → `daily_budget` (unidade: centavos)",
"- `status` → `status`（`CAMPAIGN_STATUS_ENABLE`→enabled, `CAMPAIGN_STATUS_DISABLE`→paused, `CAMPAIGN_STATUS_DELETE`→deleted）": "- `status` → `status` (`CAMPAIGN_STATUS_ENABLE`→enabled, `CAMPAIGN_STATUS_DISABLE`→paused, `CAMPAIGN_STATUS_DELETE`→deleted)",
"- 报表中 `spend`→`cost`/`impression`→`impressions`/`click`→`clicks`/`conversion`→`conversions`": "- No relatório: `spend`→`cost`/`impression`→`impressions`/`click`→`clicks`/`conversion`→`conversions`",
"## 验收标准": "## Critérios de aceitação",
"1. ✅ 腾讯广告适配器实现全部 13 个 PlatformAdapter 方法": "1. ✅ O adaptador do Tencent Ads implementa todos os 13 métodos do PlatformAdapter",
"2. ✅ 友盟适配器实现 report + oauth 能力（友盟不支持投放操作）": "2. ✅ O adaptador da Umeng implementa as capacidades report + oauth (a Umeng não suporta operações de veiculação)",
"3. ✅ 快手磁力引擎适配器实现全部 13 个方法": "3. ✅ O adaptador do Kuaishou Magnet Engine implementa todos os 13 métodos",
"4. ✅ 小红书蒲公英适配器实现全部 13 个方法": "4. ✅ O adaptador do Xiaohongshu Dandelion implementa todos os 13 métodos",
"5. ✅ 4个适配器均在 bootstrap.php 注册": "5. ✅ Os 4 adaptadores estão registrados no bootstrap.php",
"6. ✅ `GET /api/v1/platforms` 返回 7 个平台（含之前3个）": "6. ✅ `GET /api/v1/platforms` retorna 7 plataformas (incluindo as 3 anteriores)",
"7. ✅ 所有适配器 curl 调用正确错误处理（curl_errno + CURLOPT_CONNECTTIMEOUT）": "7. ✅ Todos os adaptadores tratam erros corretamente nas chamadas curl (curl_errno + CURLOPT_CONNECTTIMEOUT)",
},
"docs/superpowers/plans/2026-05-15-phase4-17-adapters.md": {
"# Phase 4: 大规模平台适配器扩展计划": "# Phase 4: Plano de Expansão de Adaptadores de Plataformas em Grande Escala",
"> 新增 17 个广告平台适配器（国内 7 + 国外 10）": "> Adicionar 17 adaptadores de plataformas de publicidade (7 nacionais + 10 internacionais)",
"## 已有适配器（7个）": "## Adaptadores existentes (7)",
"巨量引擎、百度营销、淘宝/阿里妈妈、腾讯广告、友盟、快手磁力引擎、小红书蒲公英": "Juliang (Ocean Engine), Baidu Marketing, Taobao/Alimama, Tencent Ads, Umeng, Kuaishou Magnet Engine, Xiaohongshu Dandelion",
"## 新增国内平台（7个）": "## Novas plataformas nacionais (7)",
"| # | 平台 | Adapter类 | API特点 |": "| # | Plataforma | Classe Adapter | Características da API |",
"| 17 | 微博粉丝通 | Weibo.php | OAuth2, Bearer token, 金额:分, 同步报表 |": "| 17 | Weibo Fans Tong | Weibo.php | OAuth2, Bearer token, valor:centavos, relatório síncrono |",
"| 18 | B站花火 | Bilibili.php | OAuth2, Bearer token, 金额:分, 内容营销为主 |": "| 18 | Bilibili Huahuo | Bilibili.php | OAuth2, Bearer token, valor:centavos, foco em marketing de conteúdo |",
"| 19 | 优酷广告 | Youku.php | 阿里系(同Taobao签名), 金额:元→分 |": "| 19 | Youku Ads | Youku.php | Grupo Alibaba (mesma assinatura do Taobao), valor:yuan→centavos |",
"| 20 | 美团广告 | Meituan.php | OAuth2, Bearer token, 金额:分, 本地生活 |": "| 20 | Meituan Ads | Meituan.php | OAuth2, Bearer token, valor:centavos, serviços locais |",
"| 21 | 知乎广告 | Zhihu.php | OAuth2, Bearer token, 金额:元→分, 内容营销 |": "| 21 | Zhihu Ads | Zhihu.php | OAuth2, Bearer token, valor:yuan→centavos, marketing de conteúdo |",
"| 22 | 360推广 | Qihoo360.php | OAuth2, API Key签名, 金额:元→分 |": "| 22 | Qihoo 360 Promotion | Qihoo360.php | OAuth2, assinatura API Key, valor:yuan→centavos |",
"| 23 | 搜狗推广 | Sogou.php | OAuth2, API Key签名, 金额:元→分 |": "| 23 | Sogou Promotion | Sogou.php | OAuth2, assinatura API Key, valor:yuan→centavos |",
"## 新增国外平台（10个）": "## Novas plataformas internacionais (10)",
"| 24 | Meta Ads | Meta.php | OAuth2, Graph API, 金额:分(cent), 系统Token |": "| 24 | Meta Ads | Meta.php | OAuth2, Graph API, valor:centavos (cent), token do sistema |",
"| 25 | Amazon Ads | Amazon.php | OAuth2(Login with Amazon), Profile-based auth, 金额:分(cent) |": "| 25 | Amazon Ads | Amazon.php | OAuth2 (Login with Amazon), auth baseada em perfil, valor:centavos (cent) |",
"| 26 | LinkedIn Ads | Linkedin.php | OAuth2, Bearer token, 金额:分(cent), REST API |": "| 26 | LinkedIn Ads | Linkedin.php | OAuth2, Bearer token, valor:centavos (cent), API REST |",
"| 27 | The Trade Desk | TheTradeDesk.php | API Key + Secret header, DSP, 金额:分(cent) |": "| 27 | The Trade Desk | TheTradeDesk.php | API Key + Secret no header, DSP, valor:centavos (cent) |",
"| 28 | Snapchat Ads | Snapchat.php | OAuth2, Bearer token, 金额:分(cent micro) |": "| 28 | Snapchat Ads | Snapchat.php | OAuth2, Bearer token, valor:centavos (cent micro) |",
"| 29 | Spotify Ads | Spotify.php | OAuth2, Bearer token, 金额:分(cent), Audio |": "| 29 | Spotify Ads | Spotify.php | OAuth2, Bearer token, valor:centavos (cent), Audio |",
"| 30 | Twitch Ads | Twitch.php | OAuth2, Bearer token, 金额:分(cent) |": "| 30 | Twitch Ads | Twitch.php | OAuth2, Bearer token, valor:centavos (cent) |",
"| 31 | Netflix Ads | Netflix.php | OAuth2 client_credentials, 金额:分(cent), 有限API |": "| 31 | Netflix Ads | Netflix.php | OAuth2 client_credentials, valor:centavos (cent), API limitada |",
"| 32 | Pinterest Ads | Pinterest.php | OAuth2, Bearer token, 金额:分(cent micro) |": "| 32 | Pinterest Ads | Pinterest.php | OAuth2, Bearer token, valor:centavos (cent micro) |",
"| 33 | Twitter/X Ads | Twitter.php | OAuth1.0a + OAuth2, 金额:分(cent), 自定义签名 |": "| 33 | Twitter/X Ads | Twitter.php | OAuth1.0a + OAuth2, valor:centavos (cent), assinatura personalizada |",
"## 设计原则": "## Princípios de design",
"所有适配器遵循统一的 PlatformAdapter 接口。核心差异仅在于：": "Todos os adaptadores seguem a interface unificada PlatformAdapter. As diferenças essenciais são apenas:",
"1. **认证方式**: OAuth2 Bearer / URL参数 / Header API Key+Sign / OAuth1.0a": "1. **Autenticação**: OAuth2 Bearer / parâmetro de URL / API Key+Sign no Header / OAuth1.0a",
"2. **金额单位**: 统一转为分(国内)/分-cent(国外)，适配器内部处理平台差异": "2. **Unidade monetária**: conversão unificada para centavos (nacional)/centavos-cent (internacional); o adaptador trata as diferenças de plataforma internamente",
"3. **报表模式**: 同步分页 / 异步创建→轮询→获取": "3. **Modo de relatório**: paginação síncrona / assíncrono criar→consultar→obter",
"4. **capabilities**: 部分平台不支持 campaign 管理，仅 report": "4. **capabilities**: algumas plataformas não suportam gerenciamento de campanhas, apenas report",
"## 实施策略": "## Estratégia de implementação",
"按平台共性分组，每组 4-5 个适配器并行创建：": "Agrupar por características comuns das plataformas, criando 4-5 adaptadores por grupo em paralelo:",
"- **Batch A (国内 OAuth2 系)**: Weibo, Bilibili, Meituan, Zhihu": "- **Batch A (nacionais com OAuth2)**: Weibo, Bilibili, Meituan, Zhihu",
"- **Batch B (国内签名系)**: Youku, Qihoo360, Sogou": "- **Batch B (nacionais com assinatura)**: Youku, Qihoo360, Sogou",
"- **Batch C (国际 Meta系)**: Meta, LinkedIn, Snapchat, Pinterest, Twitter": "- **Batch C (internacionais Meta)**: Meta, LinkedIn, Snapchat, Pinterest, Twitter",
"- **Batch D (国际 DSP系)**: Amazon, TheTradeDesk, Spotify, Twitch, Netflix": "- **Batch D (internacionais DSP)**: Amazon, TheTradeDesk, Spotify, Twitch, Netflix",
"每批 4-5 个适配器，修改 bootstrap.php 注册。": "Cada lote tem 4-5 adaptadores; modificar o bootstrap.php para registrá-los.",
},
"docs/superpowers/plans/2026-05-15-phase5-alert-system.md": {
"# Phase 5: 告警推送系统 Implementation Plan": "# Phase 5: Plano de Implementação do Sistema de Push de Alertas",
"**Goal:** 实现广告数据监控告警，支持自定义规则（花费超限/ROI过低/转化骤降），通过多种渠道推送。": "**Goal:** Implementar alertas de monitoramento dos dados de publicidade, com suporte a regras personalizadas (gasto acima do limite/ROI muito baixo/queda brusca de conversões) e envio por vários canais.",
"## Task 25: 告警数据模型 + 规则引擎": "## Task 25: Modelo de dados de alerta + mecanismo de regras",
"## Task 26: 告警推送渠道": "## Task 26: Canais de envio de alertas",
"## Task 27: 告警调度 + 实时推送": "## Task 27: Agendamento de alertas + push em tempo real",
},
"docs/superpowers/plans/2026-05-16-phase5-stabilization.md": {
"# Phase 5: 稳定化计划": "# Phase 5: Plano de Estabilização",
"## 清单": "## Lista de verificação",
"| # | 项目 | 内容 |": "| # | Item | Conteúdo |",
"| 1 | Docker 部署 | Dockerfile (PHP+webman), nginx conf, docker-compose, Redis, MySQL |": "| 1 | Implantação Docker | Dockerfile (PHP+webman), nginx conf, docker-compose, Redis, MySQL |",
"| 2 | API 文档 | 完整的 API 参考文档 |": "| 2 | Documentação da API | Documentação completa de referência da API |",
"| 3 | 性能优化 | Redis 缓存层, 数据库索引优化, 查询优化 |": "| 3 | Otimização de desempenho | Camada de cache Redis, otimização de índices do banco de dados, otimização de consultas |",
"| 4 | 安全加固 | Rate limiting, 输入校验, SQL注入防护, XSS防护 |": "| 4 | Reforço de segurança | Rate limiting, validação de entrada, proteção contra injeção de SQL, proteção XSS |",
"| 5 | 速率限制中间件 | 基于 Redis 的令牌桶/滑动窗口限流 |": "| 5 | Middleware de limitação de taxa | Limitador baseado em Redis (token bucket/janela deslizante) |",
"| 6 | Docker Compose | 一键启动全部服务 |": "| 6 | Docker Compose | Inicia todos os serviços com um comando |",
"| 7 | README | 项目说明 |": "| 7 | README | Descrição do projeto |",
"## 实施顺序": "## Ordem de implementação",
"**Task 28: Docker 部署 + docker-compose**": "**Task 28: Implantação Docker + docker-compose**",
"**Task 29: Rate limiting + 安全加固**": "**Task 29: Rate limiting + reforço de segurança**",
"**Task 30: Redis 缓存层 + 性能优化**": "**Task 30: Camada de cache Redis + otimização de desempenho**",
"**Task 31: API 文档 + README**": "**Task 31: Documentação da API + README**",
},
"docs/superpowers/plans/2026-05-15-phase6-erik-stack.md": {
"> 全面重构：数据库前缀、ID体系、加密体系、版权、代码规范": "> Refatoração abrangente: prefixo do banco de dados, sistema de IDs, sistema de criptografia, direitos autorais, padrões de código",
"## 变更清单": "## Lista de alterações",
"| # | 变更 | 包 | 影响范围 |": "| # | Alteração | Pacote | Escopo de impacto |",
"| 1 | 数据库表前缀 `erik_` | — | 所有 SQL/迁移文件 |": "| 1 | Prefixo `erik_` das tabelas do banco | — | Todos os arquivos SQL/migração |",
"| 2 | 主键 Snowflake ID (无自增) | erikwang2013/snowflake-php | 所有 Model + SQL |": "| 2 | Chave primária Snowflake ID (sem autoincremento) | erikwang2013/snowflake-php | Todos os Models + SQL |",
"| 3 | API ID hashids 加解密 | erikwang2013/hashids | 所有 Controller 响应 |": "| 3 | Criptografia/descriptografia de IDs da API com hashids | erikwang2013/hashids | Todas as respostas dos Controllers |",
"| 4 | JWT 认证切换 | erikwang2013/jwt-webman | AuthMiddleware + AuthController |": "| 4 | Migração de autenticação JWT | erikwang2013/jwt-webman | AuthMiddleware + AuthController |",
"| 5 | API 敏感数据加解密 | erikwang2013/encryption | API 请求/响应层 |": "| 5 | Criptografia de dados sensíveis da API | erikwang2013/encryption | Camada de requisições/respostas da API |",
"| 6 | DB 敏感数据加解密 | erikwang2013/encryptable | Eloquent Model 层 |": "| 6 | Criptografia de dados sensíveis do banco | erikwang2013/encryptable | Camada de Models Eloquent |",
"| 7 | ES 数据同步/查询 | erikwang2013/webman-scout | 报表搜索 |": "| 7 | Sincronização/consulta de dados ES | erikwang2013/webman-scout | Busca de relatórios |",
"| 8 | 国家旗帜 | erikwang2013/season | 前端平台标签 |": "| 8 | Bandeiras de países | erikwang2013/season | Etiquetas de plataforma no frontend |",
"| 9 | 版权声明 | — | 所有文件头部 |": "| 9 | Aviso de direitos autorais | — | Cabeçalho de todos os arquivos |",
"| 10 | 移除全局 `\\` 前缀 | — | 所有 PHP 文件 |": "| 10 | Remover o prefixo global `\\` | — | Todos os arquivos PHP |",
"| 11 | 配置文件加注释 | — | config/*.php |": "| 11 | Adicionar comentários nos arquivos de configuração | — | config/*.php |",
"| 12 | Flutter Web PC 布局 | — | Flutter 项目 |": "| 12 | Layout Flutter Web para PC | — | Projeto Flutter |",
"| 13 | Admin 面板可视化增强 | — | 仪表盘图表 |": "| 13 | Aprimoramento de visualização do painel Admin | — | Gráficos do dashboard |",
"| 14 | 面板数据导出 PDF | — | 新增导出格式 |": "| 14 | Exportação de dados do painel em PDF | — | Novo formato de exportação |",
"| 15 | Excel 导出(Client+Admin) | — | 增强导出 |": "| 15 | Exportação Excel (Client+Admin) | — | Exportação aprimorada |",
"| 16 | HarmonyOS App | — | 新建鸿蒙项目 |": "| 16 | Aplicativo HarmonyOS | — | Novo projeto HarmonyOS |",
"## 实施顺序": "## Ordem de implementação",
"**Batch A: 基础设施（依赖 + ID + 加密）**": "**Batch A: Infraestrutura (dependências + ID + criptografia)**",
"- 更新 composer.json 添加 6 个 erikwang2013 包": "- Atualizar o composer.json adicionando os 6 pacotes erikwang2013",
"- 重写所有 SQL 迁移文件（erik_ 前缀 + bigint 无自增）": "- Reescrever todos os arquivos de migração SQL (prefixo erik_ + bigint sem autoincremento)",
"- 创建 Snowflake ID trait": "- Criar a trait de Snowflake ID",
"- 更新所有 Model（使用 SnowflakeTrait）": "- Atualizar todos os Models (usando SnowflakeTrait)",
"- 配置 hashids 中间件": "- Configurar o middleware de hashids",
"- 切换 JWT 到 jwt-webman": "- Migrar o JWT para o jwt-webman",
"**Batch B: 代码清理**": "**Batch B: Limpeza de código**",
"- 移除所有 `\\` 全局前缀": "- Remover todos os prefixos globais `\\`",
"- 所有文件添加版权头": "- Adicionar cabeçalho de direitos autorais a todos os arquivos",
"- 配置文件加注释": "- Adicionar comentários nos arquivos de configuração",
"**Batch C: 前端增强**": "**Batch C: Aprimoramentos de frontend**",
"- Admin 面板可视化增强（更多图表、实时数据）": "- Aprimoramento de visualização do painel Admin (mais gráficos, dados em tempo real)",
"- 面板数据导出 PDF": "- Exportação de dados do painel em PDF",
"- Excel 导出增强": "- Aprimoramento da exportação Excel",
"- Flutter Web PC 布局项目": "- Projeto de layout Flutter Web para PC",
"- HarmonyOS 项目骨架": "- Estrutura base do projeto HarmonyOS",
},
"docs/superpowers/plans/2026-08-07-phase7-contract-fix.md": {
"# Phase 7: 跨端契约修复 Implementation Plan": "# Phase 7: Plano de Implementação da Correção de Contratos entre Plataformas",
"> **状态更新（2026-08-16）：** Task 1 ✅ / Task 2 ✅ / Task 3 ✅ / Task 4 ✅ 全部完成，tester 回归验证通过（35 tests OK，契约交叉核对无幽灵端点，Phase 7 可验收）。": "> **Atualização de status (2026-08-16):** Task 1 ✅ / Task 2 ✅ / Task 3 ✅ / Task 4 ✅ concluídas; verificação de regressão do tester aprovada (35 testes OK, verificação cruzada de contratos sem endpoints fantasmas; Fase 7 pronta para aceitação).",
"**Goal:** 修复团队审计发现的跨端 API 契约问题：Flutter 3 个幽灵端点（404）、Admin `admin.ts` 双前缀 bug、`/system/info` 无路由、ServiceProxy 未接线、文档口径过时。恢复三端（Admin/Flutter/HarmonyOS）对 service API 的一致消费。": "**Goal:** Corrigir os problemas de contrato de API entre plataformas encontrados na auditoria da equipe: 3 endpoints fantasmas do Flutter (404), bug de prefixo duplicado no `admin.ts` do Admin, `/system/info` sem rota, ServiceProxy não conectado e documentação desatualizada. Restaurar o consumo consistente da API do service pelos três clientes (Admin/Flutter/HarmonyOS).",
"**来源:** 2026-08-07 团队并行审计（backend-dev 路由盘点 61 端点、vue-dev Admin 调用盘点 50 调用点、mobile-dev 移动端盘点、researcher 已实现/已规划盘点交叉比对）": "**Fonte:** Auditoria paralela da equipe em 2026-08-07 (backend-dev inventariou 61 endpoints de rotas, vue-dev inventariou 50 pontos de chamada do Admin, mobile-dev inventariou o mobile e o researcher fez a comparação cruzada entre o implementado e o planejado)",
"## Task 1: 修复 Flutter 幽灵端点（🔴 最高优先）": "## Task 1: Corrigir os endpoints fantasmas do Flutter (🔴 prioridade máxima)",
"### 背景": "### Contexto",
"Flutter 3 个页面调用了 service 不存在的路由，全部 404：": "Três páginas do Flutter chamam rotas que não existem no service, todas retornando 404:",
"| Flutter 调用 | service 实际路由 | 修复方案 |": "| Chamada do Flutter | Rota real no service | Solução |",
"| `GET /dashboard` | 无（仪表盘汇总在 `/reports/summary`） | 改为 `GET /reports/summary` |": "| `GET /dashboard` | Nenhuma (resumo do dashboard em `/reports/summary`) | Alterar para `GET /reports/summary` |",
"| `GET /alerts` | 无（告警在 `/alerts/rules`、`/alerts/logs`、`/alerts/unread-count`） | 改为 `GET /alerts/logs`（告警列表语义） |": "| `GET /alerts` | Nenhuma (alertas em `/alerts/rules`, `/alerts/logs`, `/alerts/unread-count`) | Alterar para `GET /alerts/logs` (semântica de lista de alertas) |",
"| `GET /reports` | 无（报表在 `/reports/summary`、`/reports/custom`） | 改为 `GET /reports/custom`（带日期/维度/指标参数，匹配 ReportBuilder::buildCustom） |": "| `GET /reports` | Nenhuma (relatórios em `/reports/summary`, `/reports/custom`) | Alterar para `GET /reports/custom` (com parâmetros de data/dimensão/métrica, correspondente ao ReportBuilder::buildCustom) |",
"- Modify: `apps/flutter/lib/features/dashboard/dashboard_page.dart`（`/dashboard` → `/reports/summary` ×2 区间，适配响应结构 `data.overview`/`by_platform`/`daily`）✅": "- Modificar: `apps/flutter/lib/features/dashboard/dashboard_page.dart` (`/dashboard` → `/reports/summary` em ×2 pontos, adaptando a estrutura de resposta `data.overview`/`by_platform`/`daily`) ✅",
"- Modify: `apps/flutter/lib/features/alert/alert_page.dart`（`/alerts` → `/alerts/logs`，适配分页结构 `data.list`，AlertLog 字段 rule_name/metric/current_value/condition/threshold）✅": "- Modificar: `apps/flutter/lib/features/alert/alert_page.dart` (`/alerts` → `/alerts/logs`, adaptando a estrutura paginada `data.list`, campos do AlertLog rule_name/metric/current_value/condition/threshold) ✅",
"- Modify: `apps/flutter/lib/features/report/report_page.dart`（`/reports` → `/reports/custom`，参数 date_start/date_end/dimensions[]/metrics[]，解析 `data.list`，字段 cost）✅": "- Modificar: `apps/flutter/lib/features/report/report_page.dart` (`/reports` → `/reports/custom`, parâmetros date_start/date_end/dimensions[]/metrics[], analisando `data.list`, campo cost) ✅",
"- Verify: 响应字段与 `service/plugin/ads-api/controller/v1/DashboardController.php` / `AlertController.php` / `ReportBuilder.php` 实际返回一致 ✅": "- Verificar: os campos de resposta são consistentes com o retorno real de `service/plugin/ads-api/controller/v1/DashboardController.php` / `AlertController.php` / `ReportBuilder.php` ✅",
"### 验收": "### Aceitação",
"- [x] 三处路径修改完成，查询参数保留（report 页的日期参数 → date_start/date_end + dimensions/metrics）✅": "- [x] As três alterações de caminho concluídas, parâmetros de consulta preservados (parâmetros de data da página de relatório → date_start/date_end + dimensions/metrics) ✅",
"- [x] 响应解析与后端实际 JSON 结构对齐（overview / paginated list / custom list）✅": "- [x] Análise de resposta alinhada à estrutura JSON real do backend (overview / paginated list / custom list) ✅",
"- [x] 修改后 `flutter analyze` 无错误 — 本环境 Flutter SDK 缓存只读无法运行，改用 SDK 内置 `dart analyze` 全项目 **0 errors**（15 个既有警告均为改动前存在，本次未引入新问题）✅": "- [x] `flutter analyze` sem erros após as alterações — o cache somente leitura do Flutter SDK neste ambiente impede a execução; usando o `dart analyze` embutido no SDK em todo o projeto, **0 erros** (os 15 avisos existentes já estavam presentes antes das alterações; nenhum problema novo foi introduzido) ✅",
"## Task 2: 修复 Admin `admin.ts` 双前缀 bug": "## Task 2: Corrigir o bug de prefixo duplicado no `admin.ts` do Admin",
"- `admin/public/web/src/api/admin.ts` 路径写 `/api/admin/...`，而 axios baseURL 已是 `/api`（`src/api/index.ts`），实际拼成 `/api/api/admin/...`，UserManage.vue / AuditLog.vue 的 5 个调用大概率 404。": "- O caminho em `admin/public/web/src/api/admin.ts` está escrito como `/api/admin/...`, mas o baseURL do axios já é `/api` (`src/api/index.ts`), resultando em `/api/api/admin/...`; as 5 chamadas de UserManage.vue / AuditLog.vue provavelmente retornam 404.",
"- **深层架构问题（vue-dev 最终报告确认）**：admin 后端（8789）自身提供 12 条本地路由（`/api/admin/login`、`me`、`logout`、`users` CRUD、`roles`、`audit-logs`、`/api/install/*`），但：": "- **Problema arquitetural profundo (confirmado no relatório final do vue-dev):** o backend do admin (8789) fornece 12 rotas locais (`/api/admin/login`, `me`, `logout`, CRUD de `users`, `roles`, `audit-logs`, `/api/install/*`), mas:",
"  - `docker/nginx/admin.conf` 的 `location /api/` **全部** proxy_pass 到 `service_api`（php:8788）；": "  - o `location /api/` do `docker/nginx/admin.conf` faz proxy_pass de **tudo** para `service_api` (php:8788);",
"  - `upstream admin_backend`（admin-php:8789）虽已定义，但**没有任何 location 引用它** → 生产环境下 `/api/admin/*` 永远到不了 8789；": "  - o `upstream admin_backend` (admin-php:8789) está definido, mas **nenhum location o referencia** → em produção, `/api/admin/*` nunca chega à porta 8789;",
"  - Vite dev 代理同样将 `/api` 全部指向 8788。": "  - o proxy de desenvolvimento do Vite também aponta todo o `/api` para a porta 8788.",
"  - 结论：即使修好双前缀，`/api/admin/*` 仍 404——admin 后端本地路由在生产链路中未接线。": "  - Conclusão: mesmo corrigindo o prefixo duplicado, `/api/admin/*` continua retornando 404 — as rotas locais do backend do admin não estão conectadas no fluxo de produção.",
"### 决策点（需 backend-dev + vue-dev + devops 确认）": "### Ponto de decisão (requer confirmação de backend-dev + vue-dev + devops)",
"- 方案 A（推荐）：vue-dev 将 `admin.ts` 路径改为相对 `/admin/users`、`/admin/audit-logs`，同时 **devops 在 Nginx 增加 `location /api/admin/` → `proxy_pass http://admin_backend`**（置于 `location /api/` 之前，精确前缀优先匹配），让 admin 专属路由由 8789 直服，业务路由仍走 8788": "- Opção A (recomendada): o vue-dev altera os caminhos de `admin.ts` para `/admin/users`, `/admin/audit-logs`, e o **devops adiciona `location /api/admin/` → `proxy_pass http://admin_backend` no Nginx** (antes de `location /api/`, pois prefixo exato tem prioridade de correspondência), para que as rotas exclusivas do admin sejam servidas diretamente pela 8789 e as rotas de negócio continuem na 8788",
"- 方案 B：backend-dev 在 service 增加 `/api/admin/*` 路由（与 Admin 端职责重叠，不推荐）": "- Opção B: o backend-dev adiciona rotas `/api/admin/*` no service (sobreposição de responsabilidades com o Admin, não recomendada)",
"- 方案 C：业务查询也改走 ServiceProxy（需接线，改动最大，仅当需要 admin 端统一鉴权时才考虑）": "- Opção C: as consultas de negócio também passam pelo ServiceProxy (requer conexão; é a maior mudança; considerar apenas se o Admin precisar de autenticação unificada)",
"- Modify: `admin/public/web/src/api/admin.ts`（去除 `/api` 前缀）": "- Modificar: `admin/public/web/src/api/admin.ts` (remover o prefixo `/api`)",
"- Modify: `docker/nginx/admin.conf`（新增 `location /api/admin/` → admin_backend upstream）": "- Modificar: `docker/nginx/admin.conf` (adicionar `location /api/admin/` → upstream admin_backend)",
"- Modify: `admin/public/web/vite.config.ts`（dev 代理增加 `/api/admin` → 8789 规则，置于 `/api` 之前）": "- Modificar: `admin/public/web/vite.config.ts` (adicionar a regra `/api/admin` → 8789 no proxy de dev, antes de `/api`)",
"- Verify: `admin/config/route.php` 中 admin 后端路由（/api/admin/users 等）与前端调用匹配": "- Verificar: as rotas do backend do admin em `admin/config/route.php` (/api/admin/users etc.) correspondem às chamadas do frontend",
"- [x] 前端请求路径与实际存在的后端路由一致（无 404）— admin.ts 9 个方法全部核对 route.php ✅，vue-tsc 通过": "- [x] Caminhos de requisição do frontend consistentes com as rotas reais do backend (sem 404) — os 9 métodos do admin.ts conferidos com o route.php ✅, vue-tsc aprovado",
"- [x] Nginx / Vite 均能正确分流 `/api/admin/*` 到 8789，`/api/*` 其余到 8788 — Nginx 新增 `location /api/admin/`，Vite 新增 `/api/admin` 代理（置于 `/api` 前）✅": "- [x] Nginx / Vite roteiam corretamente `/api/admin/*` para a 8789 e o restante de `/api/*` para a 8788 — Nginx com novo `location /api/admin/`, Vite com novo proxy `/api/admin` (antes de `/api`) ✅",
"- [x] UserManage / AuditLog 页面功能可用 — 路径已对齐（含 listRoles → `/admin/users/roles` 决策）✅": "- [x] Funcionalidade das páginas UserManage / AuditLog operacional — caminhos alinhados (incluindo a decisão listRoles → `/admin/users/roles`) ✅",
"## Task 3: `/system/info` 无路由 + ServiceProxy 决策": "## Task 3: `/system/info` sem rota + decisão sobre o ServiceProxy",
"- `SystemInfo.vue` / `stores/admin.ts` 调用 `GET /api/system/info`，service 无此路由（仅 /health、/ping），404 被 try/catch 吞掉": "- `SystemInfo.vue` / `stores/admin.ts` chamam `GET /api/system/info`, rota inexistente no service (apenas /health, /ping); o 404 é engolido pelo try/catch",
"- `admin/app/controller/ServiceProxy.php` 已定义但全仓 0 个活跃调用方（\"已定义未接线\"）": "- `admin/app/controller/ServiceProxy.php` está definido, mas não há nenhum chamador ativo no repositório (\"definido mas não conectado\")",
"### 决策点": "### Ponto de decisão",
"- `/system/info`：方案 A — 前端改为调用 `/health`（service 已有）；方案 B — backend-dev 在 service 增加 `/api/system/info` 端点（返回版本/环境信息，对 HarmonyOS/Flutter 也有用，推荐）": "- `/system/info`: opção A — o frontend passa a chamar `/health` (já existente no service); opção B — o backend-dev adiciona o endpoint `/api/system/info` no service (retorna informações de versão/ambiente, útil também para HarmonyOS/Flutter; recomendada)",
"- ServiceProxy：方案 A — 接线到 admin 需要的 admin 专属 API（如审计日志转发）；方案 B — 删除类并更新文档声明\"Admin 直连 service\"（当前实际架构）": "- ServiceProxy: opção A — conectar às APIs exclusivas do admin necessárias (ex.: encaminhamento de logs de auditoria); opção B — excluir a classe e atualizar a documentação declarando \"Admin conecta diretamente ao service\" (arquitetura atual)",
"### 已执行（2026-08-16）": "### Executado (2026-08-16)",
"- **`/system/info` → 方案 A（前端改调 `/health`）**：SystemInfo.vue 改原生 axios 调 `GET /health`，判定 `checks.database === 'ok'`；`/health` 路由在 service 侧不带 `/api` 前缀，Vite 已新增 `/health` 代理，Nginx 原有 `location /health` 已存在；`stores/admin.ts` 死代码同步改为 `/health` ✅": "- **`/system/info` → opção A (frontend passa a chamar `/health`):** SystemInfo.vue usa axios nativo para `GET /health`, verificando `checks.database === 'ok'`; a rota `/health` no service não tem o prefixo `/api`, o Vite já ganhou o proxy `/health` e o Nginx já tinha `location /health`; o código morto em `stores/admin.ts` também foi alterado para `/health` ✅",
"- **ServiceProxy → 方案 B（保留 + 文档说明）**：类保留为预留基础设施（`ServiceProxy::init()` 自初始化无害），`admin/config/app.php` 注释更新为\"预留基础设施，当前无活跃调用方\" ✅": "- **ServiceProxy → opção B (manter + documentar):** a classe é mantida como infraestrutura reservada (`ServiceProxy::init()` é uma auto-inicialização inofensiva), e o comentário em `admin/config/app.php` foi atualizado para \"infraestrutura reservada, sem chamadores ativos no momento\" ✅",
"- [x] `/system/info` 决策落地：前端已移除调用（改 /health），无 404 幽灵请求 ✅": "- [x] Decisão de `/system/info` implementada: frontend sem a chamada (usando /health), sem requisições fantasmas 404 ✅",
"- [x] ServiceProxy 决策落地：保留类并在 config 注释说明现状 ✅": "- [x] Decisão do ServiceProxy implementada: classe mantida, e o comentário no config explica a situação atual ✅",
"## Task 4: 文档回填与口径统一": "## Task 4: Atualização da documentação e uniformização das informações",
"- README\"14 控制器 / 45+ 端点\"过时（实际 17 控制器 / 61 端点）": "- O README \"14 controladores / 45+ endpoints\" está desatualizado (na verdade são 17 controladores / 61 endpoints)",
"- `docs/superpowers/plans/` 各 phase checkbox 未回填（代码已实现但文档未勾选）": "- As checkboxes das fases em `docs/superpowers/plans/` não foram preenchidas (código implementado, mas documentação não marcada)",
"- HarmonyOS 状态\"UI 规划中\"过时（实际 6 页面 + ApiClient 已就绪）": "- O status do HarmonyOS \"UI em planejamento\" está desatualizado (na verdade, 6 páginas + ApiClient prontos)",
"- install.html / InstallController 默认 `.../api/v1` 与 config 默认 `/api`（X-API-Version 头）不一致": "- O padrão `.../api/v1` do install.html / InstallController é inconsistente com o padrão `/api` do config (cabeçalho X-API-Version)",
"- CacheService 注释称两级缓存，实为三级（L1 内存 / APCu / Redis）": "- O comentário do CacheService menciona cache de dois níveis, mas são três (L1 memória / APCu / Redis)",
"- Modify: `README.md` / `README.en.md`（控制器数、端点数、HarmonyOS 状态、缓存层级）": "- Modificar: `README.md` / `README.en.md` (número de controladores, endpoints, status do HarmonyOS, níveis de cache)",
"- Modify: `admin/public/install.html` / `admin/app/controller/InstallController.php`（版本前缀口径统一）": "- Modificar: `admin/public/install.html` / `admin/app/controller/InstallController.php` (uniformizar o prefixo de versão)",
"- Modify: `service/support/CacheService.php`（注释更正）": "- Modificar: `service/support/CacheService.php` (correção de comentário)",
"- Optional: 回填 `docs/superpowers/plans/*.md` checkbox": "- Opcional: preencher as checkboxes de `docs/superpowers/plans/*.md`",
"- README.md / README.en.md：17 控制器 / 61 端点 / HarmonyOS 6 页面 / 19 Vue 页面 / SPA 直连口径全部更新 ✅": "- README.md / README.en.md: 17 controladores / 61 endpoints / 6 páginas HarmonyOS / 19 páginas Vue / conexão direta SPA — tudo atualizado ✅",
"- install.html / InstallController：`/api/v1` 默认值 → `/api`（X-API-Version 头机制）✅": "- install.html / InstallController: valor padrão `/api/v1` → `/api` (mecanismo do cabeçalho X-API-Version) ✅",
"- 8 份 phase plan checkbox 全部回填 ✅（phase7 除外，待执行）": "- As checkboxes de 8 planos de fase preenchidas ✅ (exceto a fase 7, pendente)",
"- [x] README 数据与代码一致（17 控制器 / 61 端点 / HarmonyOS 6 页面）✅": "- [x] Dados do README consistentes com o código (17 controladores / 61 endpoints / 6 páginas HarmonyOS) ✅",
"- [x] 安装向导版本前缀与 X-API-Version 机制一致 ✅": "- [x] Prefixo de versão do assistente de instalação consistente com o mecanismo X-API-Version ✅",
"## 后续阶段规划（Phase 8-10，本计划之外）": "## Planejamento das próximas fases (Fases 8-10, fora deste plano)",
"| Phase | 内容 | 状态 |": "| Phase | Conteúdo | Status |",
"| Phase 8 | 告警多渠道落地：ads-alert 新增 channel/（Email SMTP、Webhook、SMS 网关占位）—— 补 Phase 5 遗留缺口 | 待启动 |": "| Phase 8 | Canais múltiplos de alertas: ads-alert ganha channel/ (Email SMTP, Webhook, placeholder de gateway SMS) — preenche lacunas restantes da Fase 5 | Não iniciada |",
"| Phase 9 | HarmonyOS 真实联调：6 页面接入 ApiClient（当前 0 真实调用，全模拟数据） | 待启动 |": "| Phase 9 | Integração real do HarmonyOS: 6 páginas conectadas ao ApiClient (atualmente 0 chamadas reais, todos os dados simulados) | Não iniciada |",
"| Phase 10 | 深化与商业化：29 平台真实联调、同步状态可视化、转化数据闭环、Flutter/HarmonyOS CI 打包、多租户 SaaS 配额 | 待启动 |": "| Phase 10 | Aprofundamento e comercialização: integração real de 29 plataformas, visualização do status de sincronização, ciclo fechado de dados de conversão, empacotamento CI de Flutter/HarmonyOS, cotas SaaS multitenant | Não iniciada |",
},
"docs/superpowers/plans/2026-08-16-phase8-alert-channels.md": {
"# Phase 8: 告警多渠道落地 Implementation Plan": "# Phase 8: Plano de Implementação dos Canais Múltiplos de Alertas",
"**Goal:** 补齐 Phase 5 遗留缺口——`NotificationService` 的 email/sms 渠道从 echo 存根升级为真实实现（SMTP 邮件 + 通用 Webhook），并支持渠道配置。web 渠道与 Redis pub/sub 已实现，保持不变。": "**Goal:** Preencher as lacunas restantes da Fase 5 — os canais email/sms do `NotificationService` passam de stubs de echo para implementações reais (e-mail SMTP + Webhook genérico), com suporte à configuração de canais. O canal web e o Redis pub/sub já estão implementados e permanecem inalterados.",
"**来源:** Phase 7 团队审计结论（researcher 规划对照：唯一明确\"部分完成\"项 = Phase 5 告警多渠道，`ads-alert` 缺 `channel/` 目录）": "**Fonte:** Conclusão da auditoria da equipe na Fase 7 (comparação de planejamento do researcher: o único item explicitamente \"parcialmente concluído\" = canais múltiplos de alertas da Fase 5, com o `ads-alert` sem o diretório `channel/`)",
"## 现状（已核实）": "## Situação atual (verificada)",
"| 组件 | 状态 |": "| Componente | Status |",
"| `NotificationService::send()` | `match ($channel)` 分发 web/email/sms；web 真实写入 `erik_notifications`，email/sms 为 echo 存根 |": "| `NotificationService::send()` | `match ($channel)` distribui web/email/sms; web grava de fato em `erik_notifications`; email/sms são stubs de echo |",
"| `AlertRule.channels` | JSON 字段 + Eloquent cast array，前端已提交 `['web','email','sms']` |": "| `AlertRule.channels` | Campo JSON + cast array do Eloquent; o frontend já envia `['web','email','sms']` |",
"| Admin AlertRuleList.vue | 已有渠道勾选 UI（web 锁定、email/sms 可选） |": "| Admin AlertRuleList.vue | UI de seleção de canais já existente (web bloqueado, email/sms opcionais) |",
"| Redis pub/sub | `alert:new` 频道推送已实现 |": "| Redis pub/sub | Push no canal `alert:new` já implementado |",
"| SMTP/邮件配置 | 无（service/config 无 mail 配置） |": "| Configuração SMTP/e-mail | Inexistente (service/config não tem configuração de mail) |",
"## Task 1: 邮件渠道（SMTP）": "## Task 1: Canal de e-mail (SMTP)",
"- Create: `service/config/mail.php`（smtp host/port/user/pass/from/from_name/encryption，env 驱动）": "- Criar: `service/config/mail.php` (smtp host/port/user/pass/from/from_name/encryption, orientado por env)",
"- Create: `service/plugin/ads-alert/service/channel/EmailChannel.php`（实现 send(AlertLog, AlertRule)）": "- Criar: `service/plugin/ads-alert/service/channel/EmailChannel.php` (implementa send(AlertLog, AlertRule))",
"- Modify: `service/plugin/ads-alert/service/NotificationService.php`（email 分支调用 EmailChannel，移除 echo 存根）": "- Modificar: `service/plugin/ads-alert/service/NotificationService.php` (o ramo email chama EmailChannel; remover o stub de echo)",
"- Modify: `service/composer.json`（如选 PHPMailer 需加依赖；优先考虑不引依赖的 `mail()`/socket 实现以保持轻量，由实现者评估）": "- Modificar: `service/composer.json` (adicionar dependência se o PHPMailer for escolhido; preferir implementação `mail()`/socket sem dependências para manter a leveza, a critério do implementador)",
"### 设计要点": "### Pontos de design",
"- 收件人：从 AlertRule 配置或租户配置读取（如无，用 `email` 字段或配置默认）": "- Destinatários: lidos da configuração do AlertRule ou do tenant (se ausentes, usar o campo `email` ou o padrão da configuração)",
"- 主题/正文：复用 sendWeb 的文案模板（\"告警触发: {rule.name}\" + 指标/当前值/条件/阈值）": "- Assunto/corpo: reutilizar o modelo de texto do sendWeb (\"Alerta acionado: {rule.name}\" + métrica/valor atual/condição/limiar)",
"- 失败处理：捕获异常记日志，不影响其他渠道与主流程": "- Tratamento de falhas: capturar exceções e registrar em log, sem afetar os outros canais e o fluxo principal",
"- 配置缺失时优雅降级（log 提示，不抛异常中断）": "- Degradação graciosa quando a configuração estiver ausente (aviso no log, sem lançar exceção que interrompa)",
"## Task 2: Webhook 渠道": "## Task 2: Canal Webhook",
"- Create: `service/plugin/ads-alert/service/channel/WebhookChannel.php`（POST JSON 到配置的 URL）": "- Criar: `service/plugin/ads-alert/service/channel/WebhookChannel.php` (POST JSON para a URL configurada)",
"- Modify: `NotificationService::send()` match 增加 `'webhook'` 分支": "- Modificar: adicionar o ramo `'webhook'` no match de `NotificationService::send()`",
"- 配置来源：AlertRule 扩展 `webhook_url` 字段（migration）或 channels 配置；为最小改动，优先在 AlertRule 增加 `webhook_url` 列（可空）": "- Origem da configuração: estender o AlertRule com o campo `webhook_url` (migration) ou a configuração de channels; para mudança mínima, preferir adicionar a coluna `webhook_url` (nullable) no AlertRule",
"- 载荷：`{event: 'alert.triggered', alert: {...}, rule: {...}, timestamp}`，含告警级别/指标/值/阈值/时间": "- Payload: `{event: 'alert.triggered', alert: {...}, rule: {...}, timestamp}`, contendo nível do alerta/métrica/valor/limiar/hora",
"- 超时与重试：连接超时 5s、总超时 10s，失败记日志（不重试，保持简单）": "- Timeout e tentativas: timeout de conexão 5s, timeout total 10s; falhas registradas em log (sem nova tentativa, mantendo simples)",
"- 安全：仅允许 http/https，不做内网地址校验（SSRF 风险记为已知限制，或校验非内网——由实现者评估并记录）": "- Segurança: permitir apenas http/https, sem validação de endereços de rede interna (risco de SSRF documentado como limitação conhecida, ou validar a exclusão de rede interna — a critério e registro do implementador)",
"## Task 3: 短信渠道（网关占位）": "## Task 3: Canal SMS (placeholder de gateway)",
"- Modify: `NotificationService::sendSms`（保留占位，明确注释接入点；如实现者评估有轻量方案可落地）": "- Modificar: `NotificationService::sendSms` (manter o placeholder e comentar claramente o ponto de integração; o implementador pode adotar uma solução leve se avaliar que vale a pena)",
"- 短信网关（阿里云/腾讯云）需 AK/SK 与付费，本阶段保留占位实现，注释标明接入步骤": "- O gateway SMS (Alibaba Cloud/Tencent Cloud) exige AK/SK e pagamento; nesta fase, manter a implementação placeholder com comentários indicando os passos de integração",
"- 前端 UI 的 sms 选项保持可选但后端仅记录日志（明确告知用户未配置网关）": "- A opção sms na UI do frontend permanece selecionável, mas o backend apenas registra em log (informando claramente ao usuário que o gateway não está configurado)",
"## Task 4: 渠道配置与前端": "## Task 4: Configuração de canais e frontend",
"- Modify: `admin/public/web/src/views/alert/AlertRuleList.vue`（如增加 webhook 选项与 URL 输入）": "- Modificar: `admin/public/web/src/views/alert/AlertRuleList.vue` (adicionar opção webhook e campo de URL, se aplicável)",
"- Modify: `service/plugin/ads-api/controller/v1/AlertController.php`（规则创建/更新接受 webhook_url）": "- Modificar: `service/plugin/ads-api/controller/v1/AlertController.php` (criação/atualização de regras aceita webhook_url)",
"- Modify: `service/plugin/ads-alert/model/AlertRule.php`（fillable/casts 增加 webhook_url）": "- Modificar: `service/plugin/ads-alert/model/AlertRule.php` (adicionar webhook_url em fillable/casts)",
"- Modify: `service/plugin/ads-alert/migration/create_alerts.sql`（ALTER 或说明增量脚本）": "- Modificar: `service/plugin/ads-alert/migration/create_alerts.sql` (ALTER ou descrição do script incremental)",
"### 验收": "### Aceitação",
"- [ ] email 渠道：配置 SMTP 后触发告警能收到邮件；未配置时优雅降级": "- [ ] Canal email: após configurar SMTP, o disparo de alerta envia e-mail; sem configuração, degradação graciosa",
"- [ ] webhook 渠道：触发告警时 POST JSON 到配置 URL，载荷字段完整": "- [ ] Canal webhook: ao disparar alerta, POST JSON para a URL configurada com campos completos no payload",
"- [ ] sms 渠道：保持占位，记录日志": "- [ ] Canal sms: manter o placeholder, registrar em log",
"- [ ] web 渠道与 Redis pub/sub 回归不受影响": "- [ ] Regressão do canal web e do Redis pub/sub sem impacto",
"- [ ] Admin 规则表单可配置新渠道字段": "- [ ] O formulário de regras do Admin permite configurar os novos campos de canal",
"- [ ] `php vendor/bin/phpunit --no-coverage` 全过": "- [ ] `php vendor/bin/phpunit --no-coverage` passando integralmente",
"- [ ] 新增/更新测试：AlertEngine/NotificationService 渠道分发测试": "- [ ] Testes novos/atualizados: testes de distribuição de canais do AlertEngine/NotificationService",
},
"docs/superpowers/plans/2026-08-16-phase9-harmonyos.md": {
"# Phase 9: HarmonyOS 真实联调 Implementation Plan": "# Phase 9: Plano de Implementação da Integração Real do HarmonyOS",
"**Goal:** 将 HarmonyOS 端 6 个页面从模拟数据切换为真实 API 调用（service :8788），修复 ApiClient 的 baseUrl 硬编码问题，实现登录真实化，使鸿蒙端成为可用的第三客户端。": "**Goal:** Trocar as 6 páginas do HarmonyOS de dados simulados para chamadas reais de API (service :8788), corrigir o baseUrl codificado do ApiClient, tornar o login real e fazer do HarmonyOS um terceiro cliente utilizável.",
"**来源:** Phase 7 团队审计（mobile-dev 盘点：HarmonyOS 6 页面全部模拟数据、0 处真实调用、ApiClient baseUrl 硬编码 `http://127.0.0.1:8788/api`）": "**Fonte:** Auditoria da equipe na Fase 7 (inventário do mobile-dev: as 6 páginas do HarmonyOS usam apenas dados simulados, 0 chamadas reais, baseUrl `http://127.0.0.1:8788/api` codificado no ApiClient)",
"## 现状（已核实）": "## Situação atual (verificada)",
"| 组件 | 状态 |": "| Componente | Status |",
"| `api/ApiClient.ets` | get/post/put/delete/login 已完备；baseUrl 硬编码 `http://127.0.0.1:8788/api`（Flutter 用同源相对 `/api`）；login() 无调用方 |": "| `api/ApiClient.ets` | get/post/put/delete/login completos; baseUrl `http://127.0.0.1:8788/api` codificado (o Flutter usa o caminho relativo de mesma origem `/api`); login() sem chamadores |",
"| `pages/LoginPage.ets` | 模拟登录（setTimeout 1s 跳转），注释\"replace with actual API call\" |": "| `pages/LoginPage.ets` | Login simulado (setTimeout de 1s para redirecionar), comentário \"replace with actual API call\" |",
"| `pages/DashboardPage.ets` | `@State` 硬编码指标（totalCost=1250000 等） |": "| `pages/DashboardPage.ets` | Métricas codificadas em `@State` (totalCost=1250000 etc.) |",
"| `pages/CampaignListPage.ets` | L187 注释占位 `/campaigns` |": "| `pages/CampaignListPage.ets` | L187 placeholder de comentário `/campaigns` |",
"| `pages/AccountPage.ets` | L138 注释占位 `/accounts` |": "| `pages/AccountPage.ets` | L138 placeholder de comentário `/accounts` |",
"| `pages/AlertPage.ets` | L146 注释占位 `/alerts` |": "| `pages/AlertPage.ets` | L146 placeholder de comentário `/alerts` |",
"| `pages/ReportPage.ets` | L242 注释占位 `/reports?date=` |": "| `pages/ReportPage.ets` | L242 placeholder de comentário `/reports?date=` |",
"| models | Campaign/PlatformAccount/AlertRule/ReportMetric 已存在 |": "| models | Campaign/PlatformAccount/AlertRule/ReportMetric já existem |",
"| i18n | StringResources.ets（15+ keys） |": "| i18n | StringResources.ets (15+ keys) |",
"## Task 1: ApiClient 增强": "## Task 1: Aprimoramento do ApiClient",
"### 设计要点": "### Pontos de design",
"- **baseUrl 改为可配置**：保留 setBaseUrl，默认值仍为 `http://127.0.0.1:8788/api`（真机/模拟器需指向局域网地址，注释说明）；避免 Flutter 式同源相对路径（ArkTS 必须绝对 URL）": "- **baseUrl configurável:** manter setBaseUrl, com o valor padrão ainda `http://127.0.0.1:8788/api` (dispositivos reais/emuladores precisam apontar para um endereço de LAN, conforme comentário); evitar caminho relativo de mesma origem como no Flutter (ArkTS exige URL absoluta)",
"- **修复重复 replayHeaders bug**：`{ ...this.replayHeaders(), ...this.replayHeaders() }` 重复展开（get 方法内）→ 单次": "- **Corrigir o bug de replayHeaders duplicado:** `{ ...this.replayHeaders(), ...this.replayHeaders() }` espalhado duas vezes (no método get) → uma única vez",
"- **login() 返回值适配**：service `POST /api/auth/login` 返回 `{access_token, token_type, expires_in, user}`（对照 `service/plugin/ads-api/controller/v1/AuthController.php` 实际字段——是 access_token 而非 token，需核实后修正 `data.token` 判断）": "- **Adaptação do retorno de login():** o service `POST /api/auth/login` retorna `{access_token, token_type, expires_in, user}` (comparar com os campos reais de `service/plugin/ads-api/controller/v1/AuthController.php` — é access_token, não token; corrigir a verificação `data.token` após a confirmação)",
"- **错误处理**：resp.responseCode 非 2xx 时抛错/返回明确错误信息；JSON.parse 失败保护": "- **Tratamento de erros:** lançar erro/retornar mensagem clara quando resp.responseCode não for 2xx; proteção contra falha de JSON.parse",
"- 保持 get/post/put/delete 返回 `data.data`（ApiResponse 解包）的既有约定": "- Manter a convenção existente de get/post/put/delete retornarem `data.data` (desempacotamento do ApiResponse)",
"## Task 2: LoginPage 真实登录": "## Task 2: Login real no LoginPage",
"- `handleLogin()` 调 `ApiClient.login(username, password)`；成功 → setToken + 跳转 Dashboard；失败 → toast 错误信息": "- `handleLogin()` chama `ApiClient.login(username, password)`; sucesso → setToken + redirecionar para o Dashboard; falha → toast com a mensagem de erro",
"- 加载态 isLoading 已存在，复用": "- O estado de carregamento isLoading já existe; reutilizar",
"- 错误消息优先用 service 返回的 message（ApiResponse envelope），无则通用文案": "- Mensagens de erro: preferir a message retornada pelo service (envelope ApiResponse); caso contrário, texto genérico",
"## Task 3: 五个业务页面真实化": "## Task 3: Tornar reais as cinco páginas de negócio",
"### 端点对照（Phase 7 审计已确认，与 Flutter 修复后一致）": "### Correspondência de endpoints (confirmada pela auditoria da Fase 7, idêntica ao Flutter após a correção)",
"| 页面 | 调用 | 解析 |": "| Página | Chamada | Análise |",
"| DashboardPage | `GET /reports/summary`（今日区间） | `data.overview` → totalCost/total_impressions/avg_ctr 等（金额为分，formatFen 已有） |": "| DashboardPage | `GET /reports/summary` (intervalo de hoje) | `data.overview` → totalCost/total_impressions/avg_ctr etc. (valores em centavos; formatFen já existe) |",
"| CampaignListPage | `GET /campaigns` | `data.list`（分页）→ Campaign model |": "| CampaignListPage | `GET /campaigns` | `data.list` (paginado) → modelo Campaign |",
"| AccountPage | `GET /accounts` | `data.list` → PlatformAccount model |": "| AccountPage | `GET /accounts` | `data.list` → modelo PlatformAccount |",
"| AlertPage | `GET /alerts/logs` | `data.list` → AlertLog 字段（metric/rule_name/current_value/condition/threshold/status） |": "| AlertPage | `GET /alerts/logs` | `data.list` → campos do AlertLog (metric/rule_name/current_value/condition/threshold/status) |",
"| ReportPage | `GET /reports/custom`（date_start/date_end/dimensions[]/metrics[]） | `data.list` → ReportMetric |": "| ReportPage | `GET /reports/custom` (date_start/date_end/dimensions[]/metrics[]) | `data.list` → ReportMetric |",
"- 页面加载（aboutToAppear）触发请求；@State 数据初始化置空/0，避免模拟值残留": "- O carregamento da página (aboutToAppear) dispara a requisição; inicializar os dados @State como vazios/0 para evitar valores simulados residuais",
"- 加载失败显示错误 + 重试（参考 Flutter 页面的错误/重试模式）": "- Em falha de carregamento, exibir erro + tentar novamente (referência ao padrão de erro/nova tentativa das páginas Flutter)",
"- 金额单位：service 返回分为单位的数字，formatFen 已处理": "- Unidade monetária: o service retorna números em centavos; formatFen já trata a conversão",
"- **不新增文件**，保持各页面现有 UI 结构与 i18n": "- **Sem novos arquivos**, manter a estrutura de UI e o i18n existentes das páginas",
"## Task 4: 验证": "## Task 4: Validação",
"### 验收": "### Aceitação",
"- [ ] ApiClient 无重复 replayHeaders、login 返回字段与 AuthController 一致": "- [ ] ApiClient sem replayHeaders duplicado; campos de retorno do login consistentes com o AuthController",
"- [ ] 6 个页面无硬编码模拟业务数据残留（grep 验证）": "- [ ] Nenhum dado de negócio simulado codificado restante nas 6 páginas (verificação com grep)",
"- [ ] 5 个业务页面调用路径与 service 路由一一对应（对照 `service/plugin/ads-api/config/route.php`）": "- [ ] Caminhos de chamada das 5 páginas de negócio correspondem um a um às rotas do service (conferir com `service/plugin/ads-api/config/route.php`)",
"- [ ] ArkTS 语法检查（如本环境有 hvigor/DevEco 工具链则运行；无则说明并人工核对）": "- [ ] Verificação de sintaxe ArkTS (executar se o ambiente tiver o toolchain hvigor/DevEco; caso contrário, documentar e conferir manualmente)",
"- [ ] 回归：service PHPUnit 不受影响": "- [ ] Regressão: PHPUnit do service sem impacto",
},
"docs/superpowers/plans/2026-08-16-phase10-deepen.md": {
"# Phase 10: 深化与商业化 Implementation Plan": "# Phase 10: Plano de Implementação — Aprofundamento e Comercialização",
"**Goal:** 在 Phase 7-9 契约与多渠道基础上，落地同步状态可视化、转化数据闭环、移动端 CI 打包、多租户 SaaS 配额四项深化能力。": "**Goal:** Com base nos contratos das Fases 7-9 e nos canais múltiplos, implementar quatro capacidades de aprofundamento: visualização do status de sincronização, ciclo fechado de dados de conversão, empacotamento CI do mobile e cotas SaaS multitenant.",
"**来源:** Phase 7 团队审计推断方向（researcher：ES/读写分离/队列落地、Flutter/鸿蒙 CI、29 平台真实联调、SaaS 计费配额、转化数据闭环、同步状态可视化、AI 出价）": "**Fonte:** Direções inferidas pela auditoria da equipe na Fase 7 (researcher: ES/separacão leitura-escrita/filas, CI de Flutter/HarmonyOS, integração real de 29 plataformas, cotas de cobrança SaaS, ciclo fechado de conversão, visualização do status de sincronização, lances com IA)",
"## 现状（已核实）": "## Situação atual (verificada)",
"| 候选子项 | 现状 |": "| Subitem candidato | Situação atual |",
"| 同步状态可视化 | `erik_sync_errors` 表 + `RetrySyncTask`（重试 3 次、退避 5^n 分钟）已存在；**无前端页面/API 展示同步失败率与延迟** |": "| Visualização do status de sincronização | A tabela `erik_sync_errors` + `RetrySyncTask` (3 tentativas, backoff de 5^n minutos) já existem; **sem página/API de frontend exibindo a taxa de falha e a latência da sincronização** |",
"| 转化数据闭环 | `erik_conversions` + `erik_attribution_results` 表已存在，归因引擎已实现；**无转化数据采集入口**（回传/埋点 API） |": "| Ciclo fechado de dados de conversão | As tabelas `erik_conversions` + `erik_attribution_results` existem e o mecanismo de atribuição está implementado; **sem ponto de coleta de dados de conversão** (API de retorno/rastreamento) |",
"| 移动端 CI | `ci.yml` 仅 PHP 语法→PHPUnit→vue-tsc→Docker；**无 Flutter/HarmonyOS 构建打包** |": "| CI do mobile | `ci.yml` apenas PHP syntax→PHPUnit→vue-tsc→Docker; **sem build/empacotamento de Flutter/HarmonyOS** |",
"| 多租户 SaaS | `erik_tenants` 表 + TenantIdentify 中间件已存在；**无计费/配额/用量统计** |": "| SaaS multitenant | A tabela `erik_tenants` + o middleware TenantIdentify existem; **sem cobrança/cotas/estatísticas de uso** |",
"| ES 落地 | scout.php 已配置 + webman-scout 依赖已引入；**docker-compose 无 ES 服务** |": "| Implementação do ES | scout.php configurado + dependência webman-scout adicionada; **docker-compose sem serviço ES** |",
"| 29 平台真实联调 | 29 适配器代码齐全；**无沙箱/凭据联调记录**（需外部凭据，标记为人工项） |": "| Integração real de 29 plataformas | Código dos 29 adaptadores completo; **sem registros de integração com sandbox/credenciais** (exige credenciais externas; marcado como item manual) |",
"## Task 1: 同步状态可视化": "## Task 1: Visualização do status de sincronização",
"### 设计要点": "### Pontos de design",
"- Modify: `service/plugin/ads-api/controller/v1/DashboardController.php` 或新增 `service/plugin/ads-api/controller/v1/SyncController.php` + route": "- Modificar: `service/plugin/ads-api/controller/v1/DashboardController.php` ou criar `service/plugin/ads-api/controller/v1/SyncController.php` + route",
"- Create: `admin/public/web/src/views/sync/SyncStatus.vue`（或并入系统页）": "- Criar: `admin/public/web/src/views/sync/SyncStatus.vue` (ou incorporar na página de sistema)",
"- 端点：`GET /api/sync/status`（账户维度：last_sync_at、成功率、今日失败数、pending 重试数）+ `GET /api/sync/errors`（分页错误列表，含 last_error/retry_count/next_retry_at）": "- Endpoints: `GET /api/sync/status` (por conta: last_sync_at, taxa de sucesso, falhas de hoje, tentativas pendentes) + `GET /api/sync/errors` (lista paginada de erros com last_error/retry_count/next_retry_at)",
"- 前端：同步状态页（表格 + 摘要卡片），仅 Full/Standard 版本线": "- Frontend: página de status de sincronização (tabela + cards de resumo), apenas nas linhas de versão Full/Standard",
"- 数据源：erik_platform_accounts（last_sync_at）+ erik_sync_errors": "- Fontes de dados: erik_platform_accounts (last_sync_at) + erik_sync_errors",
"## Task 2: 转化数据采集 API": "## Task 2: API de coleta de dados de conversão",
"- Modify: `service/plugin/ads-api/controller/v1/`（新增 ConversionController + route）": "- Modificar: `service/plugin/ads-api/controller/v1/` (adicionar ConversionController + route)",
"- 端点：`POST /api/conversions`（业务方回传转化：platform/campaign_id/order_id/conversion_time/value/currency/channel）+ `GET /api/conversions`（查询）": "- Endpoints: `POST /api/conversions` (o negócio envia conversões: platform/campaign_id/order_id/conversion_time/value/currency/channel) + `GET /api/conversions` (consulta)",
"- 校验：campaign_id 存在、金额非负、时间格式；写入 erik_conversions": "- Validação: campaign_id existente, valor não negativo, formato de data; gravar em erik_conversions",
"- 归因联动：回传后可触发归因重算（或说明由现有 AttributionEngine 定时/手动重算）": "- Integração com atribuição: o envio pode disparar o recálculo de atribuição (ou documentar que o AttributionEngine existente recalcula por agendamento/manualmente)",
"- 前端：归因报表页增加\"转化回传\"说明/演示（可选）": "- Frontend: adicionar explicação/demonstração de \"envio de conversões\" na página de relatório de atribuição (opcional)",
"## Task 3: 移动端 CI 打包": "## Task 3: Empacotamento CI do mobile",
"- Modify: `.github/workflows/ci.yml`（新增 job：Flutter build（web + linux 或 apk）+ HarmonyOS 静态检查）": "- Modificar: `.github/workflows/ci.yml` (novo job: Flutter build (web + linux ou apk) + verificação estática do HarmonyOS)",
"- Flutter：`flutter pub get && flutter analyze && flutter build web`（或 apk，按仓库现状选择可构建目标；如 flutter 环境受限则用 dart analyze）": "- Flutter: `flutter pub get && flutter analyze && flutter build web` (ou apk, escolher o alvo construível conforme o estado do repositório; se o ambiente flutter for limitado, usar dart analyze)",
"- HarmonyOS：无标准 Linux CI 工具链，做静态检查说明或跳过（标注）": "- HarmonyOS: sem toolchain padrão de CI no Linux; documentar a verificação estática ou pular (com anotação)",
"- 与现有 php-tests job 并行，不阻塞主流程": "- Paralelo ao job php-tests existente, sem bloquear o fluxo principal",
"## Task 4: 多租户 SaaS 配额（MVP）": "## Task 4: Cotas SaaS multitenant (MVP)",
"- Modify: `service/plugin/ads-tenant/`（新增 QuotaService）": "- Modificar: `service/plugin/ads-tenant/` (adicionar QuotaService)",
"- 数据：erik_tenants 增加 quota 字段或新表 erik_tenant_quotas（plan/account_limit/campaign_limit/sync_quota）": "- Dados: adicionar campo quota em erik_tenants ou nova tabela erik_tenant_quotas (plan/account_limit/campaign_limit/sync_quota)",
"- 校验点：账户绑定数、计划创建数、每日同步次数（在 AccountController/CampaignController/DataSyncTask 入口检查）": "- Pontos de verificação: número de contas vinculadas, planos criados, sincronizações diárias (verificar nas entradas de AccountController/CampaignController/DataSyncTask)",
"- 端点：`GET /api/tenant/quota`（用量 + 配额）": "- Endpoint: `GET /api/tenant/quota` (uso + cotas)",
"- 前端：系统页展示配额用量（可选，MVP 可仅 API）": "- Frontend: exibir uso de cotas na página de sistema (opcional; o MVP pode ter apenas a API)",
"- 版本线：quota 默认值按 lite/standard/full 差异（config 常量）": "- Linhas de versão: valores padrão de quota diferenciados por lite/standard/full (constantes de config)",
"## 验收（按 Task）": "## Aceitação (por Task)",
"- [ ] Task 1：sync API 端点可用、前端页面展示、测试覆盖": "- [ ] Task 1: endpoints da sync API disponíveis, página de frontend exibindo, cobertura de testes",
"- [ ] Task 2：conversions 回传 API 可写可查、校验生效、测试覆盖": "- [ ] Task 2: API de envio de conversões gravável e consultável, validações ativas, cobertura de testes",
"- [ ] Task 3：CI 新增 job 通过（或明确标注跳过项）": "- [ ] Task 3: novo job de CI aprovado (ou itens ignorados claramente anotados)",
"- [ ] Task 4：quota API 返回正确、超限拦截生效、测试覆盖": "- [ ] Task 4: quota API com retornos corretos, bloqueio de excesso ativo, cobertura de testes",
"- [ ] 全部：`php vendor/bin/phpunit --no-coverage` 全过、vue-tsc 通过": "- [ ] Todos: `php vendor/bin/phpunit --no-coverage` passando integralmente, vue-tsc aprovado",
"## 不在本期范围（需外部资源）": "## Fora do escopo desta fase (requer recursos externos)",
"- 29 平台真实联调（需各平台凭据/沙箱）": "- Integração real de 29 plataformas (requer credenciais/sandbox de cada plataforma)",
"- ES 服务落地（需 docker-compose 增加 ES 服务与索引初始化）": "- Implementação do serviço ES (requer adicionar o serviço ES ao docker-compose e a inicialização de índices)",
"- AI 出价建议（模型/数据准备）": "- Sugestões de lances com IA (preparação de modelo/dados)",
},
}
