# -*- coding: utf-8 -*-
# 葡萄牙语翻译词典（test-reports）
TRANS = {
"docs/test-reports/go.md": {
"# Go 模块测试报告": "# Relatório de testes do módulo Go",
"- 结论：**N/A（无 Go 模块）**": "- Conclusão: **N/A (sem módulo Go)**",
"- 日期：2026-08-27": "- Data: 2026-08-27",
"## 扫描证据": "## Evidências da varredura",
"全仓库（775 个文件，排除 `.git` / `node_modules` / `vendor`）未找到任何 Go 源文件或模块文件：": "Nenhum arquivo de origem ou módulo Go encontrado em todo o repositório (775 arquivos, excluindo `.git` / `node_modules` / `vendor`):",
"- `*.go`：0 个": "- `*.go`: 0",
"- `go.mod` / `go.sum`：0 个": "- `go.mod` / `go.sum`: 0",
"- 大小写不敏感复扫（`.go` / `go.mod` / `go.sum`）：0 个": "- Revarredura sem diferenciar maiúsculas (`.go` / `go.mod` / `go.sum`): 0",
"- Git 子模块：无（无 `.gitmodules`，`git submodule status` 为空）": "- Submódulos Git: nenhum (sem `.gitmodules`, `git submodule status` vazio)",
"- 全库 grep 工具链关键字（`go build` / `go test` / `Golang`）：0 命中": "- grep em todo o repositório por palavras-chave do toolchain (`go build` / `go test` / `Golang`): 0 ocorrências",
"- Makefile、docker-compose.yml、Dockerfile*、.github/workflows（ci.yml、deploy.yml）、scripts 均无 Go 构建步骤": "- Makefile, docker-compose.yml, Dockerfile*, .github/workflows (ci.yml, deploy.yml) e scripts sem etapas de build Go",
"## N/A 说明：代码库中 Go 的替代物": "## Explicação do N/A: substitutos de Go no repositório",
"| 职责 | 实际技术栈 |": "| Responsabilidade | Stack tecnológica real |",
"| 后端服务 | PHP 8（webman 框架），`service/` 目录 |": "| Backend | PHP 8 (framework webman), diretório `service/` |",
"| 构建/CI | Makefile + docker-compose + GitHub Actions（PHP/Node） |": "| Build/CI | Makefile + docker-compose + GitHub Actions (PHP/Node) |",
"| 系统脚本 | bash（28 个 .sh） |": "| Scripts de sistema | bash (28 arquivos .sh) |",
"结论：本代码库不含 Go 代码，无单元测试可编写或运行。若后续引入 Go 微服务，需在 `go test ./...` 通过后补充本报告。": "Conclusão: este repositório não contém código Go, portanto não há testes unitários a escrever ou executar. Se um microsserviço Go for introduzido no futuro, este relatório deve ser atualizado após `go test ./...` passar.",
},
"docs/test-reports/rust.md": {
"# Rust 模块测试报告": "# Relatório de testes do módulo Rust",
"- 结论：**N/A（无 Rust 模块）**": "- Conclusão: **N/A (sem módulo Rust)**",
"- 日期：2026-08-27": "- Data: 2026-08-27",
"## 扫描证据": "## Evidências da varredura",
"全仓库（775 个文件，排除 `.git` / `node_modules` / `vendor`）未找到任何 Rust 源文件或模块文件：": "Nenhum arquivo de origem ou módulo Rust encontrado em todo o repositório (775 arquivos, excluindo `.git` / `node_modules` / `vendor`):",
"- `*.rs`：0 个": "- `*.rs`: 0",
"- `Cargo.toml` / `Cargo.lock`：0 个": "- `Cargo.toml` / `Cargo.lock`: 0",
"- `build.zig` / `*.zig`：0 个": "- `build.zig` / `*.zig`: 0",
"- 大小写不敏感复扫（`.rs` / `cargo` / `rustc` / `build.zig`）：0 个": "- Revarredura sem diferenciar maiúsculas (`.rs` / `cargo` / `rustc` / `build.zig`): 0",
"- Git 子模块：无（无 `.gitmodules`，`git submodule status` 为空）": "- Submódulos Git: nenhum (sem `.gitmodules`, `git submodule status` vazio)",
"- 全库 grep 工具链关键字（`cargo` / `rustc` / `Rust`）：0 命中": "- grep em todo o repositório por palavras-chave do toolchain (`cargo` / `rustc` / `Rust`): 0 ocorrências",
"- Makefile、docker-compose.yml、Dockerfile*、.github/workflows 均无 Rust 构建步骤": "- Makefile, docker-compose.yml, Dockerfile* e .github/workflows sem etapas de build Rust",
"## N/A 说明：代码库中 Rust 的替代物": "## Explicação do N/A: substitutos de Rust no repositório",
"| 职责 | 实际技术栈 |": "| Responsabilidade | Stack tecnológica real |",
"| 移动端 App（Android/iOS） | Dart（Flutter），`apps/flutter/`（24 个 .dart 文件） |": "| App mobile (Android/iOS) | Dart (Flutter), `apps/flutter/` (24 arquivos .dart) |",
"| 鸿蒙端 App | ArkTS（.ets，18 个文件），`apps/harmonyos/` |": "| App HarmonyOS | ArkTS (.ets, 18 arquivos), `apps/harmonyos/` |",
"| Flutter 桌面原生壳 | C++（linux/windows runner，.cpp/.cc/.h 共 17 个，为 Flutter 脚手架生成，非业务代码） |": "| Shell nativo de desktop do Flutter | C++ (linux/windows runner, 17 arquivos .cpp/.cc/.h no total, gerados pelo scaffolding do Flutter, não são código de negócio) |",
"| 后端服务 | PHP 8（webman），`service/` |": "| Backend | PHP 8 (webman), `service/` |",
"结论：本代码库不含 Rust 代码，无单元测试可编写或运行（`cargo test` 无可执行目标）。若后续引入 Rust 模块，需在 `cargo test` 通过后补充本报告。": "Conclusão: este repositório não contém código Rust, portanto não há testes unitários a escrever ou executar (`cargo test` sem alvos executáveis). Se um módulo Rust for introduzido no futuro, este relatório deve ser atualizado após `cargo test` passar.",
},
}
