# -*- coding: utf-8 -*-
# 葡萄牙语翻译词典（README + docs/index）
TRANS = {
"README.md": {
"# Ads Platform — 多平台广告管理系统": "# Ads Platform — Sistema de gerenciamento de publicidade multiplataforma",
"## 概述": "## Visão geral",
"对接 **29 个广告平台**，统一管理广告投放与跨平台数据报表，支持告警监控、自动出价、多端访问。": "Integra **29 plataformas de publicidade**, gerencia de forma unificada a veiculação de anúncios e os relatórios de dados entre plataformas, com suporte a monitoramento de alertas, lances automáticos e acesso em múltiplos dispositivos.",
"> 架构设计 → [docs/architecture.md](docs/architecture.md)  ": "> Design de arquitetura → [docs/architecture.md](docs/architecture.pt.md)  ",
"> 功能模块 → [docs/features.md](docs/features.md)  ": "> Módulos de funcionalidades → [docs/features.md](docs/features.pt.md)  ",
"> API 文档 → [docs/api.md](docs/api.md) | hg/apidoc: `http://127.0.0.1:8788/apidoc`  ": "> Documentação da API → [docs/api.md](docs/api.pt.md) | hg/apidoc: `http://127.0.0.1:8788/apidoc`  ",
"> 版本对比 → [docs/versions.md](docs/versions.md)（Lite 开源 / Standard & Full 联系 erik@erik.xyz）": "> Comparação de versões → [docs/versions.md](docs/versions.pt.md) (Lite open source / Standard & Full contate erik@erik.xyz)",
"### 支持的平台": "### Plataformas suportadas",
"#### 国内 (16)": "#### Nacionais (16)",
"| 平台 | 适配器 | 认证 |": "| Plataforma | Adaptador | Autenticação |",
"| 巨量引擎 | Juliang | OAuth2 Access-Token |": "| Juliang (Ocean Engine) | Juliang | OAuth2 Access-Token |",
"| 百度营销 | Baidu | OAuth2 + 信封签名 |": "| Baidu Marketing | Baidu | OAuth2 + assinatura de envelope |",
"| 淘宝/阿里妈妈 | Taobao | OAuth2 + MD5 |": "| Taobao/Alimama | Taobao | OAuth2 + MD5 |",
"| 腾讯广告 | Tencent | OAuth2 + nonce |": "| Tencent Ads | Tencent | OAuth2 + nonce |",
"| 快手磁力引擎 | Kuaishou | OAuth2 URL参数 |": "| Kuaishou Magnet Engine | Kuaishou | OAuth2 parâmetro de URL |",
"| 小红书蒲公英 | Xiaohongshu | OAuth2 Bearer |": "| Xiaohongshu Dandelion | Xiaohongshu | OAuth2 Bearer |",
"| 微博粉丝通 | Weibo | OAuth2 Bearer |": "| Weibo Fans Tong | Weibo | OAuth2 Bearer |",
"| B站花火 | Bilibili | OAuth2 Bearer |": "| Bilibili Huahuo | Bilibili | OAuth2 Bearer |",
"| 优酷广告 | Youku | OAuth2 + MD5 |": "| Youku Ads | Youku | OAuth2 + MD5 |",
"| 美团广告 | Meituan | OAuth2 Bearer |": "| Meituan Ads | Meituan | OAuth2 Bearer |",
"| 知乎广告 | Zhihu | OAuth2 Bearer |": "| Zhihu Ads | Zhihu | OAuth2 Bearer |",
"| 360推广 | Qihoo360 | API Key + Sign |": "| Qihoo 360 Promo | Qihoo360 | API Key + Sign |",
"| 搜狗推广 | Sogou | API Key + Sign |": "| Sogou Promo | Sogou | API Key + Sign |",
"| 友盟 | Umeng | API Key + MD5 |": "| Umeng | Umeng | API Key + MD5 |",
"| 京东京准通 | Jingdong | OAuth2 + MD5 |": "| Jingdong Jingzhuntong | Jingdong | OAuth2 + MD5 |",
"| 拼多多广告 | Pinduoduo | OAuth2 + 自定义Sign |": "| Pinduoduo Ads | Pinduoduo | OAuth2 + Sign personalizado |",
"#### 国际 (13)": "#### Internacionais (13)",
"| Meta Ads | Meta | OAuth2 URL参数 |": "| Meta Ads | Meta | OAuth2 parâmetro de URL |",
"## 技术栈": "## Stack de tecnologia",
"| 层 | 技术 | 说明 |": "| Camada | Tecnologia | Descrição |",
"| 服务端 | webman v2 + PHP 8.2+ | 7 个插件，65+ API 端点 |": "| Backend | webman v2 + PHP 8.2+ | 7 plugins, 65+ endpoints de API |",
"| 数据库 | MySQL 8.0 | 28 张表，erik_ 前缀，Snowflake BIGINT 主键 |": "| Banco de dados | MySQL 8.0 | 28 tabelas, prefixo erik_, chave primária Snowflake BIGINT |",
"| 缓存 | Redis 7 | 三级缓存 (L1内存/L2 APCu/L3 Redis)、限流计数、Pub/Sub、消息队列 |": "| Cache | Redis 7 | Cache de três níveis (L1 memória/L2 APCu/L3 Redis), contagem de rate limit, Pub/Sub, fila de mensagens |",
"| 搜索 | Elasticsearch | webman-scout 自动索引同步（已配置） |": "| Busca | Elasticsearch | Sincronização automática de índice webman-scout (configurado) |",
"| 管理后台 | webman-admin v2 + Vue 3 + TypeScript + Element Plus | PHP 后端(端口 8789)，SPA 直连业务 API(端口 8788)，19 页面，ECharts 可视化 |": "| Admin | webman-admin v2 + Vue 3 + TypeScript + Element Plus | Backend PHP (porta 8789), SPA conecta direto à API de negócio (porta 8788), 19 páginas, visualização ECharts |",
"| Flutter | Dart 3 + Riverpod + GoRouter + fl_chart | PC/Mobile 响应式，Desktop Shell 布局，12 页面 |": "| Flutter | Dart 3 + Riverpod + GoRouter + fl_chart | Responsivo PC/Mobile, layout Desktop Shell, 12 páginas |",
"| HarmonyOS | ArkTS + ArkUI | 6 个页面已实现，HTTP 客户端已就绪 |": "| HarmonyOS | ArkTS + ArkUI | 6 páginas implementadas, cliente HTTP pronto |",
"| 部署 | Docker + Nginx + GHCR | Docker Compose 一键启动，GitHub Actions 自动构建推送 |": "| Implantação | Docker + Nginx + GHCR | Docker Compose com um clique, GitHub Actions compila e publica automaticamente |",
"## 架构图": "## Diagrama de arquitetura",
"![系统架构图](docs/diagrams/svg/architecture.svg)": "![Diagrama de arquitetura do sistema](docs/diagrams/svg/architecture.pt.svg)",
"### 请求流程图": "### Diagrama de fluxo de requisições",
"![请求流程图](docs/diagrams/svg/request-flow.svg)": "![Diagrama de fluxo de requisições](docs/diagrams/svg/request-flow.pt.svg)",
"### 功能模块图": "### Diagrama de módulos funcionais",
"![功能模块图](docs/diagrams/svg/functional-modules.svg)": "![Diagrama de módulos funcionais](docs/diagrams/svg/functional-modules.pt.svg)",
"### 数据生命周期图": "### Diagrama do ciclo de vida dos dados",
"![数据生命周期图](docs/diagrams/svg/data-lifecycle.svg)": "![Diagrama do ciclo de vida dos dados](docs/diagrams/svg/data-lifecycle.pt.svg)",
"> 完整版含所有细节标注、Admin 端管道、定时任务甘特图、缓存状态机 → [docs/diagrams/](docs/diagrams/) |": "> A versão completa contém todas as anotações de detalhes, o pipeline do Admin, o gráfico de Gantt das tarefas agendadas e a máquina de estados do cache → [docs/diagrams/](docs/diagrams/) |",
"> 详细架构说明、安全架构、高并发设计见 [架构设计文档](docs/architecture.md) | 历史设计规范见 [design.md](docs/superpowers/specs/design.md)": "> Explicações detalhadas da arquitetura, arquitetura de segurança e design de alta concorrência em [Documento de design de arquitetura](docs/architecture.pt.md) | Especificação de design histórica em [design.md](docs/superpowers/specs/design.pt.md)",
"## 架构说明": "## Explicação da arquitetura",
"- **`service/`** — webman v2 用户端业务 API 服务，监听端口 **8788**。处理广告平台对接、OAuth 授权、数据同步、报表引擎、告警监控等业务逻辑。": "- **`service/`** — serviço de API de negócio do usuário webman v2, escutando na porta **8788**. Trata a integração com plataformas de publicidade, autorização OAuth, sincronização de dados, engine de relatórios, monitoramento de alertas e outras lógicas de negócio.",
"- **`admin/`** — webman-admin v2 独立管理后台，监听端口 **8789**。包含 PHP 后端（认证鉴权、用户管理、系统配置）和 Vue 3 SPA 前端。": "- **`admin/`** — painel administrativo independente webman-admin v2, escutando na porta **8789**. Inclui backend PHP (autenticação, gerenciamento de usuários, configuração do sistema) e frontend Vue 3 SPA.",
"- **管理后台与业务服务的通信** — Vue SPA 通过 axios（baseURL `/api`）直连 service API；admin 专属路由（`/api/admin/*`）由 admin PHP 后端（8789）提供服务，Nginx 按路径分流。": "- **Comunicação entre o painel administrativo e o serviço de negócio** — a Vue SPA conecta diretamente à API do service via axios (baseURL `/api`); as rotas exclusivas do admin (`/api/admin/*`) são servidas pelo backend PHP do admin (8789), com o Nginx fazendo o roteamento por caminho.",
"- **开发模式** — Vite dev server (端口 5173) 将 `/api` 代理至 service:8788；admin PHP 后端在 8789 提供 session 认证和 SPA 静态服务。": "- **Modo de desenvolvimento** — o Vite dev server (porta 5173) faz proxy de `/api` para service:8788; o backend PHP do admin fornece autenticação de sessão e serviço estático da SPA na porta 8789.",
"- **生产模式** — Nginx 将 `/` 路由至 admin:8789（管理后台 SPA），将 `/api/` 路由至 service:8788（业务 API）。": "- **Modo de produção** — o Nginx roteia `/` para admin:8789 (SPA do painel administrativo) e `/api/` para service:8788 (API de negócio).",
"## Erik Stack 集成": "## Integração Erik Stack",
"| 包 | 用途 |": "| Pacote | Finalidade |",
"| `erikwang2013/snowflake-php` | 分布式 Snowflake ID 生成 |": "| `erikwang2013/snowflake-php` | Geração de ID Snowflake distribuído |",
"| `erikwang2013/hashids` | API ID 参数加解密 |": "| `erikwang2013/hashids` | Criptografia/descriptografia de parâmetros de ID da API |",
"| `erikwang2013/jwt-webman` | JWT 认证令牌 |": "| `erikwang2013/jwt-webman` | Token de autenticação JWT |",
"| `erikwang2013/encryption` | API 层敏感数据加解密 |": "| `erikwang2013/encryption` | Criptografia de dados sensíveis na camada de API |",
"| `erikwang2013/encryptable` | DB 字段级自动加解密 |": "| `erikwang2013/encryptable` | Criptografia automática em nível de campo do DB |",
"| `erikwang2013/webman-scout` | Elasticsearch 数据同步 |": "| `erikwang2013/webman-scout` | Sincronização de dados Elasticsearch |",
"| `erikwang2013/season` | 国家旗帜标识 |": "| `erikwang2013/season` | Bandeiras de países |",
"| `erikwang2013/poster-php` | 滑块验证码（登录保护） |": "| `erikwang2013/poster-php` | Captcha deslizante (proteção de login) |",
"| `hg/apidoc` | API 文档自动生成（注解 + Web UI） |": "| `hg/apidoc` | Geração automática de documentação da API (anotações + Web UI) |",
"## 国际化": "## Internacionalização",
"全部界面支持 **中文 (zh-CN)** / **English (en)** 双语切换：": "Todas as interfaces suportam alternância bilíngue **Chinês (zh-CN)** / **Inglês (en)**:",
"| 端 | 技术 | 切换方式 |": "| Plataforma | Tecnologia | Método de alternância |",
"| Admin | vue-i18n v9 | TopBar 语言下拉菜单，localStorage 持久化 |": "| Admin | vue-i18n v9 | Menu suspenso de idioma na TopBar, persistência em localStorage |",
"| Service API | `erik\\support\\I18n` | Accept-Language 请求头 / `?lang=` 参数 |": "| Service API | `erik\\support\\I18n` | Cabeçalho Accept-Language / parâmetro `?lang=` |",
"| Flutter | AppLocalizations + Delegate | 系统语言自动检测 |": "| Flutter | AppLocalizations + Delegate | Detecção automática do idioma do sistema |",
"| HarmonyOS | StringResources | `setLang()` 切换 |": "| HarmonyOS | StringResources | Alternância via `setLang()` |",
"## 安全": "## Segurança",
"### Service 端 (14 层全局 + AuthMiddleware)": "### Lado Service (14 camadas globais + AuthMiddleware)",
"CORS → OriginGuard → SecurityHeaders → AttackGuard → ClientPlatform → ReplayGuard → Version → RateLimit → LoginThrottle → SessionLimit → SQLGuard → Validation → ResponseTime → Encryption → AuthMiddleware（路由层）": "CORS → OriginGuard → SecurityHeaders → AttackGuard → ClientPlatform → ReplayGuard → Version → RateLimit → LoginThrottle → SessionLimit → SQLGuard → Validation → ResponseTime → Encryption → AuthMiddleware (camada de rotas)",
"### Admin 端 (10 层全局 + AuthCheck)": "### Lado Admin (10 camadas globais + AuthCheck)",
"CORS → SecurityHeaders → AttackGuard → ClientPlatform → Version → RateLimit → LoginThrottle → SQLGuard → Validation → CSRF → AuthCheck（路由层）": "CORS → SecurityHeaders → AttackGuard → ClientPlatform → Version → RateLimit → LoginThrottle → SQLGuard → Validation → CSRF → AuthCheck (camada de rotas)",
"### 防护能力总览 (22 项)": "### Visão geral das proteções (22 itens)",
"| 分类 | 防护项 | 说明 |": "| Categoria | Item de proteção | Descrição |",
"| 输入检测 | XSS (11模式) | script/iframe/event handler/javascript:/data: |": "| Detecção de entrada | XSS (11 padrões) | script/iframe/event handler/javascript:/data: |",
"| | 路径遍历 (7模式) | ../ / null byte / /etc/passwd / .env / .git |": "| | Path traversal (7 padrões) | ../ / null byte / /etc/passwd / .env / .git |",
"| | Header 注入 | CRLF 检测 |": "| | Injeção de Header | Detecção de CRLF |",
"| | Body 大小限制 | 10 MiB |": "| | Limite de tamanho do body | 10 MiB |",
"| | Content-Type 白名单 | JSON/Form/Multipart/Plain |": "| | Lista de permissões Content-Type | JSON/Form/Multipart/Plain |",
"| | SQL 注入 | UNION/DROP/ALTER 模式检测 |": "| | Injeção de SQL | Detecção de padrões UNION/DROP/ALTER |",
"| 认证 | JWT Token 绑定 | IP + User-Agent hash 验证 |": "| Autenticação | Vínculo do JWT Token | Verificação de hash IP + User-Agent |",
"| | Token 刷新 + 黑名单 | 旧 Token 自动失效 |": "| | Refresh de Token + lista negra | Token antigo expira automaticamente |",
"| | 登录节流 | 5 次失败 → 15 分钟锁定 (Redis) |": "| | Throttle de login | 5 falhas → bloqueio de 15 minutos (Redis) |",
"| | 并发会话限制 | 每用户最大 3 个活跃 Token |": "| | Limite de sessões concorrentes | Máximo de 3 Tokens ativos por usuário |",
"| | 验证码 | 滑块验证码 (5分钟有效, 5px 容差) |": "| | Captcha | Captcha deslizante (válido por 5 minutos, tolerância de 5px) |",
"| 请求校验 | CORS 白名单 | 生产环境域名白名单 |": "| Validação de requisição | Lista de permissões CORS | Lista de permissões de domínios em produção |",
"| | Origin/Referer 校验 | 跨域来源验证 |": "| | Validação Origin/Referer | Verificação de origem entre domínios |",
"| | CSRF Token | Admin 端 session token 验证 |": "| | CSRF Token | Verificação de token de sessão no Admin |",
"| | 防重放攻击 | Nonce + Timestamp ±5min (非浏览器端) |": "| | Anti-replay | Nonce + Timestamp ±5min (fora do navegador) |",
"| | 接口限流 | 滑动窗口 60次/60s |": "| | Rate limit de API | Janela deslizante 60 req/60s |",
"| | SSRF 防护 | OAuth redirect_uri 白名单 |": "| | Proteção SSRF | Lista de permissões de redirect_uri do OAuth |",
"| 响应头 | CSP | Content-Security-Policy (SPA) |": "| Cabeçalhos de resposta | CSP | Content-Security-Policy (SPA) |",
"| | X-Frame-Options / HSTS | 防点击劫持 + HTTPS 强制 |": "| | X-Frame-Options / HSTS | Anti clickjacking + HTTPS forçado |",
"| 数据保护 | 传输加密 | EncryptionMiddleware (X-Encrypted) |": "| Proteção de dados | Criptografia de transporte | EncryptionMiddleware (X-Encrypted) |",
"| | 存储加密 | Encryptable (DB 字段级) |": "| | Criptografia de armazenamento | Encryptable (nível de campo do DB) |",
"| | 日志脱敏 | password/token/secret → \\*\\*\\* |": "| | Mascaramento de logs | password/token/secret → \\*\\*\\* |",
"### 安全架构图": "### Diagrama de arquitetura de segurança",
"![安全架构图](docs/diagrams/svg/security.svg)": "![Diagrama de arquitetura de segurança](docs/diagrams/svg/security.pt.svg)",
"**防御纵深**：外层（Nginx）→ 入口守卫（5层中间件）→ 身份认证（7项）→ 输入校验（4项）→ 频率控制 → 数据加密 → 审计追溯": "**Defesa em profundidade**: camada externa (Nginx) → guardas de entrada (5 camadas de middleware) → autenticação de identidade (7 itens) → validação de entrada (4 itens) → controle de frequência → criptografia de dados → auditoria e rastreabilidade",
"**认证**：服务端和 admin 统一用 `admin_users` 表 + bcrypt 哈希，JWT 24h + refresh 轮换": "**Autenticação**: o service e o admin usam uniformemente a tabela `admin_users` + hash bcrypt, JWT 24h + rotação de refresh",
"**审计**：所有操作记录 IP / User-Agent / Client-Platform / 操作详情": "**Auditoria**: todas as operações registram IP / User-Agent / Client-Platform / detalhes da operação",
"**二次确认**：删除/解绑/批量操作采用\"输入确认词\"模式（`GlobalConfirm` + `useConfirmStore`）": "**Confirmação secundária**: operações de exclusão/desvinculação/em lote usam o modo \"digitar palavra de confirmação\" (`GlobalConfirm` + `useConfirmStore`)",
"## 高级功能": "## Funcionalidades avançadas",
"| 功能 | 说明 | 技术 |": "| Funcionalidade | Descrição | Tecnologia |",
"| 素材库 | 图片/视频上传管理、画廊预览、复制 URL | AssetController + Vue 画廊 |": "| Biblioteca de materiais | Gerenciamento de upload de imagens/vídeos, prévia em galeria, copiar URL | AssetController + galeria Vue |",
"| 预算预警 | 日预算消耗实时追踪、三段告警 (50/80/100%) | BudgetAlertService + 15min Cron |": "| Alerta de orçamento | Rastreamento em tempo real do consumo do orçamento diário, alertas em três níveis (50/80/100%) | BudgetAlertService + Cron de 15min |",
"| 投放日历 | 跨平台 Gantt 图、月/周视图、按平台着色 | CalendarService + Vue Gantt |": "| Calendário de veiculação | Gráfico Gantt entre plataformas, visões mensal/semanal, cores por plataforma | CalendarService + Gantt Vue |",
"| 跨平台归因 | 5 模型归因 (first/last/linear/time_decay/position_based)、30 天回溯 | AttributionEngine + ECharts |": "| Atribuição entre plataformas | Atribuição com 5 modelos (first/last/linear/time_decay/position_based), retrospectiva de 30 dias | AttributionEngine + ECharts |",
"## 高并发": "## Alta concorrência",
"| 优化 | 方案 | 文件 |": "| Otimização | Solução | Arquivo |",
"| 数据库读写分离 | 主库 `shared` + 只读副本 `read_replica`，SELECT 自动路由到副本 | `config/database.php` |": "| Separação de leitura/escrita do banco | Banco principal `shared` + réplica somente leitura `read_replica`, SELECT roteado automaticamente para a réplica | `config/database.php` |",
"| DB 连接池 | `PDO::ATTR_PERSISTENT` 持久连接 + 时区初始化预热 | `config/database.php` |": "| Pool de conexões do DB | Conexão persistente `PDO::ATTR_PERSISTENT` + pré-aquecimento com inicialização de fuso horário | `config/database.php` |",
"| Redis 连接池 | `persistent` 持久连接 + 读写分离 `readonly` 配置 | `config/redis.php` |": "| Pool de conexões Redis | Conexão persistente `persistent` + configuração `readonly` de separação leitura/escrita | `config/redis.php` |",
"| 三级缓存 | L1 进程内存 → L2 APCu 共享内存 → L3 Redis | `support/CacheService.php` |": "| Cache de três níveis | L1 memória do processo → L2 memória compartilhada APCu → L3 Redis | `support/CacheService.php` |",
"| 消息队列异步 | Redis List 4 通道 (sync/report/export/notification) | `support/AsyncJobService.php` |": "| Fila de mensagens assíncrona | Redis List com 4 canais (sync/report/export/notification) | `support/AsyncJobService.php` |",
"| Nginx 分级限流 | 30r/s + burst 20 + 20 并发连接 + keepalive 32 | `docker/nginx/admin.conf` |": "| Rate limit em níveis no Nginx | 30r/s + burst 20 + 20 conexões concorrentes + keepalive 32 | `docker/nginx/admin.conf` |",
"| 水平扩展 | upstream 多实例 + 故障转移 + sticky session | `docker/nginx/admin.conf` |": "| Escala horizontal | upstream com múltiplas instâncias + failover + sticky session | `docker/nginx/admin.conf` |",
"| CDN 加速 | 静态资源 `expires 30d` + `immutable` + `gzip_static` | `docker/nginx/admin.conf` |": "| Aceleração CDN | Recursos estáticos `expires 30d` + `immutable` + `gzip_static` | `docker/nginx/admin.conf` |",
"## 快速启动": "## Início rápido",
"### 一键 Web 安装（推荐）": "### Instalação Web com um clique (recomendado)",
"启动服务后浏览器访问 `/install` 进入安装向导：": "Após iniciar o serviço, acesse `/install` no navegador para entrar no assistente de instalação:",
"安装向导将在网页上引导你完成：": "O assistente de instalação o guiará na página:",
"1. **数据库连接** — 填写 MySQL 主机、端口、数据库名、用户名密码，支持连接测试": "1. **Conexão com o banco de dados** — preencha o host MySQL, porta, nome do banco, usuário e senha, com suporte a teste de conexão",
"2. **Redis 配置** — 填写 Redis 连接信息（可选）": "2. **Configuração Redis** — preencha as informações de conexão do Redis (opcional)",
"3. **管理员账户** — 设置后台登录用户名、密码、显示名称": "3. **Conta de administrador** — defina usuário, senha e nome de exibição do login do painel",
"4. **一键安装** — 自动建库、执行 `install.sql` 创建 28 张表并写入种子数据、更新管理员密码": "4. **Instalação com um clique** — cria o banco automaticamente, executa o `install.sql` para criar 28 tabelas e inserir dados de seed, atualiza a senha do administrador",
"安装完成后访问 `/` 进入管理后台，使用设置的用户名和密码登录。": "Após a instalação, acesse `/` para entrar no painel administrativo e faça login com o usuário e a senha definidos.",
"### Docker (推荐生产环境)": "### Docker (recomendado para produção)",
"### 本地开发": "### Desenvolvimento local",
"## 项目结构": "## Estrutura do projeto",
"## API 端点": "## Endpoints da API",
"> 全部 API 端点定义见 [docs/api.md](docs/api.md)（含请求/响应示例、错误码、限流策略）。": "> Todas as definições dos endpoints da API estão em [docs/api.md](docs/api.pt.md) (incluindo exemplos de requisição/resposta, códigos de erro e políticas de rate limit).",
"> hg/apidoc 在线文档: 启动服务后访问 `http://127.0.0.1:8788/apidoc`": "> Documentação online hg/apidoc: após iniciar o serviço, acesse `http://127.0.0.1:8788/apidoc`",
"## 数据库": "## Banco de dados",
"**命名规范**: 表前缀 `erik_`，主键 `BIGINT UNSIGNED PRIMARY KEY`（无自增，Snowflake ID），引擎 InnoDB，字符集 utf8mb4": "**Convenção de nomenclatura**: prefixo de tabela `erik_`, chave primária `BIGINT UNSIGNED PRIMARY KEY` (sem autoincremento, Snowflake ID), engine InnoDB, charset utf8mb4",
"| 分类 | 表名 | 用途 |": "| Categoria | Nome da tabela | Finalidade |",
"| 基础 | `erik_tenants` | 多租户 |": "| Base | `erik_tenants` | Multitenant |",
"| 账户 | `erik_platform_accounts`, `erik_auth_tokens` | OAuth 平台账户 |": "| Contas | `erik_platform_accounts`, `erik_auth_tokens` | Contas de plataforma OAuth |",
"| 投放 | `erik_campaigns`, `erik_ad_groups`, `erik_creatives` | 广告投放层级 |": "| Veiculação | `erik_campaigns`, `erik_ad_groups`, `erik_creatives` | Hierarquia de veiculação de anúncios |",
"| 报表 | `erik_report_metrics`, `erik_report_extras` | 统一报表指标 |": "| Relatórios | `erik_report_metrics`, `erik_report_extras` | Métricas unificadas de relatórios |",
"| 素材 | `erik_assets` | 创意素材库 |": "| Materiais | `erik_assets` | Biblioteca de materiais criativos |",
"| 定向 | `erik_targeting_templates` | 受众定向模板 |": "| Segmentação | `erik_targeting_templates` | Modelos de segmentação de público |",
"| 归因 | `erik_conversions`, `erik_attribution_results` | 转化追踪 + 归因结果 |": "| Atribuição | `erik_conversions`, `erik_attribution_results` | Rastreamento de conversões + resultados de atribuição |",
"| 出价 | `erik_bid_rules`, `erik_bid_logs` | 自动出价规则 + 历史 |": "| Lances | `erik_bid_rules`, `erik_bid_logs` | Regras de lance automático + histórico |",
"| 告警 | `erik_alert_rules`, `erik_alert_logs` | 告警监控 |": "| Alertas | `erik_alert_rules`, `erik_alert_logs` | Monitoramento de alertas |",
"| 通知 | `erik_notifications` | 站内通知 |": "| Notificações | `erik_notifications` | Notificações no sistema |",
"| 系统 | `erik_sync_errors`, `admin_users`, `admin_roles`, `admin_audit_logs` | 同步错误、RBAC、审计 |": "| Sistema | `erik_sync_errors`, `admin_users`, `admin_roles`, `admin_audit_logs` | Erros de sincronização, RBAC, auditoria |",
"## 定时任务": "## Tarefas agendadas",
"| 任务 | 频率 | 功能 |": "| Tarefa | Frequência | Função |",
"| TokenRefreshTask | 每 55 分钟 | 扫描过期 OAuth Token，自动刷新 |": "| TokenRefreshTask | A cada 55 minutos | Escaneia Tokens OAuth expirados e atualiza automaticamente |",
"| DataSyncTask | 每 10 分钟 | 拉取各平台计划+广告组+创意+报表，写入统一表，清除缓存 |": "| DataSyncTask | A cada 10 minutos | Busca planos + grupos de anúncios + criativos + relatórios de cada plataforma, grava em tabelas unificadas e limpa o cache |",
"| AlertCheckTask | 每 5 分钟 | 遍历启用告警规则，评估阈值，触发推送 |": "| AlertCheckTask | A cada 5 minutos | Percorre as regras de alerta habilitadas, avalia limites e dispara notificações |",
"| BidCheckTask | 每 10 分钟 | 遍历自动出价规则，查询指标，执行预算调整/启停 |": "| BidCheckTask | A cada 10 minutos | Percorre as regras de lance automático, consulta métricas e executa ajustes de orçamento/início-pausa |",
"| BudgetCheckTask | 每 15 分钟 | 遍历投放中计划，日预算消耗追踪、三段预警 (50/80/100%) |": "| BudgetCheckTask | A cada 15 minutos | Percorre os planos em veiculação, rastreia o consumo do orçamento diário com alertas em três níveis (50/80/100%) |",
"| RetrySyncTask | 每 3 分钟 | 重试失败的同步任务（最多3次，指数退避） |": "| RetrySyncTask | A cada 3 minutos | Repete tarefas de sincronização com falha (máximo de 3 vezes, backoff exponencial) |",
"## 测试": "## Testes",
"**覆盖范围**: 中间件 (Version/SQLGuard/SecurityHeaders) · 数据对象 (CampaignData/FieldMapping/Hashids) · 引擎 (ReportBuilder/AdapterRegistry) · 集成测试 (Auth/Health)": "**Cobertura**: middlewares (Version/SQLGuard/SecurityHeaders) · objetos de dados (CampaignData/FieldMapping/Hashids) · engines (ReportBuilder/AdapterRegistry) · testes de integração (Auth/Health)",
"**CI** (`.github/workflows/ci.yml`): 自动管线 — **PHP Syntax → PHPUnit → TypeScript → Docker Build**": "**CI** (`.github/workflows/ci.yml`): pipeline automático — **PHP Syntax → PHPUnit → TypeScript → Docker Build**",
"**CD** (`.github/workflows/deploy.yml`): 手动触发 — **Docker Buildx → 推送 GHCR (service/admin/admin-php) → 部署通知**": "**CD** (`.github/workflows/deploy.yml`): acionamento manual — **Docker Buildx → push para GHCR (service/admin/admin-php) → notificação de implantação**",
"`.github/dependabot.yml` 每周自动更新 Composer + npm + Docker 依赖。": "`.github/dependabot.yml` atualiza automaticamente as dependências Composer + npm + Docker toda semana.",
"`docs/skills/` — 11 个可复用项目技能：": "`docs/skills/` — 11 habilidades de projeto reutilizáveis:",
"| Skill | 说明 |": "| Skill | Descrição |",
"| `adapter-generator` | 生成新的广告平台适配器（14 方法模板） |": "| `adapter-generator` | Gera novos adaptadores de plataforma de publicidade (modelo de 14 métodos) |",
"| `migration-generator` | 生成 SQL 迁移文件（erik_ 前缀 + BIGINT PK） |": "| `migration-generator` | Gera arquivos de migração SQL (prefixo erik_ + BIGINT PK) |",
"| `erik-stack` | Erik Stack 8 包集成使用指南 |": "| `erik-stack` | Guia de integração dos 8 pacotes do Erik Stack |",
"| `admin-page-generator` | 生成 Vue3 管理后台页面 |": "| `admin-page-generator` | Gera páginas do painel administrativo Vue3 |",
"| `api-endpoint` | 添加 RESTful API 端点 |": "| `api-endpoint` | Adiciona endpoints RESTful de API |",
"| `tdd-workflow` | TDD 验证流程（测试→实现→语法→TypeScript→提交） |": "| `tdd-workflow` | Fluxo de validação TDD (teste→implementação→sintaxe→TypeScript→commit) |",
"| `security-middleware` | 添加安全中间件层（接口规范 + 注册 + 现有链参考） |": "| `security-middleware` | Adiciona camada de middleware de segurança (especificação da interface + registro + referência da cadeia existente) |",
"| `version-split` | Lite/Standard/Full 三版本拆分（操作步骤 + 配置更新） |": "| `version-split` | Divisão nas três versões Lite/Standard/Full (etapas + atualização de configuração) |",
"| `cache-strategy` | 三级缓存策略（L1内存/L2 APCu/L3 Redis + TTL建议） |": "| `cache-strategy` | Estratégia de cache de três níveis (L1 memória/L2 APCu/L3 Redis + recomendações de TTL) |",
"| `attribution-setup` | 跨平台归因引擎（5模型 + API调用 + 数据准备） |": "| `attribution-setup` | Engine de atribuição entre plataformas (5 modelos + chamadas de API + preparação de dados) |",
"| `high-concurrency` | 高并发 8 项优化（读写分离/连接池/消息队列/水平扩展/CDN） |": "| `high-concurrency` | 8 otimizações de alta concorrência (separação leitura/escrita/pool de conexões/fila de mensagens/escala horizontal/CDN) |",
"## 开源不易，欢迎支持": "## Open source não é fácil, apoie-nos",
"| 微信 | 支付宝 |": "| WeChat | Alipay |",
"| ![微信](./docs/weixinpay.png \"微信\") | ![支付宝](./docs/alipay.png \"支付宝\") |": "| ![WeChat](./docs/weixinpay.png \"WeChat\") | ![Alipay](./docs/alipay.png \"Alipay\") |",
"### 全球转账打赏 (Global Transfer Donation)": "### Doação por transferência global (Global Transfer Donation)",
"**收款人信息 (Beneficiary)**": "**Informações do beneficiário (Beneficiary)**",
"| 字段 | 值 |": "| Campo | Valor |",
"| 收款人姓名 (Name) | WANG KEXUN |": "| Nome do beneficiário (Name) | WANG KEXUN |",
"| 收款账户号码 (Account No.) | 881015918251 |": "| Número da conta do beneficiário (Account No.) | 881015918251 |",
"**收款银行 (Receiving Bank) — ZA Bank**": "**Banco receptor (Receiving Bank) — ZA Bank**",
"| 银行名称 (Bank Name) | ZA Bank Limited |": "| Nome do banco (Bank Name) | ZA Bank Limited |",
"| 银行编号 (Bank Code) | 387 |": "| Código do banco (Bank Code) | 387 |",
"| 银行地址 (Bank Address) | Core F, Cyberport 3, 100 Cyberport Road, Hong Kong |": "| Endereço do banco (Bank Address) | Core F, Cyberport 3, 100 Cyberport Road, Hong Kong |",
"> **跨境汇款代理银行（如需，Correspondent Bank）**：此为代理（中转）银行信息，非收款银行信息，请向汇款银行查询是否需要提供。": "> **Banco correspondente para remessas transfronteiriças (se necessário, Correspondent Bank)**: estas são informações do banco intermediário (agente), não do banco receptor; consulte o banco remetente para saber se é necessário fornecê-las.",
"> - **港元、人民币及美元**：Citibank N.A. Hong Kong — SWIFT `CITIHKHXXXX` · 银行编号 006 · Hong Kong Branch（分行编号 391）· Citibank Tower, Citibank Plaza, 3 Garden Road, Central, Hong Kong": "> - **Dólar de Hong Kong, RMB e dólar americano**: Citibank N.A. Hong Kong — SWIFT `CITIHKHXXXX` · código do banco 006 · Hong Kong Branch (código da filial 391) · Citibank Tower, Citibank Plaza, 3 Garden Road, Central, Hong Kong",
"> - **其他币种**：THE BANK OF NEW YORK MELLON — SWIFT `IRVTUS3NXXX` · 240 GREENWICH STREET, NEW YORK, United States": "> - **Outras moedas**: THE BANK OF NEW YORK MELLON — SWIFT `IRVTUS3NXXX` · 240 GREENWICH STREET, NEW YORK, United States",
"## 许可证": "## Licença",
},
"docs/index.md": {
"# Docs 目录结构": "# Estrutura do diretório Docs",
"## 语言版本": "## Versões de idioma",
"每篇文档均提供 12 种语言版本（`<name>.<lang>.md`），图表为 `<name>.<lang>.svg`：": "Cada documento é fornecido em 12 versões de idioma (`<name>.<lang>.md`), e os diagramas como `<name>.<lang>.svg`:",
"| 语言 | 代码 | 语言 | 代码 |": "| Idioma | Código | Idioma | Código |",
"| 中文 | zh | Português | pt |": "| Chinês | zh | Português | pt |",
"| Français | fr | 日本語 | ja |": "| Francês | fr | Japonês | ja |",
"## 打赏支持": "## Apoio com doações",
"| 微信 | 支付宝 |": "| WeChat | Alipay |",
"| ![微信](weixinpay.png \"微信\") | ![支付宝](alipay.png \"支付宝\") |": "| ![WeChat](weixinpay.png \"WeChat\") | ![Alipay](alipay.png \"Alipay\") |",
"### 全球转账打赏 (Global Transfer Donation)": "### Doação por transferência global (Global Transfer Donation)",
"**收款人信息 (Beneficiary)**": "**Informações do beneficiário (Beneficiary)**",
"| 字段 | 值 |": "| Campo | Valor |",
"| 收款人姓名 (Name) | WANG KEXUN |": "| Nome do beneficiário (Name) | WANG KEXUN |",
"| 收款账户号码 (Account No.) | 881015918251 |": "| Número da conta do beneficiário (Account No.) | 881015918251 |",
"**收款银行 (Receiving Bank) — ZA Bank**": "**Banco receptor (Receiving Bank) — ZA Bank**",
"| 银行名称 (Bank Name) | ZA Bank Limited |": "| Nome do banco (Bank Name) | ZA Bank Limited |",
"| 银行编号 (Bank Code) | 387 |": "| Código do banco (Bank Code) | 387 |",
"| 银行地址 (Bank Address) | Core F, Cyberport 3, 100 Cyberport Road, Hong Kong |": "| Endereço do banco (Bank Address) | Core F, Cyberport 3, 100 Cyberport Road, Hong Kong |",
"> **跨境汇款代理银行（如需，Correspondent Bank）**：此为代理（中转）银行信息，非收款银行信息，请向汇款银行查询是否需要提供。": "> **Banco correspondente para remessas transfronteiriças (se necessário, Correspondent Bank)**: estas são informações do banco intermediário (agente), não do banco receptor; consulte o banco remetente para saber se é necessário fornecê-las.",
"> - **港元、人民币及美元**：Citibank N.A. Hong Kong — SWIFT `CITIHKHXXXX` · 银行编号 006 · Hong Kong Branch（分行编号 391）· Citibank Tower, Citibank Plaza, 3 Garden Road, Central, Hong Kong": "> - **Dólar de Hong Kong, RMB e dólar americano**: Citibank N.A. Hong Kong — SWIFT `CITIHKHXXXX` · código do banco 006 · Hong Kong Branch (código da filial 391) · Citibank Tower, Citibank Plaza, 3 Garden Road, Central, Hong Kong",
"> - **其他币种**：THE BANK OF NEW YORK MELLON — SWIFT `IRVTUS3NXXX` · 240 GREENWICH STREET, NEW YORK, United States": "> - **Outras moedas**: THE BANK OF NEW YORK MELLON — SWIFT `IRVTUS3NXXX` · 240 GREENWICH STREET, NEW YORK, United States",
},
}
