# -*- coding: utf-8 -*-
# 葡萄牙语翻译词典（phase1 + phase2 plans）
TRANS = {
"docs/superpowers/plans/2026-05-14-phase1-foundation.md": {
"# Phase 1: 基础骨架 Implementation Plan": "# Phase 1: Plano de implementação do esqueleto base",
"**Goal:** 搭建 webman v2 服务端 + webman-admin v2 管理后台骨架，实现多租户、认证权限、账户管理、OAuth 流程框架，并以巨量引擎作为第一个平台跑通全链路。": "**Objetivo:** montar o esqueleto do backend webman v2 + painel administrativo webman-admin v2, implementando multitenant, autenticação e permissões, gerenciamento de contas e o framework do fluxo OAuth, usando a Juliang (Ocean Engine) como primeira plataforma para percorrer todo o caminho.",
"**Architecture:** webman v2 插件化架构，service/plugin/ 下按职责拆分 ads-tenant、ads-account、ads-platform、ads-api 四个插件；管理后台使用 Vue3+TS+Element Plus，通过 Pinia 管理状态，Axios 对接后端 API。": "**Arquitetura:** arquitetura de plugins do webman v2, dividindo em `service/plugin/` quatro plugins por responsabilidade: ads-tenant, ads-account, ads-platform e ads-api; o painel administrativo usa Vue3+TS+Element Plus, com Pinia para gerenciar estado e Axios para se conectar à API do backend.",
"## 文件结构": "## Estrutura de arquivos",
"### Task 1: 初始化 webman v2 服务端项目": "### Task 1: inicializar o projeto de backend webman v2",
"- [x] **Step 1: 创建 composer.json 并安装依赖**": "- [x] **Step 1: criar composer.json e instalar as dependências**",
"- [x] **Step 2: 创建 .env 环境配置**": "- [x] **Step 2: criar a configuração de ambiente .env**",
"- [x] **Step 3: 创建 config/app.php**": "- [x] **Step 3: criar config/app.php**",
"- [x] **Step 4: 创建 config/database.php 支持动态数据源**": "- [x] **Step 4: criar config/database.php com suporte a fontes de dados dinâmicas**",
"- [x] **Step 5: 创建 config/redis.php**": "- [x] **Step 5: criar config/redis.php**",
"- [x] **Step 6: 创建 config/middleware.php**": "- [x] **Step 6: criar config/middleware.php**",
"- [x] **Step 7: 创建 support/Response.php 统一响应**": "- [x] **Step 7: criar support/Response.php com resposta unificada**",
"- [x] **Step 8: 创建 service/start.php**": "- [x] **Step 8: criar service/start.php**",
"- [x] **Step 9: 验证项目启动**": "- [x] **Step 9: validar a inicialização do projeto**",
"Expected: webman v2 启动成功，监听 8787 端口": "Esperado: webman v2 iniciado com sucesso, escutando na porta 8787",
"- [x] **Step 10: 提交**": "- [x] **Step 10: commit**",
"### Task 2: 创建 ads-tenant 多租户插件": "### Task 2: criar o plugin multitenant ads-tenant",
"- [x] **Step 1: 创建 plugin.php**": "- [x] **Step 1: criar plugin.php**",
"- [x] **Step 2: 创建 database.php 数据源路由**": "- [x] **Step 2: criar database.php com roteamento de fontes de dados**",
"- [x] **Step 3: 创建 Tenant 模型**": "- [x] **Step 3: criar o modelo Tenant**",
"- [x] **Step 4: 创建 TenantIdentify 中间件**": "- [x] **Step 4: criar o middleware TenantIdentify**",
"- [x] **Step 5: 创建迁移 SQL**": "- [x] **Step 5: criar o SQL de migração**",
"- [x] **Step 6: 提交**": "- [x] **Step 6: commit**",
"### Task 3: 创建 ads-platform 适配器核心": "### Task 3: criar o núcleo de adaptadores ads-platform",
"- [x] **Step 1: 创建 PlatformAdapter 接口**": "- [x] **Step 1: criar a interface PlatformAdapter**",
"- [x] **Step 2: 创建 CampaignData**": "- [x] **Step 2: criar CampaignData**",
"- [x] **Step 3: 创建 ReportRequest**": "- [x] **Step 3: criar ReportRequest**",
"- [x] **Step 4: 创建 FieldMapping 字段映射引擎**": "- [x] **Step 4: criar o engine de mapeamento de campos FieldMapping**",
"- [x] **Step 5: 创建 AdapterRegistry**": "- [x] **Step 5: criar AdapterRegistry**",
"- [x] **Step 6: 创建巨量引擎适配器（字段映射 + 接口骨架）**": "- [x] **Step 6: criar o adaptador da Juliang (Ocean Engine) (mapeamento de campos + esqueleto da interface)**",
"- [x] **Step 7: 创建 plugin.php**": "- [x] **Step 7: criar plugin.php**",
"- [x] **Step 8: 创建迁移 SQL（campaigns, ad_groups, creatives, report_metrics, report_extras）**": "- [x] **Step 8: criar o SQL de migração (campaigns, ad_groups, creatives, report_metrics, report_extras)**",
"- [x] **Step 9: 注册巨量引擎适配器到 AdapterRegistry**": "- [x] **Step 9: registrar o adaptador da Juliang no AdapterRegistry**",
"- [x] **Step 10: 提交**": "- [x] **Step 10: commit**",
"### Task 4: 创建 ads-account 账户管理插件": "### Task 4: criar o plugin de gerenciamento de contas ads-account",
"- [x] **Step 1: 创建 plugin.php**": "- [x] **Step 1: criar plugin.php**",
"- [x] **Step 2: 创建 PlatformAccount 模型**": "- [x] **Step 2: criar o modelo PlatformAccount**",
"- [x] **Step 3: 创建 AuthToken 模型（用于 OAuth 流程中的 state 存储）**": "- [x] **Step 3: criar o modelo AuthToken (para armazenamento do state no fluxo OAuth)**",
"- [x] **Step 4: 创建 OAuthService**": "- [x] **Step 4: criar OAuthService**",
"- [x] **Step 5: 创建迁移 SQL**": "- [x] **Step 5: criar o SQL de migração**",
"- [x] **Step 6: 提交**": "- [x] **Step 6: commit**",
"### Task 5: 创建 ads-api 插件（RESTful API + JWT 认证）": "### Task 5: criar o plugin ads-api (API RESTful + autenticação JWT)",
"- [x] **Step 1: 创建 plugin.php**": "- [x] **Step 1: criar plugin.php**",
"- [x] **Step 2: 创建 JWT AuthMiddleware**": "- [x] **Step 2: criar o AuthMiddleware JWT**",
"- [x] **Step 3: 创建 AuthController**": "- [x] **Step 3: criar AuthController**",
"- [x] **Step 4: 创建 PlatformController**": "- [x] **Step 4: criar PlatformController**",
"- [x] **Step 5: 创建 AccountController**": "- [x] **Step 5: criar AccountController**",
"- [x] **Step 6: 创建 CampaignController**": "- [x] **Step 6: criar CampaignController**",
"- [x] **Step 7: 创建 DashboardController**": "- [x] **Step 7: criar DashboardController**",
"- [x] **Step 8: 创建路由配置 route.php**": "- [x] **Step 8: criar a configuração de rotas route.php**",
"- [x] **Step 9: 提交**": "- [x] **Step 9: commit**",
"### Task 6: 初始化 webman-admin v2 管理后台项目": "### Task 6: inicializar o projeto do painel administrativo webman-admin v2",
"- [x] **Step 1: 创建 package.json**": "- [x] **Step 1: criar package.json**",
"- [x] **Step 2: 创建 vite.config.ts**": "- [x] **Step 2: criar vite.config.ts**",
"- [x] **Step 3: 创建 tsconfig.json**": "- [x] **Step 3: criar tsconfig.json**",
"- [x] **Step 4: 创建 index.html**": "- [x] **Step 4: criar index.html**",
"- [x] **Step 5: 创建 src/main.ts**": "- [x] **Step 5: criar src/main.ts**",
"- [x] **Step 6: 创建 src/App.vue**": "- [x] **Step 6: criar src/App.vue**",
"- [x] **Step 7: 创建 src/router/index.ts**": "- [x] **Step 7: criar src/router/index.ts**",
"- [x] **Step 8: 创建 src/api/index.ts（Axios 封装）**": "- [x] **Step 8: criar src/api/index.ts (encapsulamento Axios)**",
"- [x] **Step 9: 安装依赖并验证**": "- [x] **Step 9: instalar as dependências e validar**",
"Expected: Vite 开发服务器启动在 5173 端口": "Esperado: Vite dev server iniciado na porta 5173",
"- [x] **Step 10: 提交**": "- [x] **Step 10: commit**",
"### Task 7: 管理后台布局 & 登录页面": "### Task 7: layout do painel administrativo & página de login",
"- [x] **Step 1: 创建 auth store**": "- [x] **Step 1: criar a auth store**",
"- [x] **Step 2: 创建 auth API**": "- [x] **Step 2: criar a auth API**",
"- [x] **Step 3: 创建 LoginPage.vue**": "- [x] **Step 3: criar LoginPage.vue**",
"- [x] **Step 4: 创建 SideNav.vue**": "- [x] **Step 4: criar SideNav.vue**",
"- [x] **Step 5: 创建 TopBar.vue**": "- [x] **Step 5: criar TopBar.vue**",
"- [x] **Step 6: 创建 AppLayout.vue**": "- [x] **Step 6: criar AppLayout.vue**",
"- [x] **Step 7: 提交**": "- [x] **Step 7: commit**",
"### Task 8: 管理后台核心页面": "### Task 8: páginas principais do painel administrativo",
"- [x] **Step 1: 创建工具函数 format.ts**": "- [x] **Step 1: criar a função utilitária format.ts**",
"- [x] **Step 2: 创建 MetricCard.vue**": "- [x] **Step 2: criar MetricCard.vue**",
"- [x] **Step 3: 创建 PlatformBadge.vue**": "- [x] **Step 3: criar PlatformBadge.vue**",
"- [x] **Step 4: 创建 DashboardPage.vue**": "- [x] **Step 4: criar DashboardPage.vue**",
"- [x] **Step 5: 创建 AccountList.vue**": "- [x] **Step 5: criar AccountList.vue**",
"- [x] **Step 6: 创建 AccountBind.vue**": "- [x] **Step 6: criar AccountBind.vue**",
"- [x] **Step 7: 创建 CampaignList.vue**": "- [x] **Step 7: criar CampaignList.vue**",
"- [x] **Step 8: 创建 API 封装文件**": "- [x] **Step 8: criar os arquivos de encapsulamento da API**",
"- [x] **Step 9: 验证管理后台功能**": "- [x] **Step 9: validar as funcionalidades do painel administrativo**",
"Config: 确保 vite proxy 指向 webman 服务端 8787 端口": "Config: garantir que o proxy do vite aponte para o backend webman na porta 8787",
"Check: 登录 → 仪表盘 → 账户管理 → 创建计划 → 启停计划": "Check: login → dashboard → gerenciamento de contas → criar plano → iniciar/pausar plano",
"- [x] **Step 10: 提交**": "- [x] **Step 10: commit**",
"### Task 9: 配置引导 & 项目启动验证": "### Task 9: orientação de configuração & validação da inicialização do projeto",
"- Create: `service/start.php` (如果有则修改)": "- Create: `service/start.php` (modificar se já existir)",
"- [x] **Step 1: 在 service/start.php 中添加插件加载和数据库初始化**": "- [x] **Step 1: adicionar o carregamento de plugins e a inicialização do banco de dados em service/start.php**",
"- [x] **Step 2: 运行数据库迁移**": "- [x] **Step 2: executar as migrações do banco de dados**",
"- [x] **Step 3: 启动服务端并验证 API**": "- [x] **Step 3: iniciar o backend e validar a API**",
"Expected: `{\"code\":0,\"data\":[{\"code\":\"juliang\",\"name\":\"巨量引擎\",\"capabilities\":[\"report\",\"campaign\",\"creative\",\"oauth\"]}]}`": "Esperado: `{\"code\":0,\"data\":[{\"code\":\"juliang\",\"name\":\"Juliang (Ocean Engine)\",\"capabilities\":[\"report\",\"campaign\",\"creative\",\"oauth\"]}]}`",
"- [x] **Step 4: 启动管理后台并验证联调**": "- [x] **Step 4: iniciar o painel administrativo e validar a integração**",
"1. 浏览器打开 `http://localhost:5173`": "1. Abrir `http://localhost:5173` no navegador",
"2. 登录 `admin / admin123`": "2. Fazer login com `admin / admin123`",
"3. 查看仪表盘（空数据）": "3. Visualizar o dashboard (dados vazios)",
"4. 进入账户管理 → 绑定账户（需巨量引擎正式 AppId）": "4. Entrar em gerenciamento de contas → vincular conta (requer AppId oficial da Juliang)",
"5. 创建测试广告计划": "5. Criar um plano de anúncios de teste",
"- [x] **Step 5: 提交最终状态**": "- [x] **Step 5: commitar o estado final**",
"## 验收标准": "## Critérios de aceitação",
"Phase 1 完成后应达到以下状态：": "Após a conclusão do Phase 1, o projeto deve atingir o seguinte estado:",
"1. ✅ webman v2 服务端可启动，MySQL、Redis 连接正常": "1. ✅ O backend webman v2 inicia corretamente, com conexões MySQL e Redis funcionando",
"2. ✅ 多租户表 `tenants` 建好，TenantIdentify 中间件可用": "2. ✅ A tabela multitenant `tenants` criada e o middleware TenantIdentify funcional",
"3. ✅ 平台适配器接口 `PlatformAdapter` 定义完整，巨量引擎适配器实现全部方法": "3. ✅ A interface `PlatformAdapter` totalmente definida, com o adaptador da Juliang implementando todos os métodos",
"4. ✅ OAuth 授权流程完整：获取授权URL → 回调处理 → Token 存储 → 账户绑定": "4. ✅ Fluxo de autorização OAuth completo: obter URL de autorização → processar callback → armazenar Token → vincular conta",
"5. ✅ 统一投放表 `campaigns/ad_groups/creatives` 和报表表 `report_metrics/report_extras` 建好": "5. ✅ Tabelas unificadas de veiculação `campaigns/ad_groups/creatives` e de relatórios `report_metrics/report_extras` criadas",
"6. ✅ RESTful API 可认证访问：`POST /auth/login` → 获得 Token → 调用其他接口": "6. ✅ A API RESTful acessível com autenticação: `POST /auth/login` → obter Token → chamar outras interfaces",
"7. ✅ 管理后台可登录，仪表盘/账户管理/计划管理页面可用": "7. ✅ O painel administrativo permite login, com as páginas de dashboard/gerenciamento de contas/gerenciamento de planos funcionais",
"8. ✅ 管理后台可创建广告计划并同步到巨量引擎平台": "8. ✅ O painel administrativo pode criar planos de anúncios e sincronizá-los com a plataforma Juliang",
},
"docs/superpowers/plans/2026-05-15-phase2-adapters-reports.md": {
"# Phase 2: 广告平台扩展 + 报表引擎 Implementation Plan": "# Phase 2: Plano de implementação de expansão de plataformas de anúncios + engine de relatórios",
"**Goal:** 新增百度营销和淘宝广告适配器，实现真正数据同步调度，增强报表引擎支持自定义多维度查询。": "**Objetivo:** adicionar os adaptadores de Baidu Marketing e Taobao Ads, implementar o agendamento real de sincronização de dados e aprimorar o engine de relatórios para suportar consultas personalizadas de múltiplas dimensões.",
"**Architecture:** 每个广告平台实现 PlatformAdapter 接口，通过 AdapterRegistry 统一注册。数据同步使用 webman/crontab 定时调度，同步过程中将平台原生数据经 FieldMapping 转成统一格式写入 report_metrics 表。报表引擎在现有 DashboardController 基础上增加 CampaignController 中的自定义查询能力。": "**Arquitetura:** cada plataforma de anúncios implementa a interface PlatformAdapter, registrada de forma unificada via AdapterRegistry. A sincronização de dados usa o agendamento webman/crontab; durante a sincronização, os dados nativos da plataforma são convertidos para o formato unificado via FieldMapping e gravados na tabela report_metrics. O engine de relatórios adiciona a capacidade de consulta personalizada no CampaignController, além do DashboardController existente.",
"**Phase 1 已有基础:**": "**Base existente do Phase 1:**",
"- PlatformAdapter 接口、AdapterRegistry、FieldMapping 全部就绪": "- Interface PlatformAdapter, AdapterRegistry e FieldMapping totalmente prontos",
"- 巨量引擎适配器已实现完整链路（OAuth → 同步 → 投放操作）": "- O adaptador da Juliang já implementa o caminho completo (OAuth → sincronização → operações de veiculação)",
"- report_metrics 表已建好，DashboardController::summary() 已有按日期/平台聚合能力": "- A tabela report_metrics criada, e DashboardController::summary() já tem capacidade de agregação por data/plataforma",
"- campaigns 表已建好，CampaignController 已有完整 CRUD": "- A tabela campaigns criada, e CampaignController já tem CRUD completo",
"- OAuthService 通用授权流程已就绪": "- O fluxo de autorização genérico do OAuthService pronto",
"## 文件结构（Phase 2 新增/修改）": "## Estrutura de arquivos (novos/modificados no Phase 2)",
"### Task 10: 创建百度营销适配器": "### Task 10: criar o adaptador de Baidu Marketing",
"百度营销 API 核心对接：": "Integração central com a API do Baidu Marketing:",
"- OAuth 授权地址：`https://u.baidu.com/oauth/authorize`": "- URL de autorização OAuth: `https://u.baidu.com/oauth/authorize`",
"- Token 交换：`https://u.baidu.com/oauth/token`": "- Troca de Token: `https://u.baidu.com/oauth/token`",
"- 广告计划查询：`/json/sms/service/CampaignService/getCampaign`": "- Consulta de planos de anúncios: `/json/sms/service/CampaignService/getCampaign`",
"- 报表查询：`/json/sms/service/ReportService/getProfessionalReportId` + `getReportData`": "- Consulta de relatórios: `/json/sms/service/ReportService/getProfessionalReportId` + `getReportData`",
"#### Step 1: 创建 Baidu.php 适配器": "#### Step 1: criar o adaptador Baidu.php",
"#### Step 2: 注册百度适配器": "#### Step 2: registrar o adaptador Baidu",
"#### Step 3: 提交": "#### Step 3: commit",
"### Task 11: 创建淘宝广告适配器": "### Task 11: criar o adaptador de Taobao Ads",
"淘宝广告（阿里妈妈）API 核心对接：": "Integração central com a API do Taobao Ads (Alimama):",
"- OAuth 授权：淘宝开放平台 OAuth 2.0": "- Autorização OAuth: OAuth 2.0 da plataforma aberta do Taobao",
"- API 端点：`https://api.taobao.com/router/rest`": "- Endpoint da API: `https://api.taobao.com/router/rest`",
"- 广告计划：`alimama.campaign.get`": "- Planos de anúncios: `alimama.campaign.get`",
"- 报表：`alimama.report.get`": "- Relatórios: `alimama.report.get`",
"#### Step 1: 创建 Taobao.php": "#### Step 1: criar Taobao.php",
"#### Step 2: 注册淘宝适配器": "#### Step 2: registrar o adaptador Taobao",
"#### Step 3: 提交": "#### Step 3: commit",
"### Task 12: 创建数据同步任务 + 报表引擎增强": "### Task 12: criar a tarefa de sincronização de dados + aprimorar o engine de relatórios",
"#### Step 1: 创建 ads-task 插件": "#### Step 1: criar o plugin ads-task",
"#### Step 2: 创建 TokenRefreshTask": "#### Step 2: criar TokenRefreshTask",
"#### Step 3: 创建 DataSyncTask": "#### Step 3: criar DataSyncTask",
"#### Step 4: 创建 cron.php 定时任务配置": "#### Step 4: criar a configuração de tarefas agendadas cron.php",
"#### Step 5: 创建 ads-report 插件 + ReportBuilder": "#### Step 5: criar o plugin ads-report + ReportBuilder",
"#### Step 6: 创建 ReportController": "#### Step 6: criar ReportController",
"#### Step 7: 增加报表路由": "#### Step 7: adicionar as rotas de relatórios",
"在 `route.php` 认证组中添加:": "Adicionar no grupo autenticado de `route.php`:",
"#### Step 8: 提交": "#### Step 8: commit",
"## 验收标准": "## Critérios de aceitação",
"1. ✅ 百度营销适配器实现全部 PlatformAdapter 方法": "1. ✅ O adaptador de Baidu Marketing implementa todos os métodos do PlatformAdapter",
"2. ✅ 淘宝广告适配器实现全部 PlatformAdapter 方法（含淘宝签名算法）": "2. ✅ O adaptador de Taobao Ads implementa todos os métodos do PlatformAdapter (incluindo o algoritmo de assinatura do Taobao)",
"3. ✅ OAuth 回调处理通过 AdapterRegistry 统一分流": "3. ✅ O tratamento do callback OAuth é distribuído de forma unificada via AdapterRegistry",
"4. ✅ 百度/淘宝适配器在 bootstrap.php 中注册": "4. ✅ Os adaptadores Baidu/Taobao registrados em bootstrap.php",
"5. ✅ TokenRefreshTask 每 55 分钟扫描过期 Token 并刷新": "5. ✅ TokenRefreshTask escaneia Tokens expirados a cada 55 minutos e os atualiza",
"6. ✅ DataSyncTask 每 10 分钟拉取各平台投放数据和报表": "6. ✅ DataSyncTask busca os dados de veiculação e relatórios de cada plataforma a cada 10 minutos",
"7. ✅ 报表自定义查询 API 支持多维度（platform/date/campaign）和多指标组合": "7. ✅ A API de consulta personalizada de relatórios suporta múltiplas dimensões (platform/date/campaign) e combinações de múltiplas métricas",
"8. ✅ 同步数据正确写入 report_metrics 表": "8. ✅ Os dados sincronizados são gravados corretamente na tabela report_metrics",
},
}
