# -*- coding: utf-8 -*-
# 葡萄牙语翻译词典（design.md spec）
TRANS = {
"docs/superpowers/specs/design.md": {
"# 多平台广告管理系统设计": "# Design do sistema de gerenciamento de publicidade multiplataforma",
"## 概述": "## Visão geral",
"对接 **29 个广告平台** 的统一广告管理平台，覆盖国内外主流广告厂商，支持广告投放管理、跨平台数据报表、实时告警监控。": "Plataforma unificada de gerenciamento de publicidade integrando **29 plataformas de anúncios**, cobrindo os principais fornecedores de publicidade nacionais e internacionais, com suporte a gerenciamento de veiculação, relatórios de dados entre plataformas e monitoramento de alertas em tempo real.",
"- **service** — 用户端业务服务，webman v2 (PHP 8.2+)，监听 :8788": "- **service** — serviço de negócio do usuário, webman v2 (PHP 8.2+), escutando em :8788",
"- **admin** — 独立管理后台，webman-admin v2 (PHP 后端 :8789 + Vue 3 SPA)": "- **admin** — painel administrativo independente, webman-admin v2 (backend PHP :8789 + Vue 3 SPA)",
"- **apps** — 客户端 App，Flutter (iOS/Android/Web PC) + HarmonyOS (ArkTS)": "- **apps** — apps clientes, Flutter (iOS/Android/Web PC) + HarmonyOS (ArkTS)",
"- **基础设施**: Docker + Nginx + MySQL 8.0 + Redis 7 + Elasticsearch": "- **Infraestrutura**: Docker + Nginx + MySQL 8.0 + Redis 7 + Elasticsearch",
"业务场景覆盖自用投放、SaaS 多租户、代运营三种模式。": "Os cenários de negócio cobrem três modos: veiculação para uso próprio, SaaS multitenant e operação terceirizada.",
"### 通信架构": "### Arquitetura de comunicação",
"## 总体架构": "## Arquitetura geral",
"### 系统架构图": "### Diagrama de arquitetura do sistema",
"## 一、服务端模块拆解": "## 1. Decomposição dos módulos do backend",
"webman v2 插件化架构，`service/plugin/` 下 7 个插件：": "Arquitetura de plugins do webman v2, com 7 plugins em `service/plugin/`:",
"## 二、平台适配器": "## 2. Adaptadores de plataforma",
"### 已适配平台 (29)": "### Plataformas adaptadas (29)",
"| 地区 | # | 平台 | 适配器类 | 认证 | 金额 | 报表 |": "| Região | # | Plataforma | Classe do adaptador | Autenticação | Valor | Relatórios |",
"| 国内 | 1 | 巨量引擎 | Juliang | OAuth2 Access-Token | 元→分 | 同步分页 |": "| Nacionais | 1 | Juliang (Ocean Engine) | Juliang | OAuth2 Access-Token | yuan→centavos | Paginação síncrona |",
"| 国内 | 2 | 百度营销 | Baidu | OAuth2 + 信封签名 | 元→分 | 异步轮询 |": "| Nacionais | 2 | Baidu Marketing | Baidu | OAuth2 + assinatura de envelope | yuan→centavos | Polling assíncrono |",
"| 国内 | 3 | 淘宝/阿里妈妈 | Taobao | OAuth2 + MD5签名 | 元→分 | 同步分页 |": "| Nacionais | 3 | Taobao/Alimama | Taobao | OAuth2 + assinatura MD5 | yuan→centavos | Paginação síncrona |",
"| 国内 | 4 | 腾讯广告 | Tencent | OAuth2 + nonce | 分原生 | 同步分页 |": "| Nacionais | 4 | Tencent Ads | Tencent | OAuth2 + nonce | centavos nativos | Paginação síncrona |",
"| 国内 | 5 | 快手磁力引擎 | Kuaishou | OAuth2 URL参数 | 元→分 | 同步分页 |": "| Nacionais | 5 | Kuaishou Magnet Engine | Kuaishou | OAuth2 parâmetro de URL | yuan→centavos | Paginação síncrona |",
"| 国内 | 6 | 小红书蒲公英 | Xiaohongshu | OAuth2 Bearer | 分原生 | 同步分页 |": "| Nacionais | 6 | Xiaohongshu Dandelion | Xiaohongshu | OAuth2 Bearer | centavos nativos | Paginação síncrona |",
"| 国内 | 7 | 微博粉丝通 | Weibo | OAuth2 Bearer | 分原生 | 同步分页 |": "| Nacionais | 7 | Weibo Fans Tong | Weibo | OAuth2 Bearer | centavos nativos | Paginação síncrona |",
"| 国内 | 8 | B站花火 | Bilibili | OAuth2 Bearer | 分原生 | 同步分页 |": "| Nacionais | 8 | Bilibili Huahuo | Bilibili | OAuth2 Bearer | centavos nativos | Paginação síncrona |",
"| 国内 | 9 | 优酷广告 | Youku | OAuth2 + MD5签名 | 元→分 | 同步分页 |": "| Nacionais | 9 | Youku Ads | Youku | OAuth2 + assinatura MD5 | yuan→centavos | Paginação síncrona |",
"| 国内 | 10 | 美团广告 | Meituan | OAuth2 Bearer | 分原生 | 同步分页 |": "| Nacionais | 10 | Meituan Ads | Meituan | OAuth2 Bearer | centavos nativos | Paginação síncrona |",
"| 国内 | 11 | 知乎广告 | Zhihu | OAuth2 Bearer | 元→分 | 同步分页 |": "| Nacionais | 11 | Zhihu Ads | Zhihu | OAuth2 Bearer | yuan→centavos | Paginação síncrona |",
"| 国内 | 12 | 360推广 | Qihoo360 | API Key + Sign | 元→分 | 同步分页 |": "| Nacionais | 12 | Qihoo 360 Promo | Qihoo360 | API Key + Sign | yuan→centavos | Paginação síncrona |",
"| 国内 | 13 | 搜狗推广 | Sogou | API Key + Sign | 元→分 | 同步分页 |": "| Nacionais | 13 | Sogou Promo | Sogou | API Key + Sign | yuan→centavos | Paginação síncrona |",
"| 国内 | 14 | 友盟 | Umeng | API Key + MD5 | 元→分 | 同步分页 |": "| Nacionais | 14 | Umeng | Umeng | API Key + MD5 | yuan→centavos | Paginação síncrona |",
"| 国内 | 15 | 京东京准通 | Jingdong | OAuth2 + MD5 | 元→分 | 同步分页 |": "| Nacionais | 15 | Jingdong Jingzhuntong | Jingdong | OAuth2 + MD5 | yuan→centavos | Paginação síncrona |",
"| 国内 | 16 | 拼多多广告 | Pinduoduo | OAuth2 + 自定义Sign | 分原生 | 同步分页 |": "| Nacionais | 16 | Pinduoduo Ads | Pinduoduo | OAuth2 + Sign personalizado | centavos nativos | Paginação síncrona |",
"| 国际 | 17 | Google Ads | Google | OAuth2 + GAQL | 微元→分 | pageToken |": "| Internacionais | 17 | Google Ads | Google | OAuth2 + GAQL | microyuan→centavos | pageToken |",
"| 国际 | 18 | YouTube Ads | Youtube | OAuth2 + GAQL | 微元→分 | pageToken |": "| Internacionais | 18 | YouTube Ads | Youtube | OAuth2 + GAQL | microyuan→centavos | pageToken |",
"| 国际 | 19 | Meta Ads | Meta | OAuth2 URL参数 | 分原生 | 异步 |": "| Internacionais | 19 | Meta Ads | Meta | OAuth2 parâmetro de URL | centavos nativos | Assíncrono |",
"| 国际 | 20 | TikTok Ads | Tiktok | OAuth2 Access-Token | 微元→分 | 同步分页 |": "| Internacionais | 20 | TikTok Ads | Tiktok | OAuth2 Access-Token | microyuan→centavos | Paginação síncrona |",
"| 国际 | 21 | LinkedIn Ads | Linkedin | OAuth2 Bearer | 微元→分 | 同步分页 |": "| Internacionais | 21 | LinkedIn Ads | Linkedin | OAuth2 Bearer | microyuan→centavos | Paginação síncrona |",
"| 国际 | 22 | Snapchat Ads | Snapchat | OAuth2 Bearer | 微元→分 | 同步分页 |": "| Internacionais | 22 | Snapchat Ads | Snapchat | OAuth2 Bearer | microyuan→centavos | Paginação síncrona |",
"| 国际 | 23 | Pinterest Ads | Pinterest | OAuth2 Bearer | 微元→分 | 同步分页 |": "| Internacionais | 23 | Pinterest Ads | Pinterest | OAuth2 Bearer | microyuan→centavos | Paginação síncrona |",
"| 国际 | 24 | Twitter/X Ads | Twitter | OAuth2 Bearer | 微元→分 | 同步分页 |": "| Internacionais | 24 | Twitter/X Ads | Twitter | OAuth2 Bearer | microyuan→centavos | Paginação síncrona |",
"| 国际 | 25 | Amazon Ads | Amazon | OAuth2 + Profile | 分原生 | 异步 |": "| Internacionais | 25 | Amazon Ads | Amazon | OAuth2 + Profile | centavos nativos | Assíncrono |",
"| 国际 | 26 | The Trade Desk | TheTradeDesk | HMAC-SHA256 | 分原生 | 异步 |": "| Internacionais | 26 | The Trade Desk | TheTradeDesk | HMAC-SHA256 | centavos nativos | Assíncrono |",
"| 国际 | 27 | Spotify Ads | Spotify | OAuth2 Bearer | 分原生 | 异步 |": "| Internacionais | 27 | Spotify Ads | Spotify | OAuth2 Bearer | centavos nativos | Assíncrono |",
"| 国际 | 28 | Twitch Ads | Twitch | OAuth2 Bearer+ClientId | 分原生 | 同步 |": "| Internacionais | 28 | Twitch Ads | Twitch | OAuth2 Bearer+ClientId | centavos nativos | Síncrono |",
"| 国际 | 29 | Netflix Ads | Netflix | OAuth2 client_credentials | 分原生 | 同步 |": "| Internacionais | 29 | Netflix Ads | Netflix | OAuth2 client_credentials | centavos nativos | Síncrono |",
"### 接口定义": "### Definição das interfaces",
"### 字段映射": "### Mapeamento de campos",
"每个适配器通过 `FieldMapping` 将平台原始字段转为统一模型，平台特有字段自动落入 `extra` JSON。金额统一为 **分**（人民币）/ **分-cent**（美元）。": "Cada adaptador converte os campos brutos da plataforma para o modelo unificado via `FieldMapping`; os campos específicos da plataforma caem automaticamente no JSON `extra`. Os valores são unificados em **centavos** (yuan) / **centavos-cent** (dólar).",
"## 三、数据库设计": "## 3. Design do banco de dados",
"### 命名规范": "### Convenção de nomenclatura",
"- 表前缀: `erik_`": "- Prefixo de tabela: `erik_`",
"- 主键: `BIGINT UNSIGNED PRIMARY KEY` (无自增，Snowflake ID 生成)": "- Chave primária: `BIGINT UNSIGNED PRIMARY KEY` (sem autoincremento, geração por Snowflake ID)",
"- 引擎: InnoDB，字符集: utf8mb4": "- Engine: InnoDB, charset: utf8mb4",
"### 核心表 (13张)": "### Tabelas principais (13)",
"## 四、Erik Stack 集成": "## 4. Integração Erik Stack",
"| 包 | 用途 | 集成位置 |": "| Pacote | Finalidade | Local de integração |",
"| `erikwang2013/snowflake-php` | 分布式主键 ID | SnowflakeTrait → 所有 Model creating 事件 |": "| `erikwang2013/snowflake-php` | IDs de chave primária distribuídos | SnowflakeTrait → eventos creating de todos os Models |",
"| `erikwang2013/hashids` | API 请求/响应 ID 加解密 | ApiResponse 自动编码 id/*_id 字段 |": "| `erikwang2013/hashids` | Criptografia de IDs em requisições/respostas da API | ApiResponse codifica automaticamente os campos id/*_id |",
"| `erikwang2013/jwt-webman` | JWT 认证令牌 | AuthMiddleware + AuthController |": "| `erikwang2013/jwt-webman` | Token de autenticação JWT | AuthMiddleware + AuthController |",
"| `erikwang2013/encryption` | API 层敏感数据加解密 | EncryptionMiddleware (X-Encrypted 头) |": "| `erikwang2013/encryption` | Criptografia de dados sensíveis na camada de API | EncryptionMiddleware (header X-Encrypted) |",
"| `erikwang2013/encryptable` | DB 字段自动加解密 | PlatformAccount/AuthToken $encryptable |": "| `erikwang2013/encryptable` | Criptografia automática de campos do DB | PlatformAccount/AuthToken $encryptable |",
"| `erikwang2013/webman-scout` | Elasticsearch 数据同步 | config/scout.php |": "| `erikwang2013/webman-scout` | Sincronização de dados Elasticsearch | config/scout.php |",
"| `erikwang2013/season` | 国家旗帜 | PlatformBadge.vue (Unicode 国旗) |": "| `erikwang2013/season` | Bandeiras de países | PlatformBadge.vue (bandeiras Unicode) |",
"| `erikwang2013/poster-php` | 滑块验证码 | CaptchaService + CaptchaWidget |": "| `erikwang2013/poster-php` | Captcha deslizante | CaptchaService + CaptchaWidget |",
"## 五、国际化 (i18n)": "## 5. Internacionalização (i18n)",
"全部界面支持 **中文 (zh-CN)** 和 **English (en)**：": "Todas as interfaces suportam **Chinês (zh-CN)** e **Inglês (en)**:",
"| 端 | 技术 | 翻译量 |": "| Plataforma | Tecnologia | Volume de tradução |",
"| Service API | `erik\\support\\I18n` | 12 消息 keys (Accept-Language header / ?lang= param) |": "| Service API | `erik\\support\\I18n` | 12 chaves de mensagem (header Accept-Language / parâmetro ?lang=) |",
"## 六、验证码": "## 6. Captcha",
"登录等敏感操作需完成滑块验证码（erikwang2013/poster-php）：": "Operações sensíveis como login exigem a conclusão do captcha deslizante (erikwang2013/poster-php):",
"前端 `CaptchaWidget` 组件支持拖拽/触屏，失败自动刷新。后端 AuthController 在登录时校验 captcha_token + captcha_offset。": "O componente `CaptchaWidget` do frontend suporta arrastar/toque e atualiza automaticamente em caso de falha. O AuthController do backend valida captcha_token + captcha_offset no login.",
"### 二次确认": "### Confirmação secundária",
"删除、解绑、批量操作等敏感操作采用\"输入以确认\"模式：": "Operações sensíveis como exclusão, desvinculação e operações em lote usam o modo \"digitar para confirmar\":",
"| 操作 | 确认方式 | 确认词 |": "| Operação | Forma de confirmação | Palavra de confirmação |",
"| 解绑账户 | 输入账户名称 | 账户名称 |": "| Desvincular conta | Digitar o nome da conta | Nome da conta |",
"| 批量启停计划 | 输入固定确认词 | `ENABLE` / `PAUSE` |": "| Iniciar/pausar planos em lote | Digitar a palavra fixa de confirmação | `ENABLE` / `PAUSE` |",
"| 删除告警规则 | 输入规则名称 | 规则名称 |": "| Excluir regra de alerta | Digitar o nome da regra | Nome da regra |",
"| 禁用/启用用户 | 输入用户名 | 用户名 |": "| Desabilitar/habilitar usuário | Digitar o nome de usuário | Nome de usuário |",
"通用 `GlobalConfirm` 组件 + `useConfirmStore` Pinia store 驱动，新增敏感操作只需调用 `confirmStore.show({...})`。": "Conduzido pelo componente `GlobalConfirm` genérico + a Pinia store `useConfirmStore`; para adicionar uma nova operação sensível basta chamar `confirmStore.show({...})`.",
"## 七、安全中间件栈（共 8 层）": "## 7. Pilha de middlewares de segurança (8 camadas no total)",
"### 请求流": "### Fluxo de requisições",
"| 中间件 | 功能 |": "| Middleware | Função |",
"| CorsMiddleware | 跨域请求处理，支持 X-Tenant-Id/X-Encrypted |": "| CorsMiddleware | Tratamento de requisições entre domínios, suporta X-Tenant-Id/X-Encrypted |",
"| RateLimitMiddleware | Redis 滑动窗口限流，默认 60次/60秒 |": "| RateLimitMiddleware | Rate limit com janela deslizante no Redis, padrão 60 req/60s |",
"| SqlGuardMiddleware | SQL 注入模式检测（UNION/DROP/ALTER/注释） |": "| SqlGuardMiddleware | Detecção de padrões de injeção de SQL (UNION/DROP/ALTER/comentários) |",
"| ValidationMiddleware | 输入裁剪 + HTML 标签过滤 |": "| ValidationMiddleware | Corte de entrada + filtragem de tags HTML |",
"| EncryptionMiddleware | 请求解密 + 响应加密（X-Encrypted 头） |": "| EncryptionMiddleware | Descriptografia de requisição + criptografia de resposta (header X-Encrypted) |",
"| AuthMiddleware | JWT Bearer Token 验证（erikwang2013/jwt-webman） |": "| AuthMiddleware | Validação do JWT Bearer Token (erikwang2013/jwt-webman) |",
"| TenantIdentify | 多租户解析（X-Tenant-Id 头 / Session） |": "| TenantIdentify | Resolução multitenant (header X-Tenant-Id / Session) |",
"## 八、Web 管理后台": "## 8. Painel administrativo Web",
"技术栈: Vue 3 + TypeScript + Element Plus + ECharts 5 + Pinia + Axios": "Stack de tecnologia: Vue 3 + TypeScript + Element Plus + ECharts 5 + Pinia + Axios",
"### 已实现页面": "### Páginas implementadas",
"- Axios 泛型类型 `UnwrappedInstance` 自动解包 `ApiResponse<T>` 封装": "- O tipo genérico `UnwrappedInstance` do Axios desembrulha automaticamente o encapsulamento de `ApiResponse<T>`",
"- `vue-tsc --noEmit` **零错误**": "- `vue-tsc --noEmit` com **zero erros**",
"## 九、Flutter App": "## 9. App Flutter",
"PC Web 优先的响应式设计，3 个断点自适应。": "Design responsivo priorizando PC Web, adaptativo em 3 breakpoints.",
"| 断点 | 宽度 | 布局 | 导航 |": "| Breakpoint | Largura | Layout | Navegação |",
"| Mobile | < 600px | 单列卡片 | 底部 NavigationBar |": "| Mobile | < 600px | Cartões em coluna única | NavigationBar inferior |",
"| Tablet | 600-1200px | 双列网格 | Drawer 抽屉 |": "| Tablet | 600-1200px | Grade de duas colunas | Gaveta Drawer |",
"| Desktop | > 1200px | 多列网格 + DataTable | 固定 SideNav (250px) |": "| Desktop | > 1200px | Grade de várias colunas + DataTable | SideNav fixo (250px) |",
"**PC 端与管理后台分工**:": "**Divisão de trabalho entre o PC e o painel administrativo**:",
"- **webman-admin**: 重型管理（深度报表/系统配置/租户管理/批量操作）": "- **webman-admin**: administração pesada (relatórios aprofundados/configuração do sistema/gerenciamento de tenants/operações em lote)",
"- **Flutter Web/PC**: 轻量运营面板（实时盯盘/告警处理/轻量投放，无需 VPN）": "- **Flutter Web/PC**: painel operacional leve (acompanhamento em tempo real/tratamento de alertas/veiculação leve, sem necessidade de VPN)",
"## 十、HarmonyOS App": "## 10. App HarmonyOS",
"技术栈: ArkTS + ArkUI。功能与 Flutter App 对齐。": "Stack de tecnologia: ArkTS + ArkUI. Funcionalidades alinhadas com o App Flutter.",
"## 十一、API 设计": "## 11. Design da API",
"前缀 `/api/v1`，统一响应格式：": "Prefixo `/api/v1`, formato de resposta unificado:",
"### 全部端点": "### Todos os endpoints",
"## 十二、业务逻辑图": "## 12. Diagramas de lógica de negócio",
"### Admin ↔ Service 通信": "### Comunicação Admin ↔ Service",
"### OAuth 平台授权流程": "### Fluxo de autorização da plataforma OAuth",
"### 数据同步 & 告警流程": "### Fluxo de sincronização de dados & alertas",
"### 适配器模式": "### Padrão de adaptador",
"## 十三、数据同步 & 任务调度": "## 13. Sincronização de dados & agendamento de tarefas",
"使用 webman/crontab，Redis 缓存加速。": "Usa webman/crontab, com aceleração por cache Redis.",
"| 任务 | 频率 | 说明 |": "| Tarefa | Frequência | Descrição |",
"| TokenRefreshTask | 每 55 分钟 | 扫描过期 Token，自动刷新 |": "| TokenRefreshTask | A cada 55 minutos | Escaneia Tokens expirados e atualiza automaticamente |",
"| DataSyncTask | 每 10 分钟 | 拉取各平台计划+近2日报表，同步后清仪表盘缓存 |": "| DataSyncTask | A cada 10 minutos | Busca os planos de cada plataforma + relatórios dos últimos 2 dias e limpa o cache do dashboard após a sincronização |",
"| AlertCheckTask | 每 5 分钟 | 遍历启用规则，评估阈值，触发推送 |": "| AlertCheckTask | A cada 5 minutos | Percorre as regras habilitadas, avalia limites e dispara notificações |",
"| RetrySyncTask | 每 3 分钟 | 重试失败同步（erik_sync_errors 表，最多3次，指数退避） |": "| RetrySyncTask | A cada 3 minutos | Repete sincronizações com falha (tabela erik_sync_errors, máximo de 3 vezes, backoff exponencial) |",
"同步策略：适配器 Generator 流式处理，游标/分页防漏，失败自动重试，curl_errno 检查，平台级 QPS 限流。": "Estratégia de sincronização: processamento em fluxo com Generator do adaptador, prevenção de perdas com cursor/paginação, nova tentativa automática em caso de falha, verificação de curl_errno e rate limit de QPS por plataforma.",
"## 十四、部署架构": "## 14. Arquitetura de implantação",
"### 容器化部署": "### Implantação em contêineres",
"### 生产部署流": "### Fluxo de implantação em produção",
"### Docker 一键部署": "### Implantação Docker com um clique",
"## 十五、实施历史": "## 15. Histórico de implementação",
"| 阶段 | 内容 | 状态 |": "| Fase | Conteúdo | Status |",
"| Phase 1 | webman v2 + 管理后台骨架 + 多租户 + OAuth + 巨量 | ✅ |": "| Phase 1 | webman v2 + esqueleto do painel administrativo + multitenant + OAuth + Juliang | ✅ |",
"| Phase 2 | 百度适配器 + 淘宝适配器 + 数据同步 + 报表引擎 | ✅ |": "| Phase 2 | Adaptador Baidu + adaptador Taobao + sincronização de dados + engine de relatórios | ✅ |",
"| Phase 3 | 腾讯 + 友盟 + 快手 + 小红书 (4新) | ✅ |": "| Phase 3 | Tencent + Umeng + Kuaishou + Xiaohongshu (4 novos) | ✅ |",
"| Phase 4 | 微博 + B站 + 优酷 + 美团 + 知乎 + 360 + 搜狗 + 京东 + 拼多多 (9新国内) | ✅ |": "| Phase 4 | Weibo + Bilibili + Youku + Meituan + Zhihu + 360 + Sogou + Jingdong + Pinduoduo (9 novos nacionais) | ✅ |",
"| Phase 4 | Meta + LinkedIn + Snapchat + Pinterest + Twitter + Amazon + TTD + Spotify + Twitch + Netflix + Google + YouTube + TikTok (13新国际) | ✅ |": "| Phase 4 | Meta + LinkedIn + Snapchat + Pinterest + Twitter + Amazon + TTD + Spotify + Twitch + Netflix + Google + YouTube + TikTok (13 novos internacionais) | ✅ |",
"| Phase 5 | 告警系统 + 报表导出 + Flutter App + HarmonyOS App + 仪表盘增强 | ✅ |": "| Phase 5 | Sistema de alertas + exportação de relatórios + App Flutter + App HarmonyOS + melhorias no dashboard | ✅ |",
"| Phase 6 | Erik Stack 集成（snowflake/hashids/jwt-webman/encryption/encryptable/scout/season）| ✅ |": "| Phase 6 | Integração Erik Stack (snowflake/hashids/jwt-webman/encryption/encryptable/scout/season) | ✅ |",
"| Phase 7 | Docker 部署 + 安全加固 (RateLimit/CORS/SQLGuard) + 缓存层 + README | ✅ |": "| Phase 7 | Implantação Docker + reforço de segurança (RateLimit/CORS/SQLGuard) + camada de cache + README | ✅ |",
"| Phase 8 | 目录重组 (apps/) + Admin 独立 webman-admin v2 (PHP后端+ServiceProxy) + RBAC + 审计日志 | ✅ |": "| Phase 8 | Reorganização de diretórios (apps/) + Admin independente webman-admin v2 (backend PHP + ServiceProxy) + RBAC + logs de auditoria | ✅ |",
"| Phase 9 | API 文档 + 平台速率限制 + 同步重试队列 + PHPUnit 20测试 + GitHub Actions CI/CD | ✅ |": "| Phase 9 | Documentação da API + rate limit por plataforma + fila de nova tentativa de sincronização + 20 testes PHPUnit + GitHub Actions CI/CD | ✅ |",
"| Phase 10 | 配置文件中文注释 + .env 注释 + 平台凭据文档 + erik_ 表前缀重写 + BIGINT PK | ✅ |": "| Phase 10 | Comentários em chinês nos arquivos de configuração + comentários no .env + documentação de credenciais das plataformas + reescrita do prefixo erik_ nas tabelas + BIGINT PK | ✅ |",
"| Phase 11 | 国际化 (vue-i18n + I18n.php + Flutter + HarmonyOS) + 滑块验证码 (poster-php) | ✅ |": "| Phase 11 | Internacionalização (vue-i18n + I18n.php + Flutter + HarmonyOS) + captcha deslizante (poster-php) | ✅ |",
"| Phase 12 | 二次确认（输入以确认）— 解绑/删除/批量操作均需键入目标名称方可执行 | ✅ |": "| Phase 12 | Confirmação secundária (digitar para confirmar) — desvincular/excluir/operações em lote exigem digitar o nome do alvo para executar | ✅ |",
"## 十六、Admin 管理后台架构": "## 16. Arquitetura do painel administrativo Admin",
"### PHP 后端（端口 8789）": "### Backend PHP (porta 8789)",
"### 角色权限（RBAC）": "### Papéis e permissões (RBAC)",
"| 角色 | slug | 权限 |": "| Papel | slug | Permissões |",
"| 超级管理员 | super_admin | `*` 全部权限 |": "| Super administrador | super_admin | `*` todas as permissões |",
"| 运营经理 | ops_manager | dashboard, campaigns, reports, alerts, accounts |": "| Gerente de operações | ops_manager | dashboard, campaigns, reports, alerts, accounts |",
"| 数据分析师 | analyst | dashboard, reports |": "| Analista de dados | analyst | dashboard, reports |",
"### Admin 与 Service 通信": "### Comunicação entre Admin e Service",
"Admin 通过 `ServiceProxy`（cURL）调用 service API，转发 JWT Token。Admin 自身负责认证鉴权和用户管理，业务数据完全由 service 提供。": "O Admin chama a API do service via `ServiceProxy` (cURL), encaminhando o JWT Token. O Admin é responsável pela autenticação e gerenciamento de usuários; os dados de negócio são fornecidos integralmente pelo service.",
"## 十七、测试 & CI/CD": "## 17. Testes & CI/CD",
"### PHPUnit 测试套件": "### Suíte de testes PHPUnit",
"每周自动更新 Composer + npm + Docker 依赖。": "As dependências Composer + npm + Docker são atualizadas automaticamente toda semana.",
},
}
